Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2018-08, with the labels that each got.

#7 Adds ci scripts for presubmit checks
  scripts/ci-build.sh
  scripts/ci-make.sh
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#10 fix tests
  Makefile
  scripts/ci-build.sh
  scripts/ci-make.sh
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#4 Machine Config Proposal
  cloud/aws/providerconfig/types.go
  cloud/aws/providerconfig/v1alpha1/types.go
  docs/proposal/machine-config.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#26 MVP Proposal
  docs/history/lessons-learned.md
  docs/proposal/features.md
  docs/proposal/mvp-Private.png
  docs/proposal/mvp-Public.png
  docs/proposal/mvp-architecture.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#22 Clusterctl
  Gopkg.lock
  Makefile
  cloud/aws/deployer/deployer.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/providerconfig/zz_generated.deepcopy.go
  clusterctl/examples/aws/README.md
  clusterctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#27 basic machine actuator and aws instance implmentation
  Gopkg.lock
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/controllers/machine/controller.go
  cloud/aws/services/cluster/service.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#55 Cluster actuator
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/service.go
  cloud/aws/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#65 Adds tests with package cleanup
  Gopkg.lock
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/ec2/service.go
  cloud/aws/services/ec2/vpc.go
  cloud/aws/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
