Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2018-11, with the labels that each got.

#352 Don't assume compilining machine has envsubst
  WORKSPACE
  cmd/clusterctl/examples/aws/BUILD
  cmd/clusterctl/examples/aws/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#354 Configuring aws client with credentials file location
  scripts/ci-aws-cred-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#356 Update yaml to use official sigs.k8s.io fork
  BUILD.bazel
  Gopkg.lock
  WORKSPACE
  cmd/clusterawsadm/BUILD
  cmd/clusterctl/BUILD
  cmd/clusterctl/examples/aws/BUILD
  config/BUILD
  pkg/apis/awsprovider/v1alpha1/BUILD
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/cloud/aws/actuators/machine/BUILD
  vendor/sigs.k8s.io/yaml/.gitignore
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/BUILD.bazel
  vendor/sigs.k8s.io/yaml/CONTRIBUTING.md
  vendor/sigs.k8s.io/yaml/LICENSE
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/RELEASE.md
  vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS
  vendor/sigs.k8s.io/yaml/code-of-conduct.md
  vendor/sigs.k8s.io/yaml/fields.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
  vendor/sigs.k8s.io/yaml/yaml_go110_test.go
  vendor/sigs.k8s.io/yaml/yaml_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#362 Makefile update for local Docker
  Makefile
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#355 Node join
  Gopkg.lock
  Makefile
  cmd/clusterctl/examples/aws/machines.yaml.template
  config/crds/awsprovider_v1alpha1_awsclusterproviderconfig.yaml
  config/manager/manager.yaml
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderstatus_types.go
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/actuators/cluster/BUILD
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/cluster/actuator_test.go
  pkg/cloud/aws/actuators/machine/BUILD
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/mock_machineiface/machineinterface.go
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/interfaces.go
  pkg/cloud/aws/services/mocks/ec2interface.go
  pkg/cloud/aws/services/userdata/BUILD.bazel
  pkg/cloud/aws/services/userdata/bastion.go
  pkg/cloud/aws/services/userdata/controlplane.go
  pkg/cloud/aws/services/userdata/node.go
  pkg/cloud/aws/services/userdata/userdata.go
  pkg/deployer/BUILD.bazel
  pkg/deployer/deployer.go
  pkg/tokens/BUILD.bazel
  pkg/tokens/tokens.go
  vendor/k8s.io/cluster-bootstrap/.github/PULL_REQUEST_TEMPLATE.md
  vendor/k8s.io/cluster-bootstrap/CONTRIBUTING.md
  vendor/k8s.io/cluster-bootstrap/Godeps/Godeps.json
  vendor/k8s.io/cluster-bootstrap/Godeps/OWNERS
  vendor/k8s.io/cluster-bootstrap/Godeps/Readme
  vendor/k8s.io/cluster-bootstrap/LICENSE
  vendor/k8s.io/cluster-bootstrap/OWNERS
  vendor/k8s.io/cluster-bootstrap/README.md
  vendor/k8s.io/cluster-bootstrap/SECURITY_CONTACTS
  vendor/k8s.io/cluster-bootstrap/code-of-conduct.md
  vendor/k8s.io/cluster-bootstrap/token/OWNERS
  vendor/k8s.io/cluster-bootstrap/token/api/BUILD.bazel
  vendor/k8s.io/cluster-bootstrap/token/api/doc.go
  vendor/k8s.io/cluster-bootstrap/token/api/types.go
  vendor/k8s.io/cluster-bootstrap/token/util/BUILD.bazel
  vendor/k8s.io/cluster-bootstrap/token/util/helpers.go
  vendor/k8s.io/cluster-bootstrap/token/util/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#363 Bump Go to 1.11.2
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#360 Add generate-iam-policy-docs command
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  pkg/cloud/aws/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#364 [DOCS] More info on minikube and aws user in the getting started doc
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#366 Fix kubelet argumnets
  pkg/cloud/aws/services/userdata/controlplane.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/XS

#368 Prefer ec2 metdata hostname
  pkg/cloud/aws/services/userdata/controlplane.go
  pkg/cloud/aws/services/userdata/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#369 Fix 'cmd/clusterctl/examples/aws/out/' make target
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#370 Update machines.yaml.template with TypeMeta
  cmd/clusterctl/examples/aws/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#375 Convert to klog
  Gopkg.lock
  pkg/cloud/aws/actuators/cluster/BUILD
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine/BUILD
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/cloudformation/BUILD
  pkg/cloud/aws/services/cloudformation/bootstrap.go
  pkg/cloud/aws/services/cloudformation/cloudformation.go
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/network.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/elb/BUILD
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/record/BUILD
  pkg/record/recorder.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/BUILD.bazel
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/examples/coexist_glog/BUILD.bazel
  vendor/k8s.io/klog/examples/coexist_glog/coexist_glog.go
  vendor/k8s.io/klog/examples/log_file/BUILD.bazel
  vendor/k8s.io/klog/examples/log_file/usage_log_file.go
  vendor/k8s.io/klog/examples/set_output/BUILD.bazel
  vendor/k8s.io/klog/examples/set_output/usage_set_output.go
  vendor/k8s.io/klog/glog/BUILD.bazel
  vendor/k8s.io/klog/glog/README.md
  vendor/k8s.io/klog/glog/glog.go
  vendor/k8s.io/klog/glog/glog_test.go
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#377 Use klog instead of zap logger in manager
  cmd/manager/BUILD
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#378 Deployer GetIP tests
  pkg/cloud/aws/actuators/cluster/BUILD.bazel
  pkg/cloud/aws/services/mocks/BUILD.bazel
  pkg/deployer/BUILD.bazel
  pkg/deployer/deployer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#380 Remove actuator mocks
  Gopkg.lock
  pkg/cloud/aws/actuators/cluster/mock_clusteriface/BUILD
  pkg/cloud/aws/actuators/cluster/mock_clusteriface/clusterinterface.go
  pkg/cloud/aws/actuators/machine/mock_machineiface/BUILD
  pkg/cloud/aws/actuators/machine/mock_machineiface/machineinterface.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#382 Minor cleanup
  Gopkg.lock
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#384 Do not bail early in Machine create
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/userdata/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#385 Remove unused controller code
  pkg/controller/BUILD
  pkg/controller/add_cluster_controller.go
  pkg/controller/add_machine_controller.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#387 Fixed typo in cluster provider config
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#386 Add converters package, use awserrors pkg for all errors
  pkg/cloud/aws/actuators/machine/BUILD.bazel
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/converters/BUILD.bazel
  pkg/cloud/aws/converters/instance.go
  pkg/cloud/aws/converters/tags.go
  pkg/cloud/aws/services/awserrors/errors.go
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/errors.go
  pkg/cloud/aws/services/ec2/filters.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#389 Copy mocks on generate step
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#391 Add tags package
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/filters.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/tags.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/tags/BUILD.bazel
  pkg/cloud/aws/tags/cluster.go
  pkg/cloud/aws/tags/tags.go
  pkg/cloud/aws/tags/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#393 Move filters into a package
  pkg/cloud/aws/filter/BUILD.bazel
  pkg/cloud/aws/filter/ec2.go
  pkg/cloud/aws/filter/types.go
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/account.go
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#341 Update getting started guide
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterctl/examples/aws/generate-yaml.sh
  docs/getting-started.md
  pkg/cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#394 Fix ec2 subnet filter typo
  pkg/cloud/aws/filter/ec2.go
  pkg/cloud/aws/services/ec2/subnets.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#398 Refactor services around actuator scope
  pkg/cloud/aws/actuators/BUILD.bazel
  pkg/cloud/aws/actuators/clients.go
  pkg/cloud/aws/actuators/cluster/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/getters.go
  pkg/cloud/aws/actuators/machine/BUILD.bazel
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/scope.go
  pkg/cloud/aws/services/BUILD.bazel
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/account.go
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/console.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/gateways_test.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/natgateways_test.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/routetables_test.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/service.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/ec2/vpc_test.go
  pkg/cloud/aws/services/elb/BUILD.bazel
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/elb/service.go
  pkg/cloud/aws/services/elb/service_test.go
  pkg/cloud/aws/services/getters.go
  pkg/deployer/BUILD.bazel
  pkg/deployer/deployer.go
  pkg/deployer/deployer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#399 Refactor bastion methods around scope and remove region from status
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderstatus_types.go
  pkg/cloud/aws/actuators/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine_scope.go
  pkg/cloud/aws/actuators/scope.go
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/interfaces.go
  pkg/cloud/aws/services/mocks/ec2interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#400 Add actuator interface tests
  pkg/cloud/aws/actuators/cluster/actuator_test.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#403 Refactor security groups around Scope
  pkg/cloud/aws/actuators/scope.go
  pkg/cloud/aws/services/ec2/network.go
  pkg/cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#406 Refactor NAT & Internet gateways around Scope
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/gateways_test.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/natgateways_test.go
  pkg/cloud/aws/services/ec2/network.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#407 Refactor subnets around Scope
  pkg/cloud/aws/services/ec2/network.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#408 Refactor VPC around Scope
  pkg/cloud/aws/actuators/cluster/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine/BUILD.bazel
  pkg/cloud/aws/services/ec2/network.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/ec2/vpc_test.go
  pkg/cloud/aws/services/interfaces.go
  pkg/cloud/aws/services/mocks/ec2interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#410 Refactor elb package around Scope
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/interfaces.go
  pkg/cloud/aws/services/mocks/elbinterface.go
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#418 Fix deployer initialization, update config files
  config/crds/awsprovider_v1alpha1_awsclusterproviderconfig.yaml
  config/crds/awsprovider_v1alpha1_awsclusterproviderstatus.yaml
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/mocks/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#420 Update committed mocks
  pkg/cloud/aws/services/ec2/mock_ec2iface/ec2api.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#421 Fixup logs
  cmd/clusterctl/BUILD
  cmd/clusterctl/main.go
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#423 Fix security group duplicate rule bug
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#424 Fix possible race condition between machine and cluster actuator
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#428 Add verify-bazel script for CI
  hack/lib/init.sh
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#429 Update Makefile for easier DX
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
