Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2018-09, with the labels that each got.

#71 Adds dev push instructions
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm

#72 Improve dev workflow
  README.md
  clusterctl/examples/aws/generate-yaml.sh
  clusterctl/examples/aws/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#73 Aws client
  Gopkg.lock
  cloud/aws/controllers/cluster/controller.go
  cloud/aws/controllers/machine/controller.go
  clusterctl/examples/aws/generate-yaml.sh
  clusterctl/examples/aws/machines.yaml.template
  clusterctl/examples/aws/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#68 Add initial implementation for vpc
  Gopkg.lock
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/controllers/machine/controller.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/errors.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/ec2/vpc.go
  cloud/aws/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#75 Update dependencies to pull in latest cluster-api
  Gopkg.lock
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#76 refactor tests with gomock
  Gopkg.lock
  Gopkg.toml
  Makefile
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/ec2/mock_ec2iface/mock.go
  cloud/aws/services/ec2/vpc.go
  cloud/aws/services/ec2/vpc_test.go
  hack/generate-mocks.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#82 Add defaults for VPC and Subnets
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/subnets_test.go
  cloud/aws/services/ec2/utils.go
  cloud/aws/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#83 Adds cluster api machine interface mock
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  cloud/aws/services/cluster/mock_machine_interface/mock.go
  cloud/aws/services/ec2/mock_ec2iface/mock.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#85 Add internet gateways
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/network.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#90 Add tests for internet gateways
  cloud/aws/services/ec2/gateways_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#86 Add code to describe/create/associate routing tables.
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/routetables.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#80 machineactuator: Initial Delete implementation
  .gitignore
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#67 Adds simple Exists implementation to machine actuator
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/service.go
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/utils.go
  cloud/aws/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#92 Support pushing dev images to AWS ECR
  README.md
  cmd/cluster-controller/Makefile
  cmd/machine-controller/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#93 machine actuator: Fix typo and restore tests
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#91 machineactuator: Initial Update implementation
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#97 Add code to handle routing tables
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/natgateways.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/routetables_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#101 Fix NPE when deleting not yet created machine
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#106 Store cluster status and remove pointers
  Makefile
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/actuators/cluster/mock_clusteriface/mock.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/cluster/mock_machine_interface/mock.go
  cloud/aws/services/cluster/mock_machineiface/mock.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/gateways_test.go
  cloud/aws/services/ec2/mock_ec2iface/mock.go
  cloud/aws/services/ec2/network.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/routetables_test.go
  hack/generate-mocks.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#102 Fix subnet create
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#107 Add GitHub PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#110 Use real cluster client
  cloud/aws/controllers/cluster/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#108 Add bug/feature issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#105 Dx
  Makefile
  clusterctl/examples/aws/.gitignore
  clusterctl/examples/aws/cluster.yaml.template
  clusterctl/examples/aws/machines.yaml.template
  clusterctl/examples/aws/provider-components.yaml.template
  cmd/cluster-controller/main.go
  cmd/machine-controller/main.go
  envfile.example
Labels: approved, cncf-cla: yes, lgtm, size/M

#113 Refer to `deepcopy-gen` using explicit path names in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#116 Fix generate-yaml.sh example script so it can run from anywhere
  clusterctl/examples/aws/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#118 Refresh README dev instructions
  .gitignore
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#117 Remove the cluster service in favor of directly exposed interfaces
  Makefile
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/actuators/machine/mock_machineiface/mock.go
  cloud/aws/controllers/cluster/controller.go
  cloud/aws/controllers/machine/controller.go
  cloud/aws/services/cluster/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#124 Update Security Contacts
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#131 do not overwrite existing envfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#119 Fix subnet discovery, reconcile route tables, add logs
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/natgateways.go
  cloud/aws/services/ec2/network.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/subnets_test.go
  cloud/aws/services/ec2/vpc.go
  clusterctl/examples/aws/provider-components.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#100 Example improvements
  clusterctl/examples/aws/provider-components.yaml.template
  cmd/cluster-controller/Makefile
  cmd/machine-controller/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#112 Tag created VPC
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/services/ec2/network.go
  cloud/aws/services/ec2/tags.go
  cloud/aws/services/ec2/vpc.go
  cloud/aws/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#133 Update image generation
  README.md
  images/README.md
  images/ansible/.gitignore
  images/ansible/roles/common/defaults/main.yml
  images/ansible/roles/common/tasks/debian.yml
  images/ansible/roles/common/tasks/main.yml
  images/ansible/roles/common/tasks/redhat.yml
  images/ansible/roles/containerd/tasks/debian.yml
  images/ansible/roles/containerd/tasks/redhat.yml
  images/ansible/roles/kubernetes/defaults/main.yml
  images/ansible/roles/kubernetes/tasks/debian.yml
  images/ansible/roles/kubernetes/tasks/redhat.yml
  images/packer/base-images-us-east-1.json
  images/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#134 Tag additional cluster resources
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/gateways_test.go
  cloud/aws/services/ec2/natgateways.go
  cloud/aws/services/ec2/natgateways_test.go
  cloud/aws/services/ec2/network.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/routetables_test.go
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
