Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2018-12, with the labels that each got.

#432 Exclude .git/build-* directory in verify bazel
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#425 Record basic events
  Gopkg.lock
  cmd/manager/main.go
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/record/BUILD
  pkg/record/recorder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#435 Update clusterapi dependency / fixup logs
  .gitignore
  Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/Dockerfile
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/existing/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/bootstrap/existing/existingcluster.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/root.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-cluster-no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-cluster-no-args.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/create-no-args.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/delete-cluster-no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/delete-cluster-no-args.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/delete-no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/delete-no-args.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/no-args.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/validate-cluster-no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/validate-no-args-invalid-flag.golden
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/testdata/validate-no-args.golden
  vendor/sigs.k8s.io/cluster-api/config/manager/manager.yaml
  vendor/sigs.k8s.io/cluster-api/docs/book/provider_implementations/create_actuators.md
  vendor/sigs.k8s.io/cluster-api/docs/book/provider_implementations/overview.md
  vendor/sigs.k8s.io/cluster-api/scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#437 Add kind targets to Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#433 Implement 'version` sub-command
  Makefile
  cmd/clusterawsadm/BUILD
  cmd/clusterawsadm/cmd/BUILD
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterctl/BUILD
  cmd/clusterctl/main.go
  cmd/versioninfo/BUILD
  cmd/versioninfo/versioninfo.go
  cmd/versioninfo/versioninfo_test.go
  hack/print-workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#443 Fix status update error on first run
  Makefile
  pkg/cloud/aws/actuators/BUILD.bazel
  pkg/cloud/aws/actuators/machine_scope.go
  pkg/cloud/aws/actuators/scope.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#436 Adds clusterctl documentation
  docs/clusterctl.md
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#439 v1.13 update
  build/amis/README.md
  build/amis/ansible/roles/containerd/defaults/main.yml
  build/amis/packer/packer.json
  cmd/clusterctl/examples/aws/machines.yaml.template
  docs/amis.md
  pkg/cloud/aws/services/ec2/ami.go
  pkg/cloud/aws/services/userdata/controlplane.go
  pkg/cloud/aws/services/userdata/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#446 Fixes node join for v1.13
  .gitignore
  pkg/cloud/aws/services/certificates/certificates.go
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/userdata/node.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#448 Fixes bazel 0.20 deprecated git_repository native rule
  WORKSPACE
  test/e2e/e2e_suite_test.go
  test/e2e/metacluster_test.go
  test/e2e/util/kind/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#449 Fix manager container imagePullPolicy substitution
  Makefile
  cmd/clusterctl/examples/aws/BUILD
  cmd/clusterctl/examples/aws/aws_manager_image_patch.yaml.template
  cmd/clusterctl/examples/aws/generate-yaml.sh
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#450 Add ability to configure cluster name, remove generateName
  cmd/clusterctl/examples/aws/cluster.yaml.template
  cmd/clusterctl/examples/aws/generate-yaml.sh
  cmd/clusterctl/examples/aws/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#453 Rev manager image
  Makefile
  cmd/clusterctl/examples/aws/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#452 Fix cluster/machine status updates
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/cloud/aws/actuators/BUILD.bazel
  pkg/cloud/aws/actuators/machine_scope.go
  pkg/cloud/aws/actuators/scope.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#456 Enable stack trace error printing in actuators
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#457 fix kubeconfig to use correct cluster name
  .gitignore
  pkg/cloud/aws/services/certificates/certificates.go
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#459 Bump cluster-api dependency
  Gopkg.lock
  Gopkg.toml
  config/BUILD
  test/e2e/BUILD
  vendor/sigs.k8s.io/cluster-api/.github/ISSUE_TEMPLATE/bug_report.md
  vendor/sigs.k8s.io/cluster-api/.github/ISSUE_TEMPLATE/feature_request.md
  vendor/sigs.k8s.io/cluster-api/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/Gopkg.toml
  vendor/sigs.k8s.io/cluster-api/README.md
  vendor/sigs.k8s.io/cluster-api/WORKSPACE
  vendor/sigs.k8s.io/cluster-api/config/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/hack/update-bazel.sh
  vendor/sigs.k8s.io/cluster-api/hack/verify-bazel.sh
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/defaults.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#460 Update Bazel to Go 1.11.4
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#461 Containerd 1.2.1
  build/amis/ansible/roles/containerd/defaults/main.yml
  build/amis/ansible/roles/containerd/tasks/main.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#462 Wait for cloud-init to complete
  build/amis/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
