Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2018-10, with the labels that each got.

#143 Makefile: Fix sourcing of env file.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#111 Add vincepri to cluster-api-aws-maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#139 Improve NAT gateway logs
  cloud/aws/services/ec2/natgateways.go
  cloud/aws/services/ec2/natgateways_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#132 create an instance
  Makefile
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/providerconfig/types.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/ami.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/ec2/subnets.go
  clusterctl/examples/aws/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#141 Security groups! ControlPlane + Node
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/network.go
  cloud/aws/services/ec2/securitygroups.go
  cloud/aws/services/ec2/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#146 Update README with more development instructions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#148 Add security group for bastion host
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#149 Add Instance and InstanceState to v1alpha1 types
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#150 Add region cluster configuration parameter
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/actuators/cluster/interfaces.go
  cloud/aws/controllers/cluster/controller.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/ami.go
  cloud/aws/services/ec2/instances.go
  clusterctl/examples/aws/cluster.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/L

#147 Add ELB package and mocks
  Gopkg.lock
  Makefile
  cloud/aws/services/elb/mock_elbiface/mock.go
  cloud/aws/services/elb/service.go
  cloud/aws/services/elb/service_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#153 Add runInstance method & refactor
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#154 Add security groups to new instances
  Gopkg.lock
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/actuator_test.go
  cloud/aws/deployer/deployer.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#155 Add bastion host
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/actuators/cluster/interfaces.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/ami.go
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/securitygroups.go
  cloud/aws/services/ec2/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#152 VPC Teardown
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/services/ec2/account.go
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/eips.go
  cloud/aws/services/ec2/errors.go
  cloud/aws/services/ec2/filters.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/natgateways.go
  cloud/aws/services/ec2/natgateways_test.go
  cloud/aws/services/ec2/network.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/securitygroups.go
  cloud/aws/services/ec2/service.go
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/subnets_test.go
  cloud/aws/services/ec2/tags.go
  cloud/aws/services/ec2/vpc.go
  cloud/aws/services/wait/wait.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#157 Make key name configurable
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/vpc.go
  clusterctl/examples/aws/cluster.yaml.template
  clusterctl/examples/aws/generate-yaml.sh
  envfile.example
Labels: approved, cncf-cla: yes, lgtm, size/M

#159 Refactor use of consts and minor improvements
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/errors.go
  cloud/aws/services/ec2/filters.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/natgateways.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/securitygroups.go
  cloud/aws/services/ec2/service.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#162 Remove actuator tests
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/actuators/machine/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#163 Getip
  cloud/aws/deployer/deployer.go
  cloud/aws/deployer/deployer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#164 Fix ansible temp folder directory
  images/ansible/ansible.cfg
  images/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#160 Add CloudFormation template for bootstrap
  Gopkg.lock
  Gopkg.toml
  Makefile
  cloud/aws/services/cloudformation/bootstrap.go
  cloud/aws/services/iam/types.go
  clusterctl/examples/aws/bootstrap-cloudformation.yaml
  clusterctl/examples/aws/machines.yaml.template
  cmd/clusterawsadm/cmd/alpha/bootstrap.go
  cmd/clusterawsadm/cmd/alpha/root.go
  cmd/clusterawsadm/cmd/logutil.go
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterawsadm/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#156 Add cluster-api-provider-aws specific tag
  Gopkg.lock
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/eips.go
  cloud/aws/services/ec2/errors.go
  cloud/aws/services/ec2/filters.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/gateways_test.go
  cloud/aws/services/ec2/natgateways.go
  cloud/aws/services/ec2/natgateways_test.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/routetables_test.go
  cloud/aws/services/ec2/securitygroups.go
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/subnets_test.go
  cloud/aws/services/ec2/tags.go
  cloud/aws/services/ec2/vpc.go
  cloud/aws/services/ec2/vpc_test.go
  cloud/aws/services/elb/loadbalancer.go
  cloud/aws/services/elb/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#167 gofmt/govet cleanup
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/ec2/natgateways_test.go
  cloud/aws/services/ec2/subnets_test.go
  cloud/aws/services/ec2/vpc_test.go
  cloud/aws/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#170 Adds generated certificates
  Gopkg.lock
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/deployer/deployer.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/certificates/certificates.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#171 Cleanup some NPE
  cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#169 Use string for IAMInstanceProfile
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#166 Cluster actuator tests, services interfaces, other fixes
  Makefile
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/actuators/cluster/interfaces.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/network.go
  cloud/aws/services/elb/loadbalancer.go
  cloud/aws/services/interfaces.go
  cloud/aws/services/mocks/ec2.go
  cloud/aws/services/mocks/elb.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#172 Set the DNSName during type conversion
  cloud/aws/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 Misc bugfixes
  cloud/aws/deployer/deployer.go
  cloud/aws/services/certificates/certificates.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
  clusterctl/examples/aws/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#176 Use t2.medium in template
  clusterctl/examples/aws/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/XS

#178 Appease the linters
  Makefile
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/controllers/cluster/controller.go
  cloud/aws/controllers/cluster/options/options.go
  cloud/aws/controllers/machine/controller.go
  cloud/aws/controllers/machine/options/options.go
  cloud/aws/providerconfig/register.go
  cloud/aws/providerconfig/types.go
  cloud/aws/providerconfig/v1alpha1/register.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/certificates/certificates.go
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/elb/tags.go
  cloud/aws/services/interfaces.go
  cloud/aws/services/wait/wait.go
  cmd/clusterawsadm/cmd/alpha/root.go
  cmd/clusterawsadm/cmd/root.go
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#181 More getting started fixes
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#182 services/ec2/instances: Fix a small NPE
  cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#184 Refactor clusterawsadm
  cloud/aws/services/awserrors/errors.go
  cloud/aws/services/cloudformation/bootstrap.go
  cloud/aws/services/cloudformation/cloudformation.go
  cloud/aws/services/cloudformation/service.go
  cloud/aws/services/ec2/console.go
  cloud/aws/services/ec2/errors.go
  cloud/aws/services/ec2/vpc.go
  cloud/aws/services/wait/wait.go
  cmd/clusterawsadm/client/client.go
  cmd/clusterawsadm/cmd/alpha/alpha.go
  cmd/clusterawsadm/cmd/alpha/bootstrap.go
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  cmd/clusterawsadm/cmd/alpha/ec2/ec2.go
  cmd/clusterawsadm/cmd/logutil.go
  cmd/clusterawsadm/cmd/root.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#185 Dev helper additions
  hack/cluster-api-dev-helper/cmd/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#183 services/ec2/instances: Add some more glogging to methods
  cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#186 cluster controller: Delete bastion first
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/interfaces.go
  cloud/aws/services/mocks/ec2.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#192 update example and gopkg.lock
  Gopkg.lock
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#193 [clusterawsadm] Do not return error if stack update successful
  cloud/aws/services/awserrors/errors.go
  cloud/aws/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#195 Create certificates in cluster actuator instead of machine actuator
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#198 cloudformation: Add iam::PassRole permission for machine actuator
  cloud/aws/services/cloudformation/bootstrap.go
  cloud/aws/services/sts/identity.go
  cloud/aws/services/sts/service.go
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#197 machine_actuator: Split into separate files
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/security_groups.go
  cloud/aws/actuators/machine/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#199 Misc fixes for release
  .gitignore
  Gopkg.lock
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/controllers/machine/controller.go
  cloud/aws/deployer/deployer.go
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/errors.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/instances_test.go
  cloud/aws/services/elb/loadbalancer.go
  cloud/aws/services/interfaces.go
  cloud/aws/services/mocks/ec2.go
  cloud/aws/services/mocks/elb.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#209 Use the latest release of cluster-api
  Gopkg.lock
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 Use existing machine by tag lookup
  cloud/aws/services/ec2/filters.go
  cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#207 clusterctl: Get API Server endpoint from AWS
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/cluster/actuator_test.go
  cloud/aws/deployer/deployer.go
  cloud/aws/deployer/deployer_test.go
  cloud/aws/services/elb/loadbalancer.go
  cloud/aws/services/interfaces.go
  cloud/aws/services/mocks/elb.go
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#212 Comment out node machine from example
  cloud/aws/services/elb/errors.go
  clusterctl/examples/aws/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#217 Normalize copy notice
  cloud/aws/controllers/cluster/controller.go
  cloud/aws/controllers/cluster/options/options.go
  cloud/aws/controllers/machine/controller.go
  cloud/aws/controllers/machine/options/options.go
  cloud/aws/deployer/deployer.go
  cloud/aws/services/ec2/ami.go
  cloud/aws/services/wait/wait.go
  clusterctl/main.go
  cmd/cluster-controller/main.go
  cmd/clusterawsadm/client/client.go
  cmd/machine-controller/main.go
  hack/cluster-api-dev-helper/cmd/exec.go
  hack/cluster-api-dev-helper/cmd/minikube.go
  hack/cluster-api-dev-helper/cmd/root.go
  hack/cluster-api-dev-helper/cmd/testing.go
  hack/cluster-api-dev-helper/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 Start docs around idempotent AWS resource management
  docs/proposal/aws-resource-handling.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#219 Normalize/Wrap errors
  cloud/aws/services/ec2/bastion.go
  cloud/aws/services/ec2/console.go
  cloud/aws/services/ec2/eips.go
  cloud/aws/services/ec2/filters.go
  cloud/aws/services/ec2/gateways.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/routetables.go
  cloud/aws/services/ec2/securitygroups.go
  cloud/aws/services/ec2/subnets.go
  cloud/aws/services/ec2/vpc.go
  cmd/clusterawsadm/cmd/alpha/ec2/ec2.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#225 Use go env to gather GOPATH in makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#222 Refactor instance security group handling
  cloud/aws/actuators/cluster/actuator.go
  cloud/aws/actuators/machine/actuator.go
  cloud/aws/actuators/machine/security_groups.go
  cloud/aws/actuators/machine/tags.go
  cloud/aws/providerconfig/v1alpha1/types.go
  cloud/aws/providerconfig/v1alpha1/zz_generated.deepcopy.go
  cloud/aws/services/ec2/instances.go
  cloud/aws/services/ec2/securitygroups.go
  cloud/aws/services/interfaces.go
  cloud/aws/services/mocks/ec2.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#216 bastion: Fix bastion code to always lookup via tags
  cloud/aws/services/ec2/bastion.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#227 CRD: remove cluster/machine actuators
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/cluster-controller/Dockerfile
  cmd/cluster-controller/Dockerfile.minikube
  cmd/cluster-controller/Makefile
  cmd/cluster-controller/main.go
  cmd/machine-controller/Dockerfile
  cmd/machine-controller/Dockerfile.minikube
  cmd/machine-controller/Makefile
  cmd/machine-controller/main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#228 CRD Update
  Gopkg.lock
  Gopkg.toml
  Makefile
  clusterctl/main.go
  cmd/clusterawsadm/client/client.go
  cmd/manager/main.go
  pkg/apis/apis.go
  pkg/apis/awsproviderconfig/group.go
  pkg/apis/awsproviderconfig/v1alpha1/doc.go
  pkg/apis/awsproviderconfig/v1alpha1/register.go
  pkg/apis/awsproviderconfig/v1alpha1/types.go
  pkg/apis/awsproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/cluster/actuator_test.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/security_groups.go
  pkg/cloud/aws/controllers/cluster/controller.go
  pkg/cloud/aws/controllers/machine/controller.go
  pkg/cloud/aws/controllers/machine/options/options.go
  pkg/cloud/aws/deployer/deployer.go
  pkg/cloud/aws/providerconfig/doc.go
  pkg/cloud/aws/providerconfig/register.go
  pkg/cloud/aws/providerconfig/types.go
  pkg/cloud/aws/providerconfig/v1alpha1/doc.go
  pkg/cloud/aws/providerconfig/zz_generated.deepcopy.go
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/gateways_test.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/natgateways_test.go
  pkg/cloud/aws/services/ec2/network.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/routetables_test.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/ec2/vpc_test.go
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/interfaces.go
  pkg/cloud/aws/services/mocks/ec2.go
  pkg/cloud/aws/services/mocks/elb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#230 docs/getting-started: fix minor typo
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 clusterctl: fatal on empty kubeconfig
  clusterctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#238 examples: AWS, not OpenStack
  clusterctl/examples/aws/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#237 docs: fix minor typo in "ssm put-parameter" command
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#232 machine actuator: Move some methods to more correct locations
  pkg/cloud/aws/actuators/machine/annotations.go
  pkg/cloud/aws/actuators/machine/security_groups.go
  pkg/cloud/aws/actuators/machine/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#240 Add initial Bazel support
  .bazelrc
  .gitignore
  BUILD.bazel
  WORKSPACE
  build/BUILD
  build/rules.bzl
  clusterctl/BUILD
  cmd/clusterawsadm/BUILD
  cmd/clusterawsadm/client/BUILD
  cmd/clusterawsadm/cmd/BUILD
  cmd/clusterawsadm/cmd/alpha/BUILD
  cmd/clusterawsadm/cmd/alpha/bootstrap/BUILD
  cmd/clusterawsadm/cmd/alpha/ec2/BUILD
  cmd/manager/BUILD
  hack/cluster-api-dev-helper/BUILD
  hack/cluster-api-dev-helper/cmd/BUILD
  hack/print-workspace-status.sh
  hack/update-bazel.sh
  pkg/apis/BUILD
  pkg/apis/awsproviderconfig/BUILD
  pkg/apis/awsproviderconfig/v1alpha1/BUILD
  pkg/cloud/aws/actuators/cluster/BUILD
  pkg/cloud/aws/actuators/cluster/mock_clusteriface/BUILD
  pkg/cloud/aws/actuators/machine/BUILD
  pkg/cloud/aws/actuators/machine/mock_machineiface/BUILD
  pkg/cloud/aws/services/BUILD
  pkg/cloud/aws/services/awserrors/BUILD
  pkg/cloud/aws/services/certificates/BUILD
  pkg/cloud/aws/services/cloudformation/BUILD
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/mock_ec2iface/BUILD
  pkg/cloud/aws/services/elb/BUILD
  pkg/cloud/aws/services/elb/mock_elbiface/BUILD
  pkg/cloud/aws/services/iam/BUILD
  pkg/cloud/aws/services/mocks/BUILD
  pkg/cloud/aws/services/sts/BUILD
  pkg/cloud/aws/services/wait/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/XL

#243 clusterctl: remove unused "NewActuator" call
  clusterctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#244 clusterawsadm: improve user experience
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  cmd/clusterawsadm/cmd/alpha/ec2/ec2.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#248 clusterctl: Remove grabbing kubeconfig on start
  clusterctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#251 adds basic CRD to get started
  config/cluster.yaml
  config/cluster_v1alpha1_cluster.yaml
  config/cluster_v1alpha1_machine.yaml
  config/machine.yaml
  config/manager.yaml
  config/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#255 Return a VPC only if it's available or pending
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/filters.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#257 Cleanup certificates package
  pkg/cloud/aws/services/certificates/certificates.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#258 Improve NAT logging & filtering
  pkg/cloud/aws/services/ec2/account.go
  pkg/cloud/aws/services/ec2/filters.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/natgateways_test.go
  pkg/cloud/aws/services/ec2/network.go
  pkg/cloud/aws/services/ec2/routetables_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#256 Adds kubebuilder migration types
  Gopkg.lock
  Makefile
  PROJECT
  config/crds/awsprovider_v1alpha1_awsclusterproviderconfig.yaml
  config/crds/awsprovider_v1alpha1_awsclusterproviderstatus.yaml
  config/crds/awsprovider_v1alpha1_awsmachineproviderconfig.yaml
  config/crds/awsprovider_v1alpha1_awsmachineproviderstatus.yaml
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_awsprovider_v1alpha1.go
  pkg/apis/awsprovider/group.go
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types_test.go
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderstatus_types.go
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderstatus_types_test.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types_test.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderstatus_types.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderstatus_types_test.go
  pkg/apis/awsprovider/v1alpha1/doc.go
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/apis/awsprovider/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/services/certificates/certificates.go
  pkg/controller/add_cluster_controller.go
  pkg/controller/add_machine_controller.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#261 clusterawsadm: Add command to generate AWS secret
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#262 cluster-api-dev-helper: Make compatible with CRDs
  hack/cluster-api-dev-helper/cmd/minikube.go
  hack/cluster-api-dev-helper/cmd/testing.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#250 clusterawsadm: remove ec2 command tree and ec2 console-output command
  cmd/clusterawsadm/cmd/alpha/alpha.go
  cmd/clusterawsadm/cmd/alpha/ec2/BUILD
  cmd/clusterawsadm/cmd/alpha/ec2/ec2.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#264 Fix looped package installation deprecation
  images/ansible/roles/common/tasks/debian.yml
  images/ansible/roles/common/tasks/redhat.yml
  images/ansible/roles/kubernetes/tasks/debian.yml
  images/ansible/roles/kubernetes/tasks/redhat.yml
  images/ansible/roles/providers/tasks/aws.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#263 Use crds
  Gopkg.lock
  Makefile
  clusterctl/BUILD
  clusterctl/examples/aws/cluster.yaml.template
  clusterctl/examples/aws/machines.yaml.template
  cmd/clusterawsadm/client/BUILD
  cmd/clusterawsadm/client/client.go
  cmd/manager/BUILD
  cmd/manager/main.go
  config/cluster.yaml
  config/machine.yaml
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/apis/awsproviderconfig/BUILD
  pkg/apis/awsproviderconfig/group.go
  pkg/apis/awsproviderconfig/v1alpha1/BUILD
  pkg/apis/awsproviderconfig/v1alpha1/doc.go
  pkg/apis/awsproviderconfig/v1alpha1/register.go
  pkg/apis/awsproviderconfig/v1alpha1/types.go
  pkg/apis/awsproviderconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/actuators/cluster/BUILD
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/cluster/actuator_test.go
  pkg/cloud/aws/actuators/cluster/interfaces.go
  pkg/cloud/aws/actuators/machine/BUILD
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/security_groups.go
  pkg/cloud/aws/services/BUILD
  pkg/cloud/aws/services/ec2/BUILD
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/gateways_test.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/natgateways_test.go
  pkg/cloud/aws/services/ec2/network.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/routetables_test.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/ec2/vpc_test.go
  pkg/cloud/aws/services/elb/BUILD
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/interfaces.go
  pkg/cloud/aws/services/mocks/BUILD
  pkg/cloud/aws/services/mocks/ec2.go
  pkg/cloud/aws/services/mocks/elb.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#249 Use Bazel for CI
  .bazelrc
  clusterctl/BUILD
  cmd/clusterawsadm/client/BUILD
  cmd/clusterawsadm/cmd/alpha/BUILD
  cmd/clusterawsadm/cmd/alpha/bootstrap/BUILD
  cmd/clusterawsadm/cmd/alpha/ec2/BUILD
  cmd/manager/BUILD
  pkg/apis/BUILD
  pkg/apis/awsprovider/BUILD
  pkg/apis/awsprovider/v1alpha1/BUILD
  pkg/cloud/aws/actuators/cluster/BUILD
  pkg/cloud/aws/actuators/machine/BUILD
  pkg/controller/BUILD
  scripts/ci-bazel-build.sh
  scripts/ci-bazel-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#278 Fix aws credentials template for session-token
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#282 Adding a check-install script to the Makefile
  Makefile
  scripts/check-install.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#285 Coalesce test results
  hack/coalesce.py
  scripts/ci-bazel-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#289 Fix NPE in machine actuator
  Makefile
  cmd/clusterawsadm/client/client.go
  cmd/manager/main.go
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#286 Generate manifests with kustomize, fix RBAC
  BUILD.bazel
  Makefile
  clusterctl/examples/aws/.gitignore
  clusterctl/examples/aws/provider-components.yaml.template
  cmd/clusterctl/BUILD
  cmd/clusterctl/examples/aws/.gitignore
  cmd/clusterctl/examples/aws/README.md
  cmd/clusterctl/examples/aws/aws_manager_image_patch.yaml.template
  cmd/clusterctl/examples/aws/bootstrap-cloudformation.yaml
  cmd/clusterctl/examples/aws/cluster.yaml.template
  cmd/clusterctl/examples/aws/generate-yaml.sh
  cmd/clusterctl/examples/aws/machines.yaml.template
  cmd/clusterctl/main.go
  config/default/cluster/kustomization.yaml
  config/default/kustomization.yaml
  config/default/machine/kustomization.yaml
  config/default/provider-components/aws_manager_image_patch.yaml
  config/default/provider-components/kustomization.yaml
  config/generate-yaml.sh
  config/manager/manager.yaml
  config/manager/namespace.yaml
  config/manager/service.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  config/samples/cluster.yaml
  config/samples/machines.yaml
  config/vendored/cluster-api/crds/cluster_v1alpha1_cluster.yaml
  config/vendored/cluster-api/crds/cluster_v1alpha1_machine.yaml
  config/vendored/cluster-api/crds/cluster_v1alpha1_machinedeployment.yaml
  config/vendored/cluster-api/crds/cluster_v1alpha1_machineset.yaml
  config/vendored/cluster-api/default/kustomization.yaml
  config/vendored/cluster-api/manager/manager.yaml
  config/vendored/cluster-api/manager/namespace.yaml
  config/vendored/cluster-api/manager/service.yaml
  config/vendored/cluster-api/rbac/rbac_role.yaml
  config/vendored/cluster-api/rbac/rbac_role_binding.yaml
  pkg/cloud/aws/services/certificates/certificates.go
  scripts/ci-bazel-build.sh
  scripts/ci-bazel-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#293 Correct link to CF templates.
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#295 Fixup table of contents from last commit.
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#298 Correct location of `generate-yaml.sh` script
  docs/getting-started.md
  vendor/golang.org/x/text/collate/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/M

#301 misc post-crd fixes
  Dockerfile
  cmd/clusterawsadm/cmd/root.go
  config/manager/manager.yaml
  pkg/cloud/aws/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#304 Cluster and machine actuator updates status
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/cluster/actuator_test.go
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#307 Fixes for status updates
  Gopkg.lock
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  pkg/apis/awsprovider/v1alpha1/BUILD
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/controller/add_cluster_controller.go
  pkg/controller/add_machine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#308 Fix up the getting started guide
  Makefile
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  cmd/clusterctl/examples/aws/generate-yaml.sh
  docs/getting-started.md
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#317 Cleans up clusterctl workflow
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/cluster/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#328 Fix typo in Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#327 Do not install binaries to gopath
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#291 OWNERS_ALIASES: Add randomvariable (Naadir Jeewa) to maintainers list.
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#332 cleanup vendor
  vendor/golang.org/x/text/collate/build/BUILD
  vendor/golang.org/x/text/collate/build/builder.go
  vendor/golang.org/x/text/collate/build/builder_test.go
  vendor/golang.org/x/text/collate/build/colelem.go
  vendor/golang.org/x/text/collate/build/colelem_test.go
  vendor/golang.org/x/text/collate/build/contract.go
  vendor/golang.org/x/text/collate/build/contract_test.go
  vendor/golang.org/x/text/collate/build/order.go
  vendor/golang.org/x/text/collate/build/order_test.go
  vendor/golang.org/x/text/collate/build/table.go
  vendor/golang.org/x/text/collate/build/trie.go
  vendor/golang.org/x/text/collate/build/trie_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#333 fix check-install for empty GOPATH
  scripts/check-install.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#334 Fix issue if no gopath is set
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#325 Adding test script to test ci credentials work for us
  scripts/ci-aws-cred-test.sh
  scripts/ci-bazel-build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#336 Add state filtering for subnets
  pkg/cloud/aws/services/ec2/filters.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#337 Fix Bazel image building & Makefile GOPATH reference
  Makefile
  build/cluster_api_binary.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S

#338 Fix Bazel image name, remove cmd directive in yaml
  build/cluster_api_binary.bzl
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 Add copy-genmocks target to Make
  .golangci.yml
  Gopkg.lock
  Makefile
  build/asm_shim/c.go
  docs/development.md
  pkg/cloud/aws/actuators/cluster/mock_clusteriface/clusterinterface.go
  pkg/cloud/aws/services/ec2/mock_ec2iface/ec2api.go
  pkg/cloud/aws/services/elb/mock_elbiface/elbapi.go
  pkg/cloud/aws/services/mocks/ec2interface.go
  pkg/cloud/aws/services/mocks/elbinterface.go
  vendor/golang.org/x/text/collate/build/BUILD
  vendor/golang.org/x/text/collate/build/builder.go
  vendor/golang.org/x/text/collate/build/builder_test.go
  vendor/golang.org/x/text/collate/build/colelem.go
  vendor/golang.org/x/text/collate/build/colelem_test.go
  vendor/golang.org/x/text/collate/build/contract.go
  vendor/golang.org/x/text/collate/build/contract_test.go
  vendor/golang.org/x/text/collate/build/order.go
  vendor/golang.org/x/text/collate/build/order_test.go
  vendor/golang.org/x/text/collate/build/table.go
  vendor/golang.org/x/text/collate/build/trie.go
  vendor/golang.org/x/text/collate/build/trie_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#342 fixup vendor
  vendor/golang.org/x/text/collate/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#344 fix gazelle parameters
  BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#340 Improve release tooling
  .gitignore
  BUILD.bazel
  Makefile
  build/cluster_api_binary_image.bzl
  cmd/clusterawsadm/BUILD
  cmd/clusterctl/BUILD
  cmd/manager/BUILD
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#349 *: fix "Kubernetes" typos
  docs/amis.md
  pkg/apis/awsprovider/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#350 pkg/apis/awsprovider/v1alpha1: remove blank lines
  pkg/apis/awsprovider/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
