Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2019-08, with the labels that each got.

#945 Fix error with `make clean-bazel-mocks` when bazel-bin/pkg does not exist
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#946 Attempt to fix up e2e test
  test/e2e/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#949 Fix integration test error
  scripts/ci-bazel-integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#948 [0.3] Update clusterawsadm bootstrap policy
  pkg/cloud/aws/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#951 bugfix: add describe-vpc-attribute to permissions
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#953 Update e2e tests
  WORKSPACE
  hack/e2e.sh
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  scripts/ci-bazel-e2e.sh
  scripts/ci-bazel-integration.sh
  test/e2e/BUILD.bazel
  test/e2e/aws_test.go
  test/e2e/util/kind/setup.go
  test/integration/BUILD.bazel
  test/integration/metacluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#955 Query vpc before attempting to delete
  pkg/cloud/aws/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#958 Update cluster-api to v0.1.9
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/OWNERS_ALIASES
  vendor/sigs.k8s.io/cluster-api/config/default/kustomization.yaml
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/netlify.toml
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_reconciler_test.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/machine_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machinedeployment/machinedeployment_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machineset/machineset_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/util/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/util/util.go
  vendor/sigs.k8s.io/cluster-api/pkg/util/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#957 Update E2E
  WORKSPACE
  go.mod
  go.sum
  hack/e2e.sh
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/update-vendor.sh
  pkg/controller/awscluster/awscluster_controller_test.go
  pkg/controller/awsmachine/awsmachine_controller_test.go
  scripts/ci-bazel-e2e.sh
  scripts/ci-bazel-integration.sh
  test/e2e/BUILD.bazel
  test/e2e/aws_test.go
  test/e2e/kustomization.yaml
  test/e2e/util/kind/setup.go
  test/integration/BUILD.bazel
  test/integration/kustomization.yaml
  test/integration/metacluster_test.go
  vendor/github.com/onsi/gomega/gstruct/BUILD.bazel
  vendor/github.com/onsi/gomega/gstruct/elements.go
  vendor/github.com/onsi/gomega/gstruct/errors/BUILD.bazel
  vendor/github.com/onsi/gomega/gstruct/errors/nested_types.go
  vendor/github.com/onsi/gomega/gstruct/fields.go
  vendor/github.com/onsi/gomega/gstruct/ignore.go
  vendor/github.com/onsi/gomega/gstruct/keys.go
  vendor/github.com/onsi/gomega/gstruct/pointer.go
  vendor/github.com/onsi/gomega/gstruct/types.go
  vendor/k8s.io/klog/klog.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#973 Query vpc before attempting to delete
  pkg/cloud/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#961 Port 0.3 event generation code to master
  pkg/apis/infrastructure/v1alpha2/types.go
  pkg/cloud/services/ec2/BUILD.bazel
  pkg/cloud/services/ec2/gateways.go
  pkg/cloud/services/ec2/natgateways.go
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#976 increase size of bazel e2e test
  test/e2e/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#974 Port #839 forward
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#971 Remove generation from v1alpha1 types
  cmd/clusterawsadm/client/BUILD.bazel
  cmd/clusterawsadm/client/client.go
  cmd/clusterawsadm/cmd/alpha/migrate/BUILD
  cmd/clusterawsadm/cmd/alpha/migrate/migrate.go
  pkg/apis/awsprovider/v1alpha1/doc.go
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/cloud/filter/BUILD.bazel
  pkg/cloud/filter/ec2.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#979 fix for AMI build to detect Amazon Linux
  build/amis/ansible/roles/common/tasks/redhat.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#963 packer: Add image permission and encryption options
  build/amis/README.md
  build/amis/packer/packer.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#975 Port #916 to v1alpha2
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/ec2/eips.go
  pkg/cloud/services/ec2/gateways.go
  pkg/cloud/services/ec2/natgateways.go
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/ec2/vpc_test.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/wait/BUILD.bazel
  pkg/cloud/services/wait/wait.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#985 update dev docs with move to gomod
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#995 fix: update rbac for working with Cluster objects, enable status endpoint
  config/crds/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crds/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/rbac/role.yaml
  pkg/apis/infrastructure/v1alpha2/awscluster_types.go
  pkg/apis/infrastructure/v1alpha2/awsmachine_types.go
  pkg/apis/infrastructure/v1alpha2/types.go
  pkg/cloud/scope/cluster.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#997 fix: pass cluster into machinescope return
  pkg/cloud/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1001 Change APIServer healthcheck to SSL protocol
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#996 fix: base64 decode bootstrap data
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1003 Backport #1001 to 0.3 branch
  pkg/cloud/aws/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#984 Guard against missing instanceID on delete
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1017 fix: avoid duplicate nodeRole label in spec
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1010 [0.3]Update tags for managed subnets for Service type=LoadBalancer
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1002 [0.3] Record machine
  pkg/cloud/aws/actuators/machine/BUILD.bazel
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/control_plane_init_locker.go
  pkg/cloud/aws/actuators/machine/control_plane_init_locker_test.go
  pkg/cloud/aws/actuators/machine/lock_info.go
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/interfaces.go
  pkg/cloud/aws/services/mocks/services_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1021 docs: Make getting started requirements easier to understand
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1024 Do not include input object in the error message
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1025 Do not include input object in the error message
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1023 apply tags to all subnets, not just private, to fix #1008
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1034 chore: set status.ready when machine is running
  pkg/cloud/scope/machine.go
  pkg/controller/awsmachine/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1028 Port controllers
  controllers/BUILD.bazel
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awsmachine_annotations.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_security_groups.go
  controllers/awsmachine_tags.go
  controllers/suite_test.go
  main.go
  pkg/cloud/services/interfaces.go
  pkg/controller/BUILD.bazel
  pkg/controller/add_awscluster.go
  pkg/controller/add_awsmachine.go
  pkg/controller/awscluster/BUILD.bazel
  pkg/controller/awscluster/awscluster_controller.go
  pkg/controller/awscluster/awscluster_controller_suite_test.go
  pkg/controller/awscluster/awscluster_controller_test.go
  pkg/controller/awsmachine/BUILD.bazel
  pkg/controller/awsmachine/awsmachine_controller.go
  pkg/controller/awsmachine/awsmachine_controller_suite_test.go
  pkg/controller/awsmachine/awsmachine_controller_test.go
  pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1030 Update Go 1.12.9
  Dockerfile
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#1031 [0.3] --partition flag for clusterawsadm
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  pkg/cloud/aws/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1029 --partition flag for clusterawsadm
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1039 Update manager image references
  BUILD.bazel
  test/e2e/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1033 add tags for service of type LoadBalancer to create ELB
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1040 Add missing partition argument to ReconcileBootstrapStack call
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1043 Do not exit immediately if gazelle fix finds something; address shellcheck nit
  hack/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1044 Add missing partition argument to ReconcileBootstrapStack call
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1036 :running: Update PR template to match CAPI
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1045 :sparkles: Remove as much kubeadm code/logic as possible
  go.mod
  pkg/cloud/services/kubeadm/BUILD.bazel
  pkg/cloud/services/kubeadm/bootstraptoken.go
  pkg/cloud/services/kubeadm/bootstraptoken_test.go
  pkg/cloud/services/kubeadm/configs.go
  pkg/cloud/services/kubeadm/configs_test.go
  pkg/cloud/services/kubeadm/noderegistration.go
  pkg/cloud/services/kubeadm/noderegistration_test.go
  pkg/cloud/services/kubeadm/scheme.go
  pkg/cloud/services/userdata/BUILD.bazel
  pkg/cloud/services/userdata/controlplane_certs.go
  pkg/cloud/services/userdata/controlplane_init.go
  pkg/cloud/services/userdata/controlplane_join.go
  pkg/cloud/services/userdata/controlplane_test.go
  pkg/cloud/services/userdata/node.go
  pkg/cloud/services/userdata/userdata.go
  pkg/cloud/services/userdata/utils.go
  pkg/tokens/BUILD.bazel
  pkg/tokens/tokens.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/BUILD.bazel
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/arguments.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/cgroupdriver.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/chroot_unix.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/chroot_windows.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/copy.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/endpoint.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/error.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/marshal.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/template.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/version.go
  vendor/k8s.io/kubernetes/pkg/version/.gitattributes
  vendor/k8s.io/kubernetes/pkg/version/BUILD.bazel
  vendor/k8s.io/kubernetes/pkg/version/base.go
  vendor/k8s.io/kubernetes/pkg/version/def.bzl
  vendor/k8s.io/kubernetes/pkg/version/doc.go
  vendor/k8s.io/kubernetes/pkg/version/version.go
  vendor/k8s.io/utils/exec/BUILD.bazel
  vendor/k8s.io/utils/exec/doc.go
  vendor/k8s.io/utils/exec/exec.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, priority/important-longterm, size/XXL

#1046 add capi categories
  api/v1alpha2/awscluster_types.go
  api/v1alpha2/awsmachine_types.go
  api/v1alpha2/awsmachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1048 :sparkles: Remove unnecessary requeues
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1053 :bug: Remove empty patches key in config/crd/kustomization.yaml
  config/crd/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1056 [0.3] 🐛 Only allow controlplane machines to acquire lock
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1058 :bug: Fix reconciliation issue when not specifying an ssh key
  controllers/awsmachine_controller.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1061 ✨ Make example controlplane HA, add toleration to managers
  examples/controlplane/controlplane.yaml
  examples/provider-components/kustomization.yaml
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1060 :sparkles: Add MachineDeployment example
  examples/cluster/cluster.yaml
  examples/generate.sh
  examples/machinedeployment/kustomization.yaml
  examples/machinedeployment/kustomizeconfig.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1020 use cluster api patch helper to do the scope close
  pkg/cloud/scope/BUILD.bazel
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1063 :sparkles: [0.3] Cluster/machine controllers: support concurrency
  cmd/manager/main.go
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/cmd/example-provider/main.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_reconciler_test.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/machine_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/machine_reconciler_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#1064 :bug: Clean up some of the security group events and logs
  pkg/cloud/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1065 :running: Cleanup Makefile targets
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1083 Update tolerations patch
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1082 :running: Allow to provide custom GOPROXY
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1085 :warning: No embedded object meta
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  examples/machinedeployment/machinedeployment.yaml
  go.mod
  go.sum
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1086 🏃‍♂️ Name v1alpha2 imports
  cmd/clusterawsadm/cmd/alpha/migrate/migrate.go
  controllers/suite_test.go
  pkg/cloud/converters/instance.go
  pkg/cloud/converters/tags.go
  pkg/cloud/filter/ec2.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/eips.go
  pkg/cloud/services/ec2/gateways.go
  pkg/cloud/services/ec2/gateways_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/natgateways.go
  pkg/cloud/services/ec2/natgateways_test.go
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/routetables_test.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/securitygroups_test.go
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/subnets_test.go
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/ec2/vpc_test.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/tags/tags.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1087 :sparkles: Add tag to action, update Makefile
  .github/workflows/main.yml
  .gitignore
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1091 :bug: Add unique label for MachineDeployment example
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1090 Make Manager SyncPeriod configurable via a flag
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1088 🐛 Fix bug with requeuing machines from AWSCluster requests
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1094 :bug: Improve handling of instance deletion
  controllers/awsmachine_controller.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1095 ⚠️Rename ssh key name field
  api/v1alpha2/awsmachine_types.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller.go
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
  pkg/cloud/converters/instance.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1089 [0.3] Backport: Refactor wait package to be capped to 10m and simplify
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/wait/wait.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1096 🏃 Add release targets
  .github/workflows/main.yml
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M
