Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2019-10, with the labels that each got.

#1154 :book: Fix broken link in docs/development.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1122 :running: E2E test updates
  .gitignore
  Makefile
  config/default/kustomization.yaml
  config/default/manager_pull_policy.yaml
  controllers/suite_test.go
  go.mod
  hack/ensure-kustomize.sh
  scripts/ci-e2e.sh
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/util/kind/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1159 :book: Improve prerequisites document to be embedded in book
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1162 🏃Align Makefile (release) and hack/tools with other repos
  Makefile
  cloudbuild.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1165 📖 Cleaning up readme.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1170 add well-known tolerations to released CAPA manager manifest
  config/manager/manager.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1174 :sparkles: Apply elb-related tags to managed subnets
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1163 ✨Increase AWSCluster and AWSMachine default concurrency
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1178 🐛 Support running alongside other Cluster API pods in the same namespace with leader election enabled
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1182 🐛 Correct IAM profile for control plane
  examples/controlplane/controlplane.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1168 :bug: Delete cloud provider provisioned load balancers and security groups
  pkg/cloud/filter/ec2.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1184 :running: Fix hack/ensure-kustomize.sh
  hack/ensure-kustomize.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1188 🏃 Add a development dockerfile
  dev.dockerfile
  third_party/forked/README.md
  third_party/forked/rerun-process-wrapper/LICENSE
  third_party/forked/rerun-process-wrapper/README.md
  third_party/forked/rerun-process-wrapper/restart.sh
  third_party/forked/rerun-process-wrapper/start.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1186 :running: Use e2e test helpers and cleanup e2e tests
  Makefile
  api/conversion/cluster.go
  go.mod
  go.sum
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/util/kind/setup.go
  test/integration/metacluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1176 ✨ Add webhook port flag
  config/default/manager_webhook_patch.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1194 🏃Use released manifests for CAPI and CABPK in examples
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1196 🐛 Add omitempty to RouteTableID
  api/v1alpha2/types.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XS

#1192 :bug: Add permission to allow controllers to get tags
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1181 ✨ Instance deletion logs
  controllers/awsmachine_controller.go
  docs/observability.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1199 :running: Update controller-runtime v0.3, Golang v1.12.10, CAPI v0.2.5, CABPK v0.1.3
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1198 🐛 Use sshKeyName from awsCluster if not set in awsMachine
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1206 ⚠️ Remove all v1alpha1 codes
  api/conversion/asserter.go
  api/conversion/cluster.go
  api/conversion/cluster_test.go
  api/conversion/machine.go
  api/conversion/machine_test.go
  api/conversion/machinedeployment.go
  api/conversion/machineset.go
  api/v1alpha2/conversion.go
  api/v1alpha2/doc.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/zz_generated.conversion.go
  go.mod
  go.sum
  pkg/apis/addtoscheme_awsprovider_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/awsprovider/group.go
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderstatus_types.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderstatus_types.go
  pkg/apis/awsprovider/v1alpha1/doc.go
  pkg/apis/awsprovider/v1alpha1/register.go
  pkg/apis/awsprovider/v1alpha1/tags.go
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/apis/awsprovider/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/services/ec2/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1212 🐛 Fix API version in v1alpha3
  api/v1alpha3/groupversion_info.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#1213 🐛Do not attempt to log NAT gateway ID when creation fails
  pkg/cloud/services/ec2/natgateways.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1216 🐛 [0.4] Do not attempt to log NAT gateway ID when creation fails
  pkg/cloud/services/ec2/natgateways.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1217 ✨ Surface inner error from `WaitForWithRetryable`
  pkg/cloud/services/wait/wait.go
  pkg/cloud/services/wait/wait_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1220 :sparkles: Cluster API v1alpha3
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/gateways_test.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/natgateways_test.go
  pkg/cloud/services/ec2/routetables_test.go
  pkg/cloud/services/ec2/securitygroups_test.go
  pkg/cloud/services/ec2/subnets_test.go
  pkg/cloud/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1221 🐛 WaitForWithRetryable should return latest error
  pkg/cloud/services/wait/wait.go
  pkg/cloud/services/wait/wait_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1207 Change the default image in manifests to target release-0.4
  config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1223 :bug: add a default bastion AMI for the eu-north-1 (Stockholm) region
  pkg/cloud/services/ec2/ami.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1224 docs: Delete obsolete documents
  docs/README.md
  docs/clusterctl.md
  docs/creating-multinode-controlplane-clusters.md
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1225 🏃 Cleanup dockerfiles
  Dockerfile
  dev.dockerfile
  third_party/forked/README.md
  third_party/forked/rerun-process-wrapper/LICENSE
  third_party/forked/rerun-process-wrapper/README.md
  third_party/forked/rerun-process-wrapper/restart.sh
  third_party/forked/rerun-process-wrapper/start.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1226 🏃 Fixup code for cabpk merge into capi
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  go.mod
  go.sum
  main.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/ec2/instances_test.go
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1228 :running: Tweak e2e timeout for waitForClusterInfrastructureReady
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1229 :running: Patch up e2e tests
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1219 :running: Update name of AWSMachineTemplate validating webhook
  api/v1alpha3/awsmachinetemplate_webhook.go
  config/webhook/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1230 :bug: Fix AWSMachineTemplate webhook name
  api/v1alpha3/awsmachinetemplate_webhook.go
  config/webhook/manifests.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1231 :running: Additional e2e test fixes
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1234 :running: go.mod: Bump AWS SDK to v1.25.16
  go.mod
  go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1197 :running: Machine controller test
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  go.sum
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1232 🐛Fixes `clusterawsadm version` command
  Makefile
  hack/print-workspace-status.sh
  hack/version.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1245 :running: [e2e] Fetch controller logs when tearing down kind cluster
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1246 :running: [e2e] retrieve controller logs when tearing down kind cluster
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1248 :running: [e2e] Fix region handling for e2e tests
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1249 :running: [e2e] Fix region handling for e2e tests
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1251 :running: [e2e] Fix verification issues with e2e test
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1252 :running: [e2e] Fix verification issues with e2e test
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1250 ✨ LOAD_IMAGE to allow injecting locally built image into kind
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1255 [0.4] 🐛Fixes `clusterawsadm version` command
  Makefile
  hack/print-workspace-status.sh
  hack/version.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1253 Automated cherry pick of #1250: LOAD_IMAGE to allow injecting locally built image into kind
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1257 :sparkles: Allow webhook to be disabled and make leader election namespace configurable
  main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, size/M

#1254 ✨e2e-conformance.sh to be able to run e2e tests
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeversions.yaml
  examples/generate.sh
  examples/machinedeployment/kustomizeversions.yaml
  examples/machinedeployment/machinedeployment.yaml
  hack/ci/README.md
  hack/ci/e2e-conformance.sh
  hack/ensure-kind.sh
  scripts/ci-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1261 ✨Automated cherry pick of #1254: e2e-conformance.sh to be able to run e2e tests
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeversions.yaml
  examples/generate.sh
  examples/machinedeployment/kustomizeversions.yaml
  examples/machinedeployment/machinedeployment.yaml
  hack/ci/README.md
  hack/ci/e2e-conformance.sh
  hack/ensure-kind.sh
  scripts/ci-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1263 🐛 Control plane Internal ELBs now connect to private subnets instead of public subnets
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1244 :running: unit tests for deleting machines
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1258 :bug: Disassociate Elastic IPs on deletion, if still associated
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/cloudformation/bootstrap.go
  pkg/cloud/services/ec2/eips.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1259 :running: [e2e] update credentials used for controller
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1260 :running: [e2e] update credentials used for controller
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1265 :running: [e2e] more e2e fixes
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1266 :running: [e2e] more e2e fixes
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1269 :book: Update available AMI versions
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1268 :running: [e2e] Create access key after creating the prerequisites
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1267 :running: [e2e] Create access key after creating the prerequisites
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1270 :running: [e2e] fix missing kindClient
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1272 :running: [e2e] reinitialize the kindClient after deploying the cluster api components
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1271 :running: [e2e] reinitialize the kindClient after deploying the cluster api components
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1273 :bug: Fix Machine reconciliation of deletion
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1276 :bug: Record events only on AWSMachine
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1281 :running: [e2e] add junit output for e2e tests
  .gitignore
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1282 :running: [e2e] add junit output for e2e tests
  .gitignore
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1285 :bug: Record events only on AWSMachine
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1284 :bug: Revise wait backoff parameters
  pkg/cloud/services/wait/wait.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1287 :bug: Revise wait backoff parameters
  pkg/cloud/services/wait/wait.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1286 :bug: Disassociate Elastic IPs on deletion, if still associated
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/cloudformation/bootstrap.go
  pkg/cloud/services/ec2/eips.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1277 :sparkles: Add printer columns
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/awsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1288 :sparkles: Bump goformation to v3, and remove IAM hacks
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  go.mod
  go.sum
  pkg/cloud/services/cloudformation/bootstrap.go
  pkg/cloud/services/iam/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1293 :sparkles: deleting unused /build directory
  build/README.md
  build/run_in_workspace_with_goroot.bzl
  build/stateful_set_patch.bzl
  build/stateful_set_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1247 🏃 Add MachineDeployment, scale up, down tests
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1294 📖 Document how to generate release notes
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1295 :running: [e2e] fix machinedeployment scaling comparison
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1297 :running: [e2e] delete cloudformation stack on teardown
  pkg/cloud/services/cloudformation/cloudformation.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1298 :running: [e2e] delete cloudformation stack on teardown
  pkg/cloud/services/cloudformation/cloudformation.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1301 Automated cherry pick of #1299: We should propagate any errors during create-stack
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1302 :running: Update generate examples to v1alpha3
  examples/cluster/cluster.yaml
  examples/cluster/kustomizeconfig.yaml
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeconfig.yaml
  examples/generate.sh
  examples/machinedeployment/machinedeployment.yaml
  examples/provider-components/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1303 Drop cabpk from manager tolerations patch
  examples/provider-components/manager_tolerations_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1308 🏃 Bump AWSMachine concurrency to 10, AWSCluster to 5
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1306 :running: [e2e] Add boskos heartbeat
  hack/ci/e2e-conformance.sh
  hack/heartbeat_account.py
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1310 Update cert manager / fix Makefile targets
  Makefile
  config/certmanager/certificate.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_awsclusters.yaml
  config/crd/patches/cainjection_in_awsmachines.yaml
  config/crd/patches/cainjection_in_awsmachinetemplates.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  examples/generate.sh
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1311 :running: [e2e] Update e2e test to use upstream cert-manager
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1304 🐛 Wait for cert-manager in `make create-cluster-management`
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1312 :running: [e2e] Additional e2e tweaks
  scripts/ci-e2e.sh
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1296 :running: [e2e] Forward port MachineDeployment to HEAD
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1309 ✨ AWSCluster: Allow setting ImageLookupOrg at the cluster level
  api/v1alpha3/awscluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1313 :running: [e2e] Fix e2e suite
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
