Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2019-04, with the labels that each got.

#681 Add Roles for ControlPlane and Nodes
  .gitignore
  Gopkg.lock
  pkg/cloud/aws/services/kubeadm/BUILD.bazel
  pkg/cloud/aws/services/kubeadm/aws_defaults.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#684 fix: apply security groups by ENI rather than instance
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#687 fix: add required IAM permissions for modifying ENIs
  pkg/cloud/aws/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#688 Fix make target in doc
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#691 Avoid nil dereference when missing cluster
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#692 Avoid nil dereference when missing cluster
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#689 Update the releasing docs
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#694 Attach node security group to control plane nodes, so control plane n…
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#696 Attach node security group to control plane nodes, so control plane n…
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#698 Add error reason to output if fail to checkout an account from boskos
  hack/checkout_account.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#699 Temporarily add a fix to use account state as "clean" if 'free' fails…
  hack/checkout_account.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#700 Update checkout_account.py to not reuse connections
  hack/checkout_account.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#702 Fix checkout_account.py
  hack/checkout_account.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#703 Make hack/checkin_account.py executable
  hack/checkin_account.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#697 Fix: all traffic ingress rule triggers fatal nil dereference
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#707 Fixes a bug and adds tests for kubeadm defaults
  pkg/cloud/aws/actuators/machine_scope.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/kubeadm/BUILD.bazel
  pkg/cloud/aws/services/kubeadm/aws_defaults.go
  pkg/cloud/aws/services/kubeadm/aws_defaults_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#708 Update listed v1.14 AMIs to v1.14.1
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#710 GZIP user-data
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#701 Make sure Calico can talk IP-in-IP
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#709 Cleans up kubeadm default code and adds tests
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/kubeadm/BUILD.bazel
  pkg/cloud/aws/services/kubeadm/aws_defaults.go
  pkg/cloud/aws/services/kubeadm/aws_defaults_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#713 Logging
  Gopkg.lock
  cmd/manager/main.go
  pkg/cloud/aws/actuators/cluster/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/actuator.go
  vendor/k8s.io/klog/klogr/BUILD.bazel
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#715 Switch dep to use release-0.1 branch instead of version
  Gopkg.lock
  Gopkg.toml
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterdeployer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#720 Ensure `make manifests` generates machines file for HA control plane too.
  cmd/clusterctl/examples/aws/generate-yaml.sh
  cmd/clusterctl/examples/aws/machines-ha.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/M

#721 Add clusterawsadm as make dependency to manifests make target.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#719 Update to Go 1.12
  Makefile
  WORKSPACE
  build/asmshim/BUILD
  build/asmshim/c.go
  build/asmshim/textflag.h
  build/go_mock.bzl
  hack/copy-bazel-mocks.sh
  pkg/cloud/aws/services/ec2/BUILD.bazel
  pkg/cloud/aws/services/ec2/mock_ec2iface/BUILD
  pkg/cloud/aws/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/elb/mock_elbiface/BUILD
  pkg/cloud/aws/services/elb/mock_elbiface/elbapi_mock.go
  pkg/cloud/aws/services/mocks/BUILD.bazel
  pkg/cloud/aws/services/mocks/elbinterface.go
  pkg/cloud/aws/services/mocks/services_mock.go
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/BUILD
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/constants/BUILD
  vendor/k8s.io/kubernetes/cmd/kubeadm/app/util/BUILD
  vendor/k8s.io/kubernetes/pkg/kubelet/apis/config/BUILD
  vendor/k8s.io/kubernetes/pkg/registry/core/service/allocator/BUILD
  vendor/k8s.io/kubernetes/pkg/registry/core/service/ipallocator/BUILD
Labels: approved, cncf-cla: yes, lgtm, size/XL

#723 Add ability to override Organization ID for image lookups
  config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
  pkg/cloud/aws/services/ec2/ami.go
  pkg/cloud/aws/services/ec2/ami_test.go
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#718 feat: support customizing root device size
  config/crds/awsprovider_v1alpha1_awsclusterproviderstatus.yaml
  config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/converters/instance.go
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#725 Adds retry-on-conflict during updates
  Gopkg.lock
  pkg/cloud/aws/actuators/BUILD.bazel
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine_scope.go
  pkg/cloud/aws/actuators/scope.go
  pkg/cloud/aws/services/ec2/BUILD.bazel
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#733 Add the HA machines configuration to bazel
  test/e2e/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#731 Ensure bazel is the correct version
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#712 Update OWNERS_ALIASES and SECURITY_CONTACTS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/M

#735 Fix the prow jobs
  cmd/clusterctl/examples/aws/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#736 [doc] Fix markdown formatting
  docs/creating-multinode-controlplane-clusters.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#738 extract fmt from release tool
  cmd/release/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#739 Use DEFAULT_REGION as the default and REGION as the supplied
  hack/print-workspace-status.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#743 e2e testing improvement
  WORKSPACE
  test/e2e/util/kind/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#726 fix: Don't try to update root size when it's unset
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#744 Scope nodeRef to workload cluster
  cmd/manager/BUILD.bazel
  cmd/manager/main.go
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#746 Fix NPE on delete bastion host
  Gopkg.lock
  Makefile
  pkg/cloud/aws/services/ec2/bastion.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#728 Documentation for creating a new cluster on a different AWS account
  docs/roleassumption.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#741 include machines-ha.yaml.template in release artifacts
  cmd/clusterctl/examples/aws/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/XS

#747 Update AWS sdk, improve log in machine actuator
  Gopkg.lock
  Makefile
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/mock_ec2iface/ec2api_mock.go
  vendor/github.com/aws/aws-sdk-go/NOTICE.txt
  vendor/github.com/aws/aws-sdk-go/aws/awsutil/equal.go
  vendor/github.com/aws/aws-sdk-go/aws/client/logger.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
  vendor/github.com/aws/aws-sdk-go/aws/session/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/aws/session/cabundle_transport.go
  vendor/github.com/aws/aws-sdk-go/aws/session/cabundle_transport_1_5.go
  vendor/github.com/aws/aws-sdk-go/aws/session/cabundle_transport_1_6.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go
  vendor/github.com/aws/aws-sdk-go/service/cloudformation/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudformation/doc.go
  vendor/github.com/aws/aws-sdk-go/service/cloudformation/errors.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/sts/BUILD.bazel
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/aws/aws-sdk-go/service/sts/customizations.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
