Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2019-09, with the labels that each got.

#1098 ✨Update Cluster API to v0.2.0
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1103 🐛 Adds kind and apiversion to example
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1104 :running: Add release binaries target
  Makefile
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1107 :sparkles: Add AdditionalTags to AWSClusterSpec
  api/v1alpha2/awscluster_types.go
  api/v1alpha2/awsmachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1108 🐛 handle an unhandled error
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/ami_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1109 🏃 Context cleanups
  controllers/awsmachine_controller.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1110 :sparkles: Update to cluster-api v0.1.10
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterdeployer_test.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/phases/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/phases/pivot.go
  vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/phases/pivot_test.go
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/config/rbac/rbac_role.yaml
  vendor/sigs.k8s.io/cluster-api/config/rbac/rbac_role_binding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1112 🏃 Remove release notes from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1115 Use latest clusterawsadm for generate-example
  Makefile
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1081 :sparkles: Functions for converting v1a1 types to v1a2
  Makefile
  api/conversion/asserter.go
  api/conversion/cluster.go
  api/conversion/cluster_test.go
  api/conversion/machine.go
  api/conversion/machine_test.go
  api/conversion/machinedeployment.go
  api/conversion/machineset.go
  api/v1alpha2/conversion.go
  api/v1alpha2/doc.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/zz_generated.conversion.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1111 📖 Update getting started guide to prerequisites doc
  README.md
  docs/getting-started.md
  docs/prerequisites.md
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1113 :sparkles: Add support for applying custom tags to all AWS resources we manage
  .gitignore
  api/v1alpha2/tags.go
  api/v1alpha2/tags_test.go
  controllers/awsmachine_controller.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/eips.go
  pkg/cloud/services/ec2/gateways.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/natgateways.go
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, size/L

#1119 ✨ Specified measurement unit for rootdevicesize comment
  api/v1alpha2/awsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1123 ✨ Add prow image building
  .github/workflows/main.yml
  Makefile
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1129 ✨ Record events for credentials and permissions issues
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/scope/cluster.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#1126 ✨ Add ability to customize APIServer LB listener port
  controllers/awscluster_controller.go
  go.mod
  go.sum
  hack/tools/tools.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1144 :bug: remove finalizer when machine is absent
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1147 🐛fix: use clusterScope's port in APIEndpoint
  controllers/awscluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1146 ✨add support for specifying an ENI
  api/v1alpha2/awsmachine_types.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1131 Add go mod verification in CI
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1136 🏃Fix log names are too verbose
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1148 [v1alpha1] :sparkles: Remove use of cloud-init module
  pkg/cloud/aws/services/userdata/controlplane_init.go
  pkg/cloud/aws/services/userdata/controlplane_join.go
  pkg/cloud/aws/services/userdata/node.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1149 :book: Update latest AMI information
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1150 :book: Fix typo in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1152 fix: use copy builtin correctly for security groups
  pkg/cloud/services/cloudformation/bootstrap.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1124 🐛 Specify controller manager broadcaster options so events do not get discarded
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1153 🐛Fix a leak of AWS Tags from between Machine and Cluster resources
  api/v1alpha2/awscluster_types.go
  api/v1alpha2/awsmachine_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/securitygroups_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
