Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2019-07, with the labels that each got.

#862 Add watch and list to secret rbac
  config/rbac/rbac_role.yaml
  pkg/cloud/aws/actuators/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#864 Add watch and list to secret rbac (#862)
  config/rbac/rbac_role.yaml
  pkg/cloud/aws/actuators/cluster/actuator.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XS

#867 doc: Add godoc for GetCoreSecurityGroups
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#863 fix: respect cri socket if set
  pkg/cloud/aws/services/ec2/BUILD.bazel
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/kubeadm/bootstraptoken.go
  pkg/cloud/aws/services/kubeadm/noderegistration.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#868 Prefix templated nodes with cluster names
  cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
  cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
  cmd/clusterctl/examples/aws/machine-deployment.yaml.template
  cmd/clusterctl/examples/aws/machines.yaml.template
Labels: approved, cncf-cla: yes, lgtm, size/S

#870 [0.3] Use cluster label selector for machine list
  pkg/cloud/aws/actuators/machine/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#872 Rev minimum version of Bazel to match requirements
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, sig/apps, size/XS

#855 Match ncdc owner alias membership with k/org
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#779 Fix controlplane machine race
  Gopkg.lock
  config/rbac/rbac_role.yaml
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/cloud/aws/actuators/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/control_plane_lock.go
  pkg/cloud/aws/actuators/machine/BUILD.bazel
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/control_plane_init_locker.go
  pkg/cloud/aws/actuators/machine/control_plane_init_locker_test.go
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#877 Cleanup services/userdata package
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/userdata/BUILD.bazel
  pkg/cloud/aws/services/userdata/controlplane.go
  pkg/cloud/aws/services/userdata/controlplane_certs.go
  pkg/cloud/aws/services/userdata/controlplane_init.go
  pkg/cloud/aws/services/userdata/controlplane_join.go
  pkg/cloud/aws/services/userdata/controlplane_test.go
  pkg/cloud/aws/services/userdata/files.go
  pkg/cloud/aws/services/userdata/node.go
  pkg/cloud/aws/services/userdata/userdata.go
  pkg/cloud/aws/services/userdata/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#881 Avoid infinite APIEndpoints
  pkg/cloud/aws/actuators/scope.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#879 Add additionalUserDataFiles to ClusterSpec
  config/crds/awsprovider_v1alpha1_awsclusterproviderspec.yaml
  config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
  pkg/apis/awsprovider/v1alpha1/BUILD.bazel
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/userdata/controlplane_init.go
  pkg/cloud/aws/services/userdata/controlplane_join.go
  pkg/cloud/aws/services/userdata/files.go
  pkg/cloud/aws/services/userdata/node.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#876 [0.3] Fix race when multiple control plane machines try to initialize the cluster at the same time
  Gopkg.lock
  config/rbac/rbac_role.yaml
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/cloud/aws/actuators/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/BUILD.bazel
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/control_plane_lock.go
  pkg/cloud/aws/actuators/machine/BUILD.bazel
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
  pkg/cloud/aws/actuators/machine/control_plane_init_locker.go
  pkg/cloud/aws/actuators/machine/control_plane_init_locker_test.go
  pkg/deployer/deployer.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#875 Fix ELB panic on deletion
  pkg/cloud/aws/services/elb/BUILD.bazel
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/elb/loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#887 0.3 backports
  OWNERS_ALIASES
  WORKSPACE
  cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
  cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
  cmd/clusterctl/examples/aws/machine-deployment.yaml.template
  cmd/clusterctl/examples/aws/machines.yaml.template
  config/crds/awsprovider_v1alpha1_awsclusterproviderspec.yaml
  config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
  pkg/apis/awsprovider/v1alpha1/BUILD.bazel
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/actuators/scope.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/elb/BUILD.bazel
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/elb/loadbalancer_test.go
  pkg/cloud/aws/services/userdata/BUILD.bazel
  pkg/cloud/aws/services/userdata/controlplane.go
  pkg/cloud/aws/services/userdata/controlplane_certs.go
  pkg/cloud/aws/services/userdata/controlplane_init.go
  pkg/cloud/aws/services/userdata/controlplane_join.go
  pkg/cloud/aws/services/userdata/controlplane_test.go
  pkg/cloud/aws/services/userdata/files.go
  pkg/cloud/aws/services/userdata/node.go
  pkg/cloud/aws/services/userdata/userdata.go
  pkg/cloud/aws/services/userdata/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#893 Don't rely on status for deleting security group ingress rules
  pkg/cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#895 Update Releasing docs
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#897 Update Kubernetes Versions
  README.md
  build/amis/packer/packer.json
  cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
  cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
  cmd/clusterctl/examples/aws/machine-deployment.yaml.template
  cmd/clusterctl/examples/aws/machines.yaml.template
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#898 Backport #897 to release-0.3
  README.md
  build/amis/packer/packer.json
  cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
  cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
  cmd/clusterctl/examples/aws/machine-deployment.yaml.template
  cmd/clusterctl/examples/aws/machines.yaml.template
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#900 Add optional pprof http server
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#901 [0.3] Add optional pprof http server
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#902 Document custom ssh key
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#904 Convert Status.Ready to plain bool
  pkg/apis/infrastructure/v1alpha2/awsmachine_types.go
  pkg/apis/infrastructure/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#839 [0.3] Update events for Machines
  pkg/cloud/aws/actuators/machine/BUILD.bazel
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#907 feature: support set metric address
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#911 Add AMIs for Kubernetes v1.15.1
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#909 Improve AWSMachine reconciliation logic
  config/crds/infrastructure.cluster.sigs.k8s.io_awsmachines.yaml
  pkg/apis/infrastructure/v1alpha2/awsmachine_types.go
  pkg/apis/infrastructure/v1alpha2/zz_generated.deepcopy.go
  pkg/cloud/scope/BUILD.bazel
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/eips.go
  pkg/cloud/services/ec2/gateways.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mocks/services_mock.go
  pkg/controller/awsmachine/BUILD.bazel
  pkg/controller/awsmachine/awsmachine_controller.go
  pkg/controller/awsmachine/awsmachine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#910 Additional Cluster Events
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/cloud/aws/services/certificates/BUILD.bazel
  pkg/cloud/aws/services/certificates/certificates.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#914 Fix make create-cluster-ha
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#908 Do not update LB attachments or providerID in Exists
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine_scope.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#919 Switch apiGroup to cluster.x-k8s.io
  PROJECT
  cmd/manager/main.go
  config/crds/infrastructure.cluster.x-k8s.io_awsclusterproviderspecs.yaml
  config/crds/infrastructure.cluster.x-k8s.io_awsclusterproviderstatuses.yaml
  config/crds/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crds/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crds/kustomization.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1alpha2_awsmachine.yaml
  config/samples/infrastructure_v1alpha2_awsmachinetemplate.yaml
  config/samples/infrastructure_v1alpha2_machine.yaml
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/apis/infrastructure/v1alpha2/doc.go
  pkg/apis/infrastructure/v1alpha2/register.go
  pkg/apis/infrastructure/v1alpha2/types.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#922 Update cluster-api to v0.1.8
  Gopkg.lock
  Makefile
  README.md
  cmd/release/main.go
  docs/amis.md
  docs/releasing.md
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/docs/book/npm-shrinkwrap.json
  vendor/sigs.k8s.io/cluster-api/docs/book/package-lock.json
  vendor/sigs.k8s.io/cluster-api/netlify.toml
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/BUILD.bazel
  vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/cluster_controller.go
  vendor/sigs.k8s.io/cluster-api/pkg/controller/noderef/noderef_controller.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/L

#926 [0.3] Add ownerRef to kubeconfig secret, fix NPE in MachineScope
  pkg/cloud/aws/actuators/cluster/actuator.go
  pkg/cloud/aws/actuators/machine_scope.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#932 Update releasing documentation for image-promoter
  cmd/release/main.go
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#934 Clean bazel mocks before generating them
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#935 Add AWSMachine deletion and finalizer logic
  pkg/apis/infrastructure/v1alpha2/awsmachine_types.go
  pkg/cloud/scope/BUILD.bazel
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/controller/awsmachine/BUILD.bazel
  pkg/controller/awsmachine/awsmachine_controller.go
  test/integration/BUILD.bazel
  test/integration/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#941 Cluster actuator: Remove the control plane ready annotation if no control plane machine is ready
  pkg/cloud/aws/actuators/cluster/actuator.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#916 Implement backoff and retry for AWS eventual consistency
  pkg/cloud/aws/services/awserrors/errors.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/ec2/vpc_test.go
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/wait/BUILD.bazel
  pkg/cloud/aws/services/wait/wait.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/L
