Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2019-06, with the labels that each got.

#802 Fix errant formatting
  docs/upgrade-to-0.3.0.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#804 minor documentation improvements to cluster-api-provider-aws
  README.md
  docs/accessing-instances.md
  docs/clusterctl.md
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#803 Backport to release-0.3: Fix errant formatting (#802)
  README.md
  docs/accessing-instances.md
  docs/clusterctl.md
  docs/getting-started.md
  docs/upgrade-to-0.3.0.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#805 Build and update images for k8s v1.14.2
  README.md
  build/amis/README.md
  build/amis/ansible/roles/common/tasks/redhat.yml
  build/amis/ansible/roles/containerd/defaults/main.yml
  build/amis/ansible/roles/containerd/tasks/redhat.yml
  build/amis/ansible/roles/kubernetes/tasks/redhat.yml
  build/amis/packer/base-images-us-east-1.json
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#806 Remove go get install instructions for binaries
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 Update version compat docs for v0.3
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#810 Update for k8s v1.14.3
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#811 Add availaibilityZone to Machine Spec
  config/crds/awsprovider_v1alpha1_awsmachineproviderspec.yaml
  pkg/apis/awsprovider/v1alpha1/awsmachineproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#812 Update for k8s v1.13.7
  README.md
  build/amis/packer/packer.json
  cmd/clusterctl/examples/aws/machine-deployment.yaml.template
  cmd/clusterctl/examples/aws/machines-ha.yaml.template
  cmd/clusterctl/examples/aws/machines.yaml.template
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#814 Update cluster-api for v0.1.2
  Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#800 Promote sethp-nr and rudoi to reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#819 Add create-cluster-management to Makefile
  Makefile
  cmd/clusterctl/examples/aws/controlplane-machine.yaml.template
  cmd/clusterctl/examples/aws/controlplane-machines-ha.yaml.template
  cmd/clusterctl/examples/aws/generate-yaml.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#820 Bugfix: add ModifyVpcAttribute and DescribeVolumes permissions
  pkg/cloud/aws/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#823 fix: use provided NodeRegistrationOptions as base
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/kubeadm/configs_test.go
  pkg/cloud/aws/services/kubeadm/noderegistration.go
  pkg/cloud/aws/services/kubeadm/noderegistration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#824 OWNERS_ALIASES: Remove randomvariable
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#826 Allow Nodes to talk to Kubelet API Port
  pkg/cloud/aws/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#827 Update some bazel dependencies
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#829 Ignore deleted control plane machines
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/actuators/machine/actuator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#831 Remove unused parameter
  pkg/cloud/aws/actuators/machine/actuator.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/instances_test.go
  pkg/cloud/aws/services/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#832 updated link to kubernetes bot commands
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#834 Add AWS_SESSION_TOKEN to the documentation
  docs/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#742 Switch Kustomize to use bases and not resources.
  config/BUILD.bazel
  config/crds/kustomization.yaml
  config/default/BUILD.bazel
  config/default/kustomization.yaml
  config/manager/BUILD.bazel
  config/manager/kustomization.yaml
  config/rbac/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#833 Improve dependency graph
  cmd/clusterawsadm/cmd/alpha/migrate/BUILD
  cmd/clusterawsadm/cmd/alpha/migrate/migrate.go
  pkg/apis/awsprovider/v1alpha1/BUILD.bazel
  pkg/apis/awsprovider/v1alpha1/awsclusterproviderconfig_types.go
  pkg/apis/awsprovider/v1alpha1/tags.go
  pkg/apis/awsprovider/v1alpha1/types.go
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/aws/converters/BUILD.bazel
  pkg/cloud/aws/converters/tags.go
  pkg/cloud/aws/filter/BUILD.bazel
  pkg/cloud/aws/filter/ec2.go
  pkg/cloud/aws/services/ec2/BUILD.bazel
  pkg/cloud/aws/services/ec2/bastion.go
  pkg/cloud/aws/services/ec2/eips.go
  pkg/cloud/aws/services/ec2/gateways.go
  pkg/cloud/aws/services/ec2/gateways_test.go
  pkg/cloud/aws/services/ec2/instances.go
  pkg/cloud/aws/services/ec2/natgateways.go
  pkg/cloud/aws/services/ec2/natgateways_test.go
  pkg/cloud/aws/services/ec2/routetables.go
  pkg/cloud/aws/services/ec2/routetables_test.go
  pkg/cloud/aws/services/ec2/securitygroups.go
  pkg/cloud/aws/services/ec2/securitygroups_test.go
  pkg/cloud/aws/services/ec2/subnets.go
  pkg/cloud/aws/services/ec2/subnets_test.go
  pkg/cloud/aws/services/ec2/vpc.go
  pkg/cloud/aws/services/elb/BUILD.bazel
  pkg/cloud/aws/services/elb/loadbalancer.go
  pkg/cloud/aws/services/mocks/services_mock.go
  pkg/cloud/aws/tags/BUILD.bazel
  pkg/cloud/aws/tags/cluster.go
  pkg/cloud/aws/tags/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#841 Fix cross compilation issue with bazel 0.26+
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#842 Fix cross compilation issue with bazel 0.26+
  WORKSPACE
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/S

#843 Minor fixes
  cmd/clusterctl/examples/aws/BUILD.bazel
  pkg/apis/awsprovider/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#844 Bazel fixes
  build/run_in_workspace_with_goroot.bzl
  cmd/clusterctl/examples/aws/BUILD.bazel
Labels: approved, cncf-cla: yes, lgtm, size/S

#853 Log userdata size
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#854 More bazel fixes
  Makefile
  WORKSPACE
  build/cluster_api_binary_image.bzl
Labels: approved, cncf-cla: yes, lgtm, size/M

#857 Backports for release-0.3
  Makefile
  WORKSPACE
  build/cluster_api_binary_image.bzl
  pkg/cloud/aws/services/ec2/instances.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#858 Update to cluster-api v0.1.4
  Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/docs/developer/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#859 Update to cluster-api v0.1.4
  Gopkg.lock
  vendor/sigs.k8s.io/cluster-api/Makefile
  vendor/sigs.k8s.io/cluster-api/config/default/manager_image_patch.yaml
  vendor/sigs.k8s.io/cluster-api/docs/developer/releasing.md
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/S

#860 Update for Kubernetes v1.15
  README.md
  build/amis/packer/packer.json
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/M
