Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2019-12, with the labels that each got.

#1377 ✨reconcile apiserver elb tags
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1372 ⚠️ Move Status.APIEndpoints to Spec.ControlPlaneEndpoint
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  controllers/awscluster_controller.go
  go.mod
  go.sum
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1380 :bug: Fix kubeadm types import
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1371 🏃Rename Makefile dev target to create-cluster
  Makefile
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1382 🐛 Add new required ELB permissions
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#1379 [0.4] ⚠️ reconcile apiserver ELB tags
  pkg/cloud/services/cloudformation/bootstrap.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1353 :sparkles: Improves e2e tests by using version flags
  test/e2e/aws_test.go
  test/e2e/conformance_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1360 :running: Updates for test/e2e go.mod
  Makefile
  scripts/ci-e2e-conformance.sh
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1384 :running: [0.4] Remove git branch from version info
  cmd/versioninfo/versioninfo.go
  hack/version.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1218 ✨ Add validation webhook for AWSMachine
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachine_webhook_test.go
  config/webhook/manifests.yaml
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1386 :sparkles: cherry pick of 1341 from release-0.4 to master
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1385 🐛 make create-cluster: Improve cert-manager wait
  Makefile
  examples/machinedeployment/kustomizeconfig.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1388 🏃 Make conformance cluster names unique by default
  Makefile
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1391 🏃 [0.4] Make conformance cluster names unique by default
  Makefile
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1393 🏃 [0.4] conformance: Fix gsutil usage, try capturing all VM logs
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1396 🏃 conformance: Fix gsutil usage, try capturing all VM logs
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1397 🏃 [0.4] conformance: use the right bucket for released vs ci
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1399 🐛 Update KubeadmConfig(s) to v1alpha3
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
  examples/machinedeployment/machinedeployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1400 Revert "🏃 [0.4] conformance: use the right bucket for released vs ci"
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/kustomizeversions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1401 🏃 Update to KIND v0.6.1
  Makefile
  hack/ensure-kind.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1404 :running: Remove clusterctl calls from create-cluster / update CAPI
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1405 :running: Use local_hostname in cloud-init config
  examples/controlplane/controlplane.yaml
  examples/machinedeployment/machinedeployment.yaml
  go.sum
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1406 :running: Use variable to determine cluster name in create-cluster
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1407 ⚠️ Support bootstrap data in secret
  Makefile
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  go.mod
  go.sum
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1408 :bug: Update RBAC to add getting, listing, and watching Secrets for bootstrap data
  config/rbac/role.yaml
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1409 :bug: Base64 the User Data retrieved from the bootstrap secret
  pkg/cloud/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1412 :bug: Fix e2e CABPK imports
  go.mod
  go.sum
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1415 🐛 make create-cluster: use --decode for base64 decoding
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, priority/critical-urgent, size/XS

#1420 ✨ Add support for failure domains
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awscluster_controller.go
  examples/generate.sh
  go.mod
  go.sum
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1424 🐛Fix creation of Internet-facing ELB
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1426 :sparkles: Add support for extra AWS policies in clusterawsadm
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  docs/prerequisites.md
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1431 :bug: Fix broken e2e test caused by #1426
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1432 ✨ Support Tilt for local development
  .dockerignore
  .gitignore
  README.md
  tilt-provider.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#1427 ✨Add version to user-agent for AWS API calls
  Dockerfile
  Makefile
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterawsadm/cmd/version/version.go
  cmd/versioninfo/versioninfo.go
  go.mod
  hack/version.sh
  pkg/cloud/scope/cluster.go
  version/version.go
  version/version_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1430 :running: Update Go 1.13
  .golangci.yml
  Dockerfile
  Makefile
  cmd/release/main.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1434 :running: Exclude pprof lint warning in golangci-lint config
  .golangci.yml
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1421 :sparkles: Add support for updating outdated managed routes
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/routetables_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1348 🏃 Verify LoadBalancer dyanamically provisioned on service creation and deleted after cluster deletion
  Makefile
  test/e2e/aws_test.go
  test/e2e/conformance_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1433 🏃 Let GCB build release images
  Makefile
  cmd/release/main.go
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1394 ✨[0.4] feat: pass instance tags through to root volume
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_tags.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1354 :sparkles: Adds more e2e functional tests
  Makefile
  test/e2e/aws_test.go
  test/e2e/conformance_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1436 🏃 [0.4] Fix loading released artifacts in conformance tests
  examples/controlplane/ci-awsmachine.yaml
  examples/controlplane/ci-controlplane0.yaml
  examples/controlplane/kustomizeversions.yaml
  examples/machinedeployment/ci-add-image-id-to-awsmachinetemplate.yaml
  examples/machinedeployment/kustomizeversions.yaml
  hack/ci/ci-bootstrap.yaml
  hack/ci/e2e-conformance.sh
  hack/ensure-kind.sh
  scripts/ci-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1438 :sparkles: Improves e2e test suite code
  test/e2e/aws_test.go
  test/e2e/conformance_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1443 🏃 [0.4] Add tilt support
  .dockerignore
  .gitignore
  README.md
  tilt-provider.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#1446 🐛 Fix typo in SuccessfulTagVPC event name
  pkg/cloud/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1444 :bug: Fix NPE when instance doens't have a root volume
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1447 🐛 Create events for Elastic IP allocate/disassociate/release
  pkg/cloud/services/ec2/eips.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1458 "url 404"
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1461 fix a 404 url
  README.md
Labels: cncf-cla: yes, needs-ok-to-test, size/XS
