Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-03, with the labels that each got.

#1606 :bug: secrets-manager: Fix error handling
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/secretsmanager/secret.go
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1607 :running: Release artifacts and conformance test tweaks
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  envfile.example
  examples/addons.yaml
  examples/cluster/cluster.yaml
  examples/cluster/kustomization.yaml
  examples/cluster/kustomizeconfig.yaml
  examples/controlplane/controlplane.yaml
  examples/controlplane/kustomizeconfig.yaml
  examples/controlplane/kustomizeversions.yaml
  examples/generate.sh
  examples/machinedeployment/kustomization.yaml
  examples/machinedeployment/kustomizeconfig.yaml
  examples/machinedeployment/kustomizeversions.yaml
  examples/machinedeployment/machinedeployment.yaml
  examples/provider-components/kustomization.yaml
  examples/provider-components/manager_tolerations_patch.yaml
  go.mod
  go.sum
  hack/ci/e2e-conformance.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/cloud/services/ec2/instances.go
  templates/cluster-template.yaml
  templates/kustomization.yaml
  templates/kustomizeversions.yaml
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1614 Update release docs for 0.4
  Makefile
  api/v1alpha2/zz_generated.conversion.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  docs/releasing.md
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1613 Update releasing process doc.
  Makefile
  docs/releasing.md
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1612 :sparkles: Bring AWS SDK in-line with Kubernetes master and add new regions
  go.mod
  go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1615 🏃 [0.4] Add preserveUnknownFields=false
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  examples/generate.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1618 :sparkles: Update CAPI dependency and set MatchPolicy=Equivalent on webhooks
  Makefile
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachinetemplate_webhook.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1600 :book: Add a project roadmap doc
  docs/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1623 :bug: Use latest Calico manifests
  Makefile
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#1625 :bug: panic in createSecurityGroup error reporting - backport to 0.4
  pkg/cloud/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1617 controllers: Implement pause mechanism
  Makefile
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controllers/helpers.go
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1626 :running: Update the CAPI components used for conformance testing
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1621 :warning: 1156 allow no key pair v1alpha3 2020
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/awscluster_conversion_test.go
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1630 :bug: Update failureDomain support to handle it being set on the Machine rather than AWSMachine
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1634 :running: Update e2e tests for SSHKeyName change to pointer
  test/e2e/aws_test.go
  test/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#1633 Normalize vars to have AWS_ prefix
  hack/ci/e2e-conformance.sh
  templates/cluster-template.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1635 :book: v0.5.0 docs
  README.md
  docs/amis.md
  docs/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1636 :sparkles: Update cluster-api dependency as well as k8s and sonobuoy versions for testing
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  go.mod
  go.sum
  hack/ci/e2e-conformance.sh
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1640 :book: Update latest v1.16 and v1.15 AMIs
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1645 :book: Update AMIs for latest k8s releases
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1649 Fix v0.3.0-rc.3 to v0.3.0
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1647 📖 typos: fixing typos
  docs/accessing-instances.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1655 :bug: Watch for unpaused Clusters in AWSCluster controller
  controllers/awscluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1653 :sparkles: Loosen the filter used for image lookups
  pkg/cloud/services/ec2/ami.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1648 :warning: :bug:Add flag option for uncompressed userdata.
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/awsmachine_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  hack/tools/tools.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/instances.go
  test/e2e/conformance_test.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/active, ok-to-test, size/M

#1651 Ensure ELB is resolvable before marking as ready 🐛
  controllers/awscluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1662 🏃 Initialize CR logger earlier
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1663 🏃 Seed the random number generator
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1665 :running: Update dependencies and latest k8s AMI
  README.md
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  docs/amis.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1666 :running: Fixes for the conformance script
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1671 :running: Update cluster-api release used for e2e/conformance tests
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1669 :running: Fix filters in e2e-conformance.sh
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1667 :sparkles: Update predicate handling
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controllers/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1672 :sparkles: Update to latest cluster-api version
  Makefile
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controllers/helpers.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M
