Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-01, with the labels that each got.

#1463 :warning: Remove check for root volume size
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1464 :bug: Fix NPE when dealing with instance RootDeviceSize
  controllers/awsmachine_controller.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1465 :running: Install cabpk and kcp components in e2e tests
  examples/generate.sh
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1453 🐛 Fix deleting AWSCluster when VPC doesn't exist
  pkg/cloud/services/ec2/network.go
  pkg/cloud/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1471 🐛 [0.4] Fix deleting AWSCluster when VPC doesn't exist
  pkg/cloud/services/ec2/network.go
  pkg/cloud/services/ec2/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1470 ✨ add clusterctl-settings.json
  clusterctl-settings.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1456 ⚠️ ELB uses separate security group
  api/v1alpha3/types.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/securitygroups_test.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1477 🏃[0.4] Rev CAPI and CABPK modules
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#1467 🏃 automation to test deletion a EC2 instance which was referenced in machine object
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1479 [0.4] conformance: don't send CI artifacts to release path
  hack/ci/ci-bootstrap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1480 :bug: Fix when AWS return InvalidInstanceID.NotFound with statusCode 400
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1483 :bug: Backport: Fix when AWS return InvalidInstanceID.NotFound with statusCode 400
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, priority/important-soon, size/S

#1481 🐛 Include security groups when reconciling load balancer
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1466 :sparkles: Add support to enable/disable bastion host
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/awscluster_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  go.mod
  go.sum
  pkg/cloud/services/ec2/bastion.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1474 🏃Automate updating machineDeployment with new AwsMachineTemplate name
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1482 ⚠️ Update control plane security group rule to remove 0.0.0.0/0 ingress CIDR
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/securitygroups_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1445 🐛 Generate event when instance fails to launch because no subnets available in an availability zone
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1455 🐛 Persist AWSCluster/AWSMachine finalizers immediately to prevent orphaned AWS resources
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1492 🏃 e2e: don't fail test if log streaming fails
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, size/M

#1493 :running: [e2e] Add waiting for deployment and watching logs for bootstrapper and control plane deployments
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1472 🏃 Automate cluster creation when vpc limit was already hit
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1494 ✨Adding an auth-proxy sidecar container
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1495 :running: Increase e2e test timeout
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1476 ⚠️ ELB uses separate security group
  api/v1alpha2/types.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/securitygroups_test.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1488 ✨Add clusterctl labels to CAPA components
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1502 🏃 Sync cluster-api-maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1497 🏃Add automation to test cluster creation with name length more than 22 characters
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1504 Fix to avoid updating tags when there is no change in them and add unit tests
  api/v1alpha3/tags_test.go
  pkg/cloud/tags/tags.go
  pkg/cloud/tags/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1507 🏃 Update Machine FailureDomain field
  api/v1alpha3/awsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1448 🐛Prevent NPE if Machine's spec.Version is not set by failing the AWSMachine
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1509 :running: Remove deprecated AvailabilityZone field on machine spec
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  go.mod
  go.sum
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
