Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-11, with the labels that each got.

#2052 ✨ Add support for AWS_CONTROLLER_IAM_ROLE env var
  bootstrap/eks/config/manager/kustomization.yaml
  bootstrap/eks/config/manager/manager_args_patch.yaml
  bootstrap/eks/config/manager/manager_iam_patch.yaml
  bootstrap/eks/config/manager/manager_service_account_patch.yaml
  bootstrap/eks/config/manager/serviceaccount.yaml
  config/manager/kustomization.yaml
  config/manager/manager_iam_patch.yaml
  config/manager/manager_service_account_patch.yaml
  config/manager/serviceaccount.yaml
  controlplane/eks/config/manager/kustomization.yaml
  controlplane/eks/config/manager/manager_iam_patch.yaml
  controlplane/eks/config/manager/manager_service_account_patch.yaml
  controlplane/eks/config/manager/serviceaccount.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/topics/specify-management-iam-role.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2090 🐛 Add CNI defaulting to the controller
  controllers/awscluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2092 🐛 fix ownerref group on kube secret and configmap
  pkg/cloud/services/eks/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2095 🐛 Fallback to cluster subnets on update ASG
  pkg/cloud/services/autoscaling/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2094 :book: Update docs to use capa-system namespace
  docs/changing-credentials.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2099 Revert PR 2052 as this breaks the release manifests
  bootstrap/eks/config/manager/kustomization.yaml
  bootstrap/eks/config/manager/manager_iam_patch.yaml
  bootstrap/eks/config/manager/manager_manager_args_patch.yaml
  bootstrap/eks/config/manager/manager_service_account_patch.yaml
  bootstrap/eks/config/manager/serviceaccount.yaml
  config/manager/kustomization.yaml
  config/manager/manager_iam_patch.yaml
  config/manager/manager_service_account_patch.yaml
  config/manager/serviceaccount.yaml
  controlplane/eks/config/manager/kustomization.yaml
  controlplane/eks/config/manager/manager_iam_patch.yaml
  controlplane/eks/config/manager/manager_service_account_patch.yaml
  controlplane/eks/config/manager/serviceaccount.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/topics/specify-management-iam-role.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2098 Makefile: Ensure manifests compile during verify
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2085 🐛 AWSManagedMachinePool: Fix cloud provider key usage and nodegroup IAM role name
  exp/controllers/awsmanagedmachinepool_controller.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/roles.go
  pkg/cloud/services/eks/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2035 🌱 Remove unused allow additional roles feature flag related code
  config/manager/manager.yaml
  main.go
Labels: approved, cncf-cla: yes, hacktoberfest-accepted, lgtm, ok-to-test, size/S

#2072 🐛Validate that additional security groups can not have filters
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachine_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2109 🌱Build new AMIs
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2108 ✨ fix ASG event message
  pkg/cloud/services/autoscaling/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2113 🌱 Remove old terraform scripts
  hack/terraform-gcr-init/README.md
  hack/terraform-gcr-init/user_project.tf
  hack/terraform-gcr-init/variables.tf
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#2111 :bug: awsmachinetemplates: Allow cloudInit.secureSecretsBackend to be defaulted
  api/v1alpha3/awsmachinetemplate_webhook.go
  api/v1alpha3/awsmachinetemplate_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2102 ⚠️ refactor: e2e test reorganisation
  Makefile
  go.mod
  test/e2e/data/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/shared/aws.go
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
  test/e2e/shared/context.go
  test/e2e/shared/defaults.go
  test/e2e/shared/exec.go
  test/e2e/shared/suite.go
  test/e2e/shared/template.go
  test/e2e/suites/conformance/conformance_suite_test.go
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/managed/.gitkeep
  test/e2e/suites/unmanaged/unmanaged_suite_test.go
  test/e2e/suites/unmanaged/unmanaged_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2114 🌱Upgrade e2e Kubernetes version to 1.19.4
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2129 🌱Bump CAPI version to v0.3.11
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
