Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-04, with the labels that each got.

#1679 Added version setup log
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1681 :running: [ci conformance] increase timeout waiting for nodes
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1682 :running: More fixes for conformance test jobs
  Makefile
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1683 ✨ Default cluster ready to false
  api/v1alpha3/awscluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1684 :running: [ci-conformance] Fix ssh-to-node to use instanceId rather than private IP address
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1686 :running: [ci-conformance] Additional conformance test fixes
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1690 :book: Add AMI for k8s v1.18.1
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1560 Add instructions for existing AWS infrastructure
  docs/existing-aws-infrastructure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1692 Update docs on accessing instances 📖
  docs/accessing-instances.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1697 :book: Update AMIs for latest Kubernetes versions
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1687 :running: [ci-conformance] Fix kustomize template to better handle envsubst
  Makefile
  hack/ci/e2e-conformance.sh
  scripts/ci-conformance.sh
  templates/kustomizeversions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1675 Add documentation for multi-AZ control plane 📖
  docs/multi-az-control-plane.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
