Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-07, with the labels that each got.

#1763 :bug: clusterawsadm: ensure role policies work
  cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/zz_generated.deepcopy.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_node.go
  cmd/clusterawsadm/cloudformation/bootstrap/control_plane.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/node.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  go.mod
  go.sum
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1775 Remove sethp-nr from reviewers list
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1781 Add Seth Pellegrino to emeritus reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1740 ✨ Add conditions to AWSMachine
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/conditions_consts.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  go.mod
  go.sum
  pkg/cloud/scope/machine.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e_new/go.mod
  test/e2e_new/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1788 awsmachine_controller: Allow instances to be deleted if ELB is already gone
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1777 ✨ Adds cluster conditions
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/conditions_consts.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  controllers/awscluster_controller.go
  go.sum
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/gateways.go
  pkg/cloud/services/ec2/natgateways.go
  pkg/cloud/services/ec2/natgateways_test.go
  pkg/cloud/services/ec2/network.go
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/ec2/vpc_test.go
  test/e2e_new/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1790 :running: Makefile: Build clean binaries on release
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1791 ✨ Add randomvariable as a maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1789 🐛 Restricts AZ limit to 1 in e2e tests
  test/e2e/aws_test.go
  test/e2e/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#1761 ✨ allow configuration of Bastion host's ingress rules with cidrBlocks field
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/awscluster_webhook.go
  api/v1alpha3/awscluster_webhook_test.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  controllers/awscluster_controller_test.go
  pkg/cloud/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1793 🌱 Opt for a more inclusive "other" category for our emoji
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1783 Update to AWS SDK for Go 1.33.3
  go.mod
  go.sum
  pkg/cloud/services/ec2/gateways.go
  pkg/cloud/services/ec2/gateways_test.go
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/ec2/natgateways.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/securitygroups_test.go
  pkg/cloud/services/ec2/service.go
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/subnets_test.go
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/ec2/vpc_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e_new/go.mod
  test/e2e_new/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1803 🐛 Fix issue with NAT gateway failing due to EIP already been assigned
  pkg/cloud/services/ec2/eips.go
  pkg/cloud/services/ec2/natgateways.go
  pkg/cloud/services/ec2/natgateways_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1802 🐛 Fixes cluster creation with names starting with 'sg-'
  pkg/cloud/services/ec2/securitygroups.go
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1801 🌱 Allows configuring crossZoneLoadBalancing on controlPlaneLoadBalancer
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/awscluster_webhook.go
  api/v1alpha3/awscluster_webhook_test.go
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1805 🌱 Creates NAT GWs in parallel
  pkg/cloud/services/ec2/natgateways.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1807 ✨ controllers: Capture metrics for every AWS API request
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  go.mod
  pkg/cloud/metrics/metrics.go
  pkg/cloud/scope/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1797 🏃 Updates ci script to test using new e2e flow
  go.sum
  scripts/ci-e2e.sh
  test/e2e_new/e2e_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1809 :seedling: Increase golangci timeout
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1760 :running: e2e: Rewrite kubernetes main branch conformance to use clusterctl
  .dockerignore
  Dockerfile.fastbuild
  Makefile
  go.mod
  go.sum
  hack/ci/README.md
  hack/ci/e2e-conformance.sh
  hack/tools/.gitignore
  scripts/ci-conformance.sh
  test/e2e/go.sum
  test/e2e_new/aws_test.go
  test/e2e_new/common.go
  test/e2e_new/conformance_test.go
  test/e2e_new/data/e2e_conf.yaml
  test/e2e_new/data/kubetest/conformance-fast.yaml
  test/e2e_new/data/kubetest/conformance.yaml
  test/e2e_new/data/kubetest/kustomization/kustomization.yaml
  test/e2e_new/data/kubetest/kustomization/kustomizeversions.yaml
  test/e2e_new/e2e_suite_test.go
  test/e2e_new/exec.go
  test/e2e_new/go.mod
  test/e2e_new/go.sum
  test/e2e_new/kubetest/common.go
  test/e2e_new/kubetest/setup.go
  test/e2e_new/kubetest/test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1819 :seedling: ci: disable gofumpt linter
  .golangci.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1820 clusterawsadm: Add bootstrap user back to deprecated alpha command
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1825 ✨ Update to cluster-api v0.3.7
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1823 e2e: Fixups for conformance template generation
  .gitignore
  Makefile
  test/e2e_new/conformance_test.go
  test/e2e_new/data/e2e_conf.yaml
  test/e2e_new/data/kubetest/kustomization/kustomizeversions.yaml
  test/e2e_new/e2e_suite_test.go
  test/e2e_new/kubetest/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1798 🏃 Migrate rest of e2e tests to use clusterctl framework
  Makefile
  test/e2e_new/aws_test.go
  test/e2e_new/data/e2e_conf.yaml
  test/e2e_new/data/infrastructure-aws/cluster-template-limit-az.yaml
  test/e2e_new/data/infrastructure-aws/cluster-template-multi-az.yaml
  test/e2e_new/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1834 🐛 Adds Ready condition to list of owned conditions for AWSMachine and AWSCluster
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1835 🌱 Remove unused make targets
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M

#1841 📖 Update prerequisites.md to add IAM section header
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1833 ✨ Use filters to select subnet for machines
  pkg/cloud/filter/ec2.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1845 test/e2e_new: Use ci/latest version marker for retrieving cross builds
  test/e2e_new/kubetest/setup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1849 🏃‍♂️ Move myself to emeritus reviewers
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS
