Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-02, with the labels that each got.

#1442 :sparkles: Support cross zone load balancing option
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  go.sum
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1515 :running: Switch Kubernetes CI URL
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1516 :running: [0.4] Switch Kubernetes CI URL
  hack/ci/e2e-conformance.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1513 🏃 Automate creating a cluster with name having period symbol
  test/e2e/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1468 :sparkles: Adds test case to verify High Availability
  test/e2e/aws_test.go
  test/e2e/conformance_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1514 :running: Update the version of conversion-gen we are using
  Makefile
  api/v1alpha2/zz_generated.conversion.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1490 :sparkles: ec2: Add support for userdata privacy
  Makefile
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/awsmachine_conversion_test.go
  api/v1alpha2/awsmachine_types.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha2/zz_generated.deepcopy.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachine_webhook_test.go
  api/v1alpha3/awsmachinetemplate_webhook.go
  api/v1alpha3/awsmachinetemplate_webhook_test.go
  api/v1alpha3/types.go
  api/v1alpha3/webhooks.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  docs/README.md
  docs/userdata-privacy.md
  go.mod
  go.sum
  pkg/cloud/converters/tags.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/scope/machine_test.go
  pkg/cloud/services/cloudformation/bootstrap.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/mock_services/secretsmanager_machine_interface_mock.go
  pkg/cloud/services/secretsmanager/cloudinit.go
  pkg/cloud/services/secretsmanager/cloudinit_test.go
  pkg/cloud/services/secretsmanager/secret.go
  pkg/cloud/services/secretsmanager/secret_fetch_script.go
  pkg/cloud/services/secretsmanager/service.go
  pkg/cloud/services/userdata/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1519 :running: Remove hardcoded 3h timeout from hack/heartbeat_account.py
  hack/heartbeat_account.py
  scripts/ci-e2e-conformance.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1518 :running: Remove hardcoded 3h timeout from hack/heartbeat_account.py
  hack/heartbeat_account.py
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1521 :bug: Fix panic in getAPIServerClassicELBSpec
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/bug, kind/failing-test, lgtm, priority/critical-urgent, size/M

#1524 :bug: cloudformation: Add tag permission for secretsmanager
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1517 :sparkles: Support use of AWS Secrets Manager for userdata privacy
  Makefile
  api/v1alpha2/awsmachine_types.go
  api/v1alpha2/types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  docs/README.md
  docs/userdata-privacy.md
  go.mod
  go.sum
  pkg/cloud/converters/tags.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/scope/machine_test.go
  pkg/cloud/services/cloudformation/bootstrap.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/mock_services/secretsmanager_machine_interface_mock.go
  pkg/cloud/services/secretsmanager/cloudinit.go
  pkg/cloud/services/secretsmanager/cloudinit_test.go
  pkg/cloud/services/secretsmanager/secret.go
  pkg/cloud/services/secretsmanager/secret_fetch_script.go
  pkg/cloud/services/secretsmanager/service.go
  pkg/cloud/services/userdata/utils.go
  test/e2e/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1527 :bug: Re-add missing return when reconciling failed machines
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1526 :running: Post encryption fixes
  .golangci.yml
  Makefile
  controllers/awsmachine_controller.go
  pkg/cloud/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1529 :book: Update docs for correctness around userdata-privacy
  docs/userdata-privacy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1528 :book: Update userdata-privacy docs for 0.4
  docs/userdata-privacy.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1525 🏃Test conversions with object fuzzer
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/awsmachinetemplate_conversion.go
  api/v1alpha2/conversion_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1546 🐛fix-failing-test
  hack/ci/ci-bootstrap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1545 🏃cleanup: enable unparam linter
  .golangci.yml
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1498 :sparkles: Add extra root volume options
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/awsmachine_conversion_test.go
  api/v1alpha2/awsmachinetemplate_conversion_test.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachine_webhook_test.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  go.mod
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1548 :book: Update README for latest built AMIs
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1551 :bug: panic in createSecurityGroup error reporting
  pkg/cloud/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1549 🏃 cleanup: enable `gocritic` linter #1543
  .golangci.yml
  api/v1alpha2/awsmachine_conversion.go
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/elb/errors.go
  pkg/internal/hash/base36.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1558 :book: userdata-privacy: Additional troubleshooting info
  docs/userdata-privacy.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1557 ✨add omitempty to networking types that may be empty
  api/v1alpha2/types.go
  api/v1alpha3/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1565 🐛 tagging: skip non-existing root device when tagging
  controllers/awsmachine_tags.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1568 Enabled staticcheck and replace deprecated packages 🏃
  .golangci.yml
  api/v1alpha3/awscluster_webhook.go
  api/v1alpha3/awsclusterlist_webhook.go
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachinelist_webhook.go
  api/v1alpha3/awsmachinetemplatelist_webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1566 🏃 enable <unused> linter rule and fix related issues
  .golangci.yml
  cmd/release/main.go
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1570 🏃enable <gosimple> linter rule and fix violations
  .golangci.yml
  pkg/cloud/awserrors/errors.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1574 :running: Do not set xtrace in hack/ensure-kind.sh
  hack/ensure-kind.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1577 Update and require CRDv1
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_awsclusters.yaml
  config/crd/patches/cainjection_in_awsmachines.yaml
  config/crd/patches/cainjection_in_awsmachinetemplates.yaml
  config/crd/patches/webhook_in_awsclusters.yaml
  config/crd/patches/webhook_in_awsmachines.yaml
  config/crd/patches/webhook_in_awsmachinetemplates.yaml
  controllers/suite_test.go
  examples/addons.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  scripts/fetch_ext_bins.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1559 🏃 Enabled scopelint and fixed reported errors with suggestions
  .golangci.yml
  pkg/cloud/services/ec2/eips.go
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/subnets.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1569 🏃enable <stylecheck> linter rule and fix related issues
  .golangci.yml
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1582 ✨ Backport clusterctl labels to CAPA components
  config/default/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1567 Enabled errorcheck linter and handled errors 🏃
  .golangci.yml
  cmd/clusterawsadm/cmd/alpha/alpha.go
  cmd/clusterawsadm/cmd/alpha/bootstrap/bootstrap.go
  cmd/clusterawsadm/cmd/alpha/migrate/migrate.go
  controllers/awsmachine_controller_test.go
  pkg/cloud/services/ec2/securitygroups.go
  pkg/cloud/services/ec2/subnets_test.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/secretsmanager/cloudinit.go
  pkg/cloud/services/secretsmanager/helpers_test.go
  pkg/internal/hash/base36.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1584 🐛 fix clusterctl-settings.json
  clusterctl-settings.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1575 Refactor kustomize config/ folder
  Makefile
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/default/credentials.yaml
  config/default/kustomization.yaml
  config/default/manager_role_aggregation_patch.yaml
  config/default/namespace.yaml
  config/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/manager/manager_image_patch.yaml
  config/manager/manager_pull_policy.yaml
  config/patch_crd_webhook_namespace.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manager_webhook_patch.yaml
  config/webhook/service.yaml
  config/webhook/webhookcainjection_patch.yaml
  examples/generate.sh
  main.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1547 [0.4] Remove build images during make release
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1597 :bug: Need ARN values different in GOV regions.
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1601 :bug: Bump Calico version to 3.12 for Kubernetes 1.17 compatibility
  examples/addons.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1602 :bug: Bump Calico version to 3.12 for Kubernetes 1.17 compatibility [backport]
  examples/addons.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1593 :warning: Update node instance profile to add support for Session Manager
  pkg/cloud/services/cloudformation/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1599 :bug: Ensure that leader election is still enabled after applying auth proxy
  config/manager/manager_auth_proxy_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1563 🐛 secrets manager: fix error handling when creating secrets (0.4 canonical)
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  go.mod
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/secretsmanager/secret.go
  test/e2e/aws_test.go
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
