Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-12, with the labels that each got.

#2127 📖 docs: e2e test structure ADR
  docs/adr/0003-separate-e2e-packages.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#2133 🐛Fix for CAPI 3.11 upgrade
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2103 :book: Update consuming-existing-aws-infrastructure.md to provide context to where networkSpec belongs
  docs/book/src/topics/consuming-existing-aws-infrastructure.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2120 🌱 add Interruptible field to AWSMachine status
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  controllers/awsmachine_controller.go
  pkg/cloud/scope/machine.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2126 📖 docs: EKS packaging ADR
  docs/adr/0002-eks-packaging.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2100 ✨ Add support for AWS_CONTROLLER_IAM_ROLE env var
  bootstrap/eks/config/default/kustomization.yaml
  bootstrap/eks/config/default/manager_iam_patch.yaml
  bootstrap/eks/config/default/manager_service_account_patch.yaml
  bootstrap/eks/config/manager/kustomization.yaml
  bootstrap/eks/config/manager/manager_args_patch.yaml
  bootstrap/eks/config/rbac/auth_proxy_role_binding.yaml
  bootstrap/eks/config/rbac/kustomization.yaml
  bootstrap/eks/config/rbac/role_binding.yaml
  bootstrap/eks/config/rbac/serviceaccount.yaml
  config/default/kustomization.yaml
  config/default/manager_iam_patch.yaml
  config/default/manager_service_account_patch.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/kustomization.yaml
  config/rbac/role_binding.yaml
  config/rbac/serviceaccount.yaml
  controlplane/eks/config/default/kustomization.yaml
  controlplane/eks/config/default/manager_iam_patch.yaml
  controlplane/eks/config/default/manager_service_account_patch.yaml
  controlplane/eks/config/rbac/auth_proxy_role_binding.yaml
  controlplane/eks/config/rbac/kustomization.yaml
  controlplane/eks/config/rbac/role_binding.yaml
  controlplane/eks/config/rbac/serviceaccount.yaml
  docs/book/src/SUMMARY.md
  docs/book/src/topics/specify-management-iam-role.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2124 Add externalInfraCluster
  controllers/awsmachine_controller.go
  pkg/cloud/scope/externalinfracluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2140 🐛 Set Subnets as an optional property
  exp/api/v1alpha3/awsmachinepool_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2031 CAPA Maintainer promotions
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
  exp/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#2147 :sparkles: clusterawsadm: Allow CLI to take a configuration file to print IAM policy documents
  cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
  cmd/clusterawsadm/cmd/bootstrap/iam/iam_doc.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2077 clusterawsadm: Enable use of shared configuration file
  cmd/clusterawsadm/credentials/credentials.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2150 📖 fix emoji display on contributing guide
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2149 📖 Updated wording on prerequisites doc
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2151 📖 add config example to docs specifying IAM role
  docs/book/src/topics/specify-management-iam-role.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2154 🐛 Error if a loadbalancer exist with the same name in the same region with a different scheme
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2162 🌱 Move ncdc to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2161 🌱 Move ncdc to emeritus status
  OWNERS
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2163 loadbalancer: Fix NPE when comparing load balancers
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2159 :book: Fix some of the broken doc links.
  README.md
  docs/book/src/topics/userdata-privacy.md
  docs/book/src/topics/using-cluster-api-with-cross-account-role-assumption.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2164 🌱 New AMIs for: Kubernetes version 1.19.5, 1.18.13, 1.17.15
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2168 ✨ feat: initial EKS e2e tests
  Dockerfile.fastbuild
  Makefile
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  pkg/cloud/services/iamauth/reconcile.go
  scripts/ci-e2e-eks.sh
  test/e2e/data/cni/calico_eks.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/eks/cluster-template-eks-control-plane-only.yaml
  test/e2e/data/eks/cluster-template-eks-machine-deployment-only.yaml
  test/e2e/data/eks/cluster-template-eks-managed-machinepool-only.yaml
  test/e2e/data/eks/cluster-template-eks-managedmachinepool.yaml
  test/e2e/shared/aws.go
  test/e2e/shared/cluster.go
  test/e2e/shared/common.go
  test/e2e/shared/context.go
  test/e2e/shared/defaults.go
  test/e2e/shared/suite.go
  test/e2e/shared/temp.go
  test/e2e/shared/template.go
  test/e2e/suites/managed/.gitkeep
  test/e2e/suites/managed/README.md
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/control_plane.go
  test/e2e/suites/managed/control_plane_helpers.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/helpers.go
  test/e2e/suites/managed/machine_deployment.go
  test/e2e/suites/managed/machine_deployment_helpers.go
  test/e2e/suites/managed/machine_pool.go
  test/e2e/suites/managed/machine_pool_helpers.go
  test/e2e/suites/managed/managed_suite_test.go
  test/e2e/suites/managed/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
