Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-09, with the labels that each got.

#1902 ✨ feat: added ability to enable EKS via env vars
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/webhook/manager_webhook_patch.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1894 ✨ docs: add eks documentation
  README.md
  docs/README.md
  docs/eks.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1817 ✨ Look up official EKS AMI when appropriate
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  go.mod
  pkg/cloud/scope/clients.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/service.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, size/L

#1903 Update AMIs for latest Kubernetes patch releases
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1909 chore: wire up EKS bootstrapper and AWSMachine controller for AWSManagedControlPlane
  bootstrap/eks/config/rbac/role.yaml
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  bootstrap/eks/main.go
  controllers/awsmachine_controller.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, area/provider/eks, cncf-cla: yes, lgtm, size/L

#1910 :seedling: cloudbuild: Increase timeout, use newer Docker image
  cloudbuild.yaml
Labels: approved, area/release, cncf-cla: yes, lgtm, priority/critical-urgent, size/XS

#1904 Update e2e tests to latest Kubernetes release
  test/e2e/data/e2e_conf.yaml
  test/e2e/kubetest/test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1913 🌱 Reload tilt on exp changes
  tilt-provider.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1914 feat: added machines to managed template
  templates/cluster-template-managed.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1917 Update prerequisites doc regarding bootstrap user 📖
  docs/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1922 🐛Fix clusterawsadm policy mix up
  cmd/clusterawsadm/cloudformation/bootstrap/iam.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1927 🌱 Update to CAPI v0.3.9
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1925 ✨ feat: default iam role for eks
  api/v1alpha3/types.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/zz_generated.deepcopy.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/managed_control_plane.go
  cmd/clusterawsadm/cloudformation/bootstrap/template.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  docs/eks.md
  docs/prerequisites.md
  exp/api/v1alpha3/types.go
  pkg/cloud/services/eks/roles.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1930 Revert "Update to CAPI v0.3.9"
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1920 🌱 Bumps aws-sdk. Creates tags during route table creation
  go.mod
  go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/routetables_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1926 ✨Add ability to specify instance tenancy
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/awsmachinetemplate_webhook.go
  api/v1alpha3/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1931 ✨ Allow specifying subnet IDs for control plane load balancers
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/elb/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1937 :seedling: instances: Sort tag keys so unit tests can succeed
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1928 :book: Update AMIs for Kubernetes v1.16.15 and v1.19.1
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1915 ✨ Persists changes early when using default subnets
  pkg/cloud/services/network/subnets.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1939 📖 docs: added managed template to release docs
  docs/releasing.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1880 Make the VPC error message print the offending name and hint at possi…
  pkg/cloud/services/network/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1938 :seedling: Makefile: Fix code generation for mocks and EKS bootstrap provider
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1943 ✨ chore: changed template name from managed to eks
  Makefile
  docs/eks.md
  docs/releasing.md
  templates/cluster-template-eks.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1932 🐛 AWSMachine ssh key should defer to AWSCluster when nil
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1884 ✨ Unmanaged VPCs don't require public subnets
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1944 Bump Golang version to 1.13.15
  Dockerfile
  Dockerfile.fastbuild
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1948 📖 Add docs on updating AWS credentials used by CAPA
  docs/changing-credentials.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1950 :seedling: Update to controller runtime 0.5.11
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1953 🌱 Verify e2e code compiles as part of pull-cluster-api-provider-aws-build
  Makefile
  scripts/ci-build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1960 fix docs for creating a EKS cluster
  docs/eks.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1952 🐛 Retry with listing all ELBs when listing by tag fails
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/elb/mock_resourcegroupstaggingapiiface/doc.go
  pkg/cloud/services/elb/mock_resourcegroupstaggingapiiface/resourcegroupstaggingapiiface_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1966 :seedling: Bump codebuild timeout for eks control plane
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1905 🌱 Add conditions for the reconcile delete workflow
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/network/network.go
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1973 🌱 Remove references to awsmanagedcontrolplanes.infrastructure
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ekscontrolplanes.yaml
  config/crd/patches/webhook_in_ekscontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1957 🐛 fix: bastion reconcilation and connection error when using `eks` flavor
  api/v1alpha3/awscluster_webhook.go
  api/v1alpha3/awscluster_webhook_test.go
  api/v1alpha3/defaults.go
  api/v1alpha3/types.go
  api/v1alpha3/validate.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook_test.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  docs/accessing-instances.md
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1860 ✨ Implement AWSMachinePools
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_awsmachinepools.yaml
  config/crd/patches/webhook_in_awsmachinepools.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/rbac/role.yaml
  controllers/awsmachine_controller.go
  controllers/suite_test.go
  exp/api/v1alpha3/awsmachinepool_types.go
  exp/api/v1alpha3/conditions_consts.go
  exp/api/v1alpha3/types.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/suite_test.go
  feature/feature.go
  go.mod
  go.sum
  main.go
  pkg/cloud/converters/tags.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/doc.go
  pkg/cloud/services/autoscaling/service.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  tilt-provider.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1963 🌱 Adds e2e test for spot instances
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  test/e2e/aws_test.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/cluster-template-spot-instances.yaml
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1981 Book: Update published topics
  docs/book/src/SUMMARY.md
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1992 🐛 Add externalManagedControlPlane Status to fix node drain under EKS
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1974 Update AMIs for Kubernetes 1.19.2, 1.18.9, 1.17.12
  README.md
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1994 🐛 externalManagedControlPlane status field should have been optional
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1858 🌱 Support using custom endpoints for AWS services
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  controlplane/eks/main.go
  main.go
  pkg/cloud/endpoints/endpoints.go
  pkg/cloud/endpoints/endpoints_test.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/session.go
  pkg/cloud/services/secretsmanager/cloudinit.go
  pkg/cloud/services/secretsmanager/cloudinit_test.go
  pkg/cloud/services/secretsmanager/secret_fetch_script.go
Labels: approved, area/security, cncf-cla: yes, lgtm, ok-to-test, size/L
