Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-06, with the labels that each got.

#1713 :book: Single controller multitenancy proposal v3
  Makefile
  docs/Dockerfile
  docs/Makefile
  docs/README.md
  docs/proposal/20180821-machine-config.md
  docs/proposal/20180827-feature-model.md
  docs/proposal/20180827-mvp-architecture-private.png
  docs/proposal/20180827-mvp-architecture-public.png
  docs/proposal/20180827-mvp-architecture.md
  docs/proposal/20181010-aws-resource-handling.md
  docs/proposal/20200506-single-controller-multitenancy-flow.plantuml
  docs/proposal/20200506-single-controller-multitenancy-flow.svg
  docs/proposal/20200506-single-controller-multitenancy.md
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1716 🏃 Refactor e2e tests to use clusterctl framework from CAPI
  .gitignore
  Makefile
  test/e2e/aws_test.go
  test/e2e_new/aws_test.go
  test/e2e_new/common.go
  test/e2e_new/config/aws-dev.yaml
  test/e2e_new/data/cni/calico.yaml
  test/e2e_new/e2e_suite_test.go
  test/e2e_new/go.mod
  test/e2e_new/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1721 ✨ Changes to the default subnet logic
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  docs/existing-aws-infrastructure.md
  docs/multi-az-control-plane.md
  pkg/cloud/services/ec2/routetables.go
  pkg/cloud/services/ec2/routetables_test.go
  pkg/cloud/services/ec2/subnets.go
  pkg/cloud/services/ec2/subnets_test.go
  pkg/internal/cidr/cidr.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1749 Bump cluster creation timeout for conformance in multi-AZ
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1747 ✨ Allow user defined ingress rules for CNI
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_webhook.go
  api/v1alpha3/awscluster_webhook_test.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/webhook/manifests.yaml
  config/webhook/webhookcainjection_patch.yaml
  pkg/cloud/scope/cluster.go
  pkg/cloud/services/ec2/securitygroups.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1758 🐛 Check before (de)registering with ELB
  controllers/awsmachine_controller.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1759 create a bastion host if it's enabled in the spec, regardless of managed or unmanaged VPC
  pkg/cloud/services/ec2/bastion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1737 :bug: Ignore "not found" errors when deregistering ELB instances
  pkg/cloud/services/elb/loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1766 GCloud note and README instruction for folks that might wanna build a…
  Makefile
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1767 🐛 Preserve all VPCSpec fields
  pkg/cloud/services/ec2/vpc.go
  pkg/cloud/services/ec2/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1774 🐛 Delete bastion regardless of VPC type
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/bastion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
