Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2020-10, with the labels that each got.

#1996 :bug: Fix NPE when deleting security groups on cluster deletion
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1998 🌱 fix: incorrect capitalization for eks field
  cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1997 📖 docs: eks docs updated in preparation for 0.6.1 release
  docs/book/src/topics/eks.md
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1991 Update to CAPI 0.3.10
  .golangci.yml
  clusterctl-settings.json
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/network/natgateways_test.go
  pkg/cloud/services/network/vpc_test.go
  test/e2e/aws_test.go
  test/e2e/conformance_test.go
  test/e2e/data/ci-artifacts-platform-kustomization.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/kubetest/kustomization/cluster-resource-set-label.yaml
  test/e2e/data/kubetest/kustomization/cluster-resource-set.yaml
  test/e2e/data/kubetest/kustomization/kustomization.yaml
  test/e2e/data/kubetest/kustomization/kustomizeversions.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/kubetest/common.go
  test/e2e/kubetest/setup.go
  test/e2e/kubetest/test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1916 ✨ AWSManagedMachinePool (EKS managed nodegroup) support
  cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/zz_generated.deepcopy.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/managed_nodegroup.go
  cmd/clusterawsadm/cloudformation/bootstrap/template.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook.go
  exp/api/v1alpha3/awsmanagedmachinepool_types.go
  exp/api/v1alpha3/awsmanagedmachinepool_webhook.go
  exp/api/v1alpha3/conditions_consts.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  exp/controllers/awsmanagedmachinepool_controller.go
  main.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/eks.go
  pkg/cloud/services/eks/errors.go
  pkg/cloud/services/eks/iam/iam.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/roles.go
  pkg/cloud/services/eks/service.go
  pkg/cloud/services/eks/tags.go
  pkg/cloud/services/eks/tags_test.go
  pkg/eks/eks.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1995 ✨ feat: enable additional user & role mapping for aws-iam-authenticator
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1alpha3/types.go
  controlplane/eks/api/v1alpha3/validate.go
  controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/iamauth/configmap.go
  pkg/cloud/services/iamauth/configmap_test.go
  pkg/cloud/services/iamauth/crd.go
  pkg/cloud/services/iamauth/crd_test.go
  pkg/cloud/services/iamauth/errors.go
  pkg/cloud/services/iamauth/iamauth.go
  pkg/cloud/services/iamauth/reconcile.go
  pkg/cloud/services/iamauth/service.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2002 .dockerignore: Add cmd package
  .dockerignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2007 🐛 Fix AWSMachinePool panic when MixedInstancesPolicy is not set
  exp/api/v1alpha3/types.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2012 🌱 Remove the integration test
  Makefile
  scripts/ci-integration.sh
  test/integration/integration_suite_test.go
  test/integration/metacluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2010 add io2 as valid ebs volume type
  exp/api/v1alpha3/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2014 🐛 Fix AWSManagedMachinePool NPE with scalingConfig
  pkg/cloud/services/eks/nodegroup.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2017 📖 docs: fix a broken link to prerequisites
  docs/book/src/topics/eks.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2028 📖 Fix link to docs site and move to top of repo README
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#2000 🌱 Add comments for VersionNumber field in AWSLaunchTemplate
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1alpha3/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2006 ✨ Add support for DefaultCooldown to AWSMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/webhook/manifests.yaml
  exp/api/v1alpha3/awsmachinepool_types.go
  exp/api/v1alpha3/awsmachinepool_webhook.go
  exp/api/v1alpha3/types.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  main.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2024 🌱 Add AWSManagedMachinePool flavor
  templates/cluster-template-eks-managedmachinepool.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1863 📖 AWSMachinePools docs and flavor
  docs/machinepools.md
  templates/cluster-template-machinepool.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1978 Validation around fields that are passed in as AWS API parameters
  api/v1alpha3/awscluster_webhook.go
  api/v1alpha3/awscluster_webhook_test.go
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachine_webhook_test.go
  api/v1alpha3/webhooks.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2005 🌱 Fix volume description to remove 'root' since it's also used for non-root volume
  api/v1alpha3/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2015 ✨ Add machine name tag to instance during creation
  api/v1alpha3/tags.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2021 ✨ Add tagging for AWSMachinePool resources
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_tags.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2013 🌱 Improve AWSManagedMachinePool remote access support
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1alpha3/awsmanagedmachinepool_types.go
  pkg/cloud/services/eks/nodegroup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2038 :docs: fix typos in eks commands
  docs/book/src/topics/eks.md
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2011 🌱 Validate subnet's az with failure domain when subnet id is passed
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2049 🐛fix: add more condition for resource's status filtering
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2018 :seedling: docs: Provide AMI IDs for rebuilt Ubuntu amis and fix e2e conformance with CI Artifacts jobs
  docs/amis.md
  test/e2e/conformance_test.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2068 🌱 Updated Bastion node's AMI. Changed the OS version to Ubuntu 20.04 from Ubuntu 16.04
  pkg/cloud/services/ec2/ami.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2044 📖 docs: eks docs update for managed machine pools
  docs/book/src/topics/machinepools.md
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2046 🐛fix: ensure env var enables AWSMachinePool webhooks
  config/manager/manager.yaml
  config/webhook/manager_webhook_patch.yaml
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2074 Fix roundtrip conversions between v1alpha2 and v1alpha3
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/awsmachinetemplate_conversion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2043 🐛 fix: add required iam permission for managed node groups
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/managed_control_plane.go
  cmd/clusterawsadm/cloudformation/bootstrap/template.go
  pkg/cloud/services/eks/nodegroup.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2071 🐛Make the regex less restrictive to allow underscore etc. for ssh key file name
  api/v1alpha3/awsmachine_webhook_test.go
  api/v1alpha3/webhooks.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#2051 🐛 Add fallback if subnets not provided on AWSMachinePool
  pkg/cloud/services/autoscaling/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#2080 📖 docs: add ADR template and first ADR
  docs/adr/0000-template.md
  docs/adr/0001-use-adrs-for-decisions.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#2082 🐛 Updates AWSMachine CloudInit defaulting logic
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachine_webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
