Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2021-07, with the labels that each got.

#2558 master to main cleanup
  docs/book/src/development/releasing.md
Labels: approved, cncf-cla: yes, lgtm, needs-priority, ok-to-test, release-note-none, size/XS

#2559 add 64 length for awsmanagedmachinepool iam role
  exp/api/v1alpha4/awsmanagedmachinepool_webhook.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, ok-to-test, release-note-none, size/XS

#2560 [Backport] Do not delete overridden security groups
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, size/M

#2562 Makefile fix for pr blocking e2e test
  Makefile
  test/e2e/shared/resource.go
  test/e2e/shared/suite.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, size/L

#2565 Modify clusterctl config to clusterctl generate
  docs/book/src/topics/accessing-ec2-instances.md
  docs/book/src/topics/eks/addons.md
  docs/book/src/topics/eks/creating-a-cluster.md
  docs/book/src/topics/machinepools.md
  test/e2e/shared/cluster.go
  test/e2e/shared/temp.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, ok-to-test, release-note-none, size/S

#2555 Do not delete overriden security groups
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, size/L

#2505 Update EKS clusters to enable encryption
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_webhook_test.go
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/cluster_test.go
  pkg/internal/cmp/slice.go
  pkg/internal/cmp/slice_test.go
  tilt-provider.json
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-action-required, size/L

#2573 July 2021 Dependency Updates
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
Labels: approved, cncf-cla: yes, lgtm, priority/backlog, release-note-none, size/L

#2576 fix: ensure updates to subnet are persisted to the scope
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/subnets.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, size/S

#2572 Major E2E Cleanup
  Makefile
  common.mk
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/aws.go
  test/e2e/shared/common.go
  test/e2e/shared/context.go
  test/e2e/shared/defaults.go
  test/e2e/shared/exec.go
  test/e2e/shared/resource.go
  test/e2e/shared/suite.go
  test/e2e/shared/template.go
  test/e2e/suites/conformance/conformance_suite_test.go
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/managed/addon_helpers.go
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/control_plane.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/helpers.go
  test/e2e/suites/managed/helpers_test.go
  test/e2e/suites/managed/machine_deployment.go
  test/e2e/suites/managed/machine_pool.go
  test/e2e/suites/managed/managed_suite_test.go
  test/e2e/suites/managed/upgrade_test.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
  test/e2e/suites/unmanaged/unmanaged_suite_test.go
  test/e2e/suites/unmanaged/unmanaged_test.go
  versions.mk
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, size/XXL

#2583 e2e: Pull in newer Cluster API for conformance fixes
  Makefile
  go.mod
  go.sum
  test/e2e/data/kubetest/conformance.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, release-note-none, size/M

#2587 Cleanup ReconcileVPC() and set id early in reconciliation.
  api/v1alpha4/awscluster_webhook.go
  api/v1alpha4/awscluster_webhook_test.go
  pkg/cloud/services/network/network.go
  pkg/cloud/services/network/vpc.go
  pkg/cloud/services/network/vpc_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, size/L

#2579 fix: reconcile Secret when userdata changes
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  bootstrap/eks/controllers/suite_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, size/L

#2549 Enabled GPU optimised AMIs for EKS
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/awsmachine_types.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/conversion_test.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/types.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, size/L

#2589 Automated cherry pick of #2587: Cleanup ReconcileVPC() and set id early in reconciliation.
  api/v1alpha3/awscluster_webhook.go
  api/v1alpha3/awscluster_webhook_test.go
  pkg/cloud/services/network/network.go
  pkg/cloud/services/network/vpc.go
  pkg/cloud/services/network/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/L

#2594 0.6 Release July 2021 Dependency Update
  .golangci.yml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, size/XXL

#2585 add AWSClusterTemplate type
  Makefile
  PROJECT
  api/v1alpha4/awscluster_webhook.go
  api/v1alpha4/awsclustertemplate_types.go
  api/v1alpha4/awsclustertemplate_webhook.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_awsclustertemplates.yaml
  config/crd/patches/webhook_in_awsclustertemplates.yaml
  config/rbac/awsclustertemplate_editor_role.yaml
  config/rbac/awsclustertemplate_viewer_role.yaml
  config/webhook/manifests.yaml
  main.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/feature, lgtm, priority/important-soon, release-note, size/XL

#2596 eksconfig reconciler tests: Remove race conditions
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  bootstrap/eks/controllers/eksconfig_controller_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/critical-urgent, release-note-none, size/L

#2556 Changed Volume encypted to pointer for v1alpha4
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/zz_generated.deepcopy.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/launchtemplate.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-soon, release-note, size/L

#2571 Renaming spec.networkSpec to spec.network
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/awscluster_types.go
  api/v1alpha4/awscluster_webhook.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  controllers/awsmachine_controller.go
  controlplane/eks/api/v1alpha3/conversion.go
  controlplane/eks/api/v1alpha3/zz_generated.conversion.go
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  docs/book/src/topics/consuming-existing-aws-infrastructure.md
  docs/book/src/topics/multi-az-control-planes.md
  exp/api/v1alpha4/awsmanagedcluster_types.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/ec2.go
  pkg/cloud/scope/elb.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/network/service.go
  pkg/cloud/services/securitygroup/service.go
  test/e2e/data/infrastructure-aws/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-aws/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-aws/cluster-template-limit-az.yaml
  test/e2e/data/infrastructure-aws/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-aws/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-aws/cluster-template-multi-az.yaml
  test/e2e/data/infrastructure-aws/cluster-template-nested-multitenancy.yaml
  test/e2e/data/infrastructure-aws/cluster-template-simple-multitenancy.yaml
  test/e2e/data/infrastructure-aws/limit-az/patches/limit-az.yaml
  test/e2e/data/infrastructure-aws/machine-pool/patches/limit-az.yaml
  test/e2e/data/infrastructure-aws/multi-az/patches/multi-az.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, priority/important-soon, release-note, size/L

#2599 eksconfig_controller_reconciler_test: Eventually test for updated secret
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, priority/important-soon, release-note-none, size/XS

#2603 Add webhook health check
  controlplane/eks/main.go
  go.mod
  go.sum
  main.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note-none, size/S

#2605 Makefile release fixes
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note-none, size/XS

#2600 Parallelise NAT gateway deletion
  pkg/cloud/services/network/natgateways.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-longterm, release-note, size/S

#2377 bug: make sure that controllers run on controll plane nodes
  bootstrap/eks/config/manager/manager.yaml
  config/manager/manager.yaml
  controlplane/eks/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-action-required, size/M

#2620 🐛 Managed SecurityGroups should be filtered correctly
  go.mod
  go.sum
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note, size/L

#2601 Finalizers added after first read operation on AWS in AWSMachines
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, size/M

#2623 [Backport] Makefile release fixes
  Makefile
Labels: approved, cncf-cla: yes, lgtm, needs-priority, release-note-none, size/XS

#2625 fix: node affinity definitions incorrect
  bootstrap/eks/config/manager/manager.yaml
Labels: approved, area/release, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note-none, size/XS

#2628 fix: changed the node affinity for the manager deployments
  config/manager/manager.yaml
  controlplane/eks/config/manager/manager.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, size/S

#2629 Remove webhook health check
  controlplane/eks/main.go
  main.go
Labels: approved, cncf-cla: yes, lgtm, needs-priority, release-note-none, size/S

#2630 Release note creation should be based on 0.6 branch
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, size/XS
