Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2021-09, with the labels that each got.

#2724 fix: add the doc for using external CCM with CSI driver to summary_prefix.md
  docs/book/src/SUMMARY_PREFIX.md
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#2731 fix: doc formatting
  docs/book/src/topics/external-cloud-provider-with-ebs-csi-driver.md
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#2742 Fix the broken link in the doc
  docs/book/src/development/development.md
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#2728 Fix findSubnet function's logic when subnet ID is specified
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#2745 Fix the gomega errors in tests with the controller runtime version bump
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  bootstrap/eks/controllers/eksconfig_controller_test.go
  go.mod
  go.sum
Labels: kind/bug, size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#2735 Use same golang version everywhere
  Dockerfile
  Makefile
  versions.mk
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-priority

#2715 Add AWS cloud provider tags to pre-existing infrastructure
  api/v1alpha4/tags.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
  pkg/cloud/tags/tags.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, ok-to-test, area/networking

#2756 docs: update to contributing to reference developer guide in book
  CONTRIBUTING.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/S, needs-priority

#2768 :bug: Rename the ELB scheme from Internet-facing to internet-facing
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/types.go
  api/v1alpha4/awscluster_types.go
  api/v1alpha4/awscluster_webhook.go
  api/v1alpha4/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#2765 Cleanup for failing periodic e2e capi tests
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
  test/e2e/suites/unmanaged/unmanaged_test.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, kind/cleanup, needs-priority

#2766 Fix the timeout for conformance test due to prolonged log collection
  test/e2e/shared/common.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, needs-priority

#2770 Add v1alpha3 to v1alpha4 upgrade e2e test
  test/e2e/data/e2e_conf.yaml
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, kind/regression, needs-priority

#2777 Fix timeout due to delay in bringing up control plane in e2e tests
  test/e2e/data/e2e_conf.yaml
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/flake, kind/regression, needs-priority

#2786 docs: mv wg-k8s-infra sig-k8s-infra
  docs/book/src/development/releasing.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, kind/cleanup, needs-priority

#2776 :bug: fix typo in AWSCluster validation hook error
  api/v1alpha4/awsclustertemplate_webhook.go
Labels: kind/bug, cncf-cla: yes, size/XS, release-note, needs-priority

#2772 Make PublicIP field in AWSMachine Spec work
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#2740 Validation added for empty instanceType in AWSMachine and AWSMachineTemplate
  api/v1alpha4/awsmachine_types.go
  api/v1alpha4/awsmachine_webhook_test.go
  api/v1alpha4/awsmachinetemplate_webhook_test.go
  api/v1alpha4/sshkeyname_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  exp/instancestate/awsinstancestate_controller_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#2789 chore: Remove unnecessary conversion code
  api/v1alpha3/conversion.go
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-priority

#2796 Download the e2e restart scripts outside the dockerfile
  Dockerfile
  Makefile
  hack/tools/Makefile
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, needs-priority

#2806 Update tilt-provider.json to add CAPA label in Tilt
  tilt-provider.json
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#2809 Ensure destination pointer is non-nil before calling restore functions
  api/v1alpha3/conversion.go
  exp/api/v1alpha3/conversion.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#2800 Update manager_iam_patch.yaml
  config/default/manager_iam_patch.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#2659 bug: Add bastion-sg to managedMachinePool remoteAccess source-sgs when bastion is enabled
  pkg/cloud/services/eks/nodegroup.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, priority/important-soon, size/XS, ok-to-test, area/networking

#2810 bug: If one type of webhook is not defined, testenv.Build hits a nil dereference
  test/helpers/envtest.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, priority/important-soon, size/S, area/testing, needs-triage

#2811 Move generation of CRD docs to the repo to speed up Netlify
  Makefile
  docs/book/src/.gitignore
  docs/book/src/crd/index.md
Labels: release-note-none, size/XXL, approved, cncf-cla: yes, kind/documentation, lgtm, priority/important-soon, area/release, triage/accepted
