Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2021-06, with the labels that each got.

#2440 Bump to CAPI v0.3.17
  docs/book/gen-crd-api-reference-docs/config.json
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#2439 Update developer section in the book
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/SUMMARY_SUFFIX.md
  docs/book/src/development/development.md
  docs/book/src/development/tilt-setup.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#2425 Only read AWSClusterStaticIdentity secrets from controller namespace
  api/v1alpha3/conversion.go
  api/v1alpha3/conversion_test.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/awsidentity_types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  go.mod
  pkg/cloud/scope/session.go
  pkg/cloud/scope/session_test.go
  util/system/util.go
  util/system/util_test.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note-action-required, size/L

#2451 Reword wrong webhook usage
  main.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#2437 fix: Process extra statements for Cluster API Controllers
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/template.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/M

#2461 Minor makefile release fixes
  Makefile
  docs/book/src/development/releasing.md
  hack/tools/Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#2344 Use Kustomize to generate test templates
  Makefile
  hack/gen-test-flavors.sh
  test/e2e/data/infrastructure-aws/README.md
  test/e2e/data/infrastructure-aws/addons/cni/cluster-resource-set-cni.yaml
  test/e2e/data/infrastructure-aws/base/cluster-template.yaml
  test/e2e/data/infrastructure-aws/base/kustomization.yaml
  test/e2e/data/infrastructure-aws/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-aws/cluster-template-limit-az.yaml
  test/e2e/data/infrastructure-aws/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-aws/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-aws/cluster-template-multi-az.yaml
  test/e2e/data/infrastructure-aws/cluster-template-nested-multitenancy.yaml
  test/e2e/data/infrastructure-aws/cluster-template-simple-multitenancy.yaml
  test/e2e/data/infrastructure-aws/cluster-template-spot-instances.yaml
  test/e2e/data/infrastructure-aws/cluster-template-ssm.yaml
  test/e2e/data/infrastructure-aws/cluster-template-upgrade-to-main.yaml
  test/e2e/data/infrastructure-aws/cluster-template.yaml
  test/e2e/data/infrastructure-aws/default/kustomization.yaml
  test/e2e/data/infrastructure-aws/default/machine-deployment.yaml
  test/e2e/data/infrastructure-aws/default/patches/cluster-resource-set-cni.yaml
  test/e2e/data/infrastructure-aws/kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-aws/kcp-remediation/mhc.yaml
  test/e2e/data/infrastructure-aws/limit-az/kustomization.yaml
  test/e2e/data/infrastructure-aws/limit-az/patches/limit-az.yaml
  test/e2e/data/infrastructure-aws/machine-pool/kustomization.yaml
  test/e2e/data/infrastructure-aws/machine-pool/machine-pool.yaml
  test/e2e/data/infrastructure-aws/machine-pool/patches/limit-az.yaml
  test/e2e/data/infrastructure-aws/md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-aws/md-remediation/mhc.yaml
  test/e2e/data/infrastructure-aws/md-remediation/patches/mhc-label.yaml
  test/e2e/data/infrastructure-aws/multi-az/kustomization.yaml
  test/e2e/data/infrastructure-aws/multi-az/patches/multi-az.yaml
  test/e2e/data/infrastructure-aws/nested-multitenancy/kustomization.yaml
  test/e2e/data/infrastructure-aws/nested-multitenancy/patches/role-identity.yaml
  test/e2e/data/infrastructure-aws/nested-multitenancy/role.yaml
  test/e2e/data/infrastructure-aws/patches/cluster-cni.yaml
  test/e2e/data/infrastructure-aws/simple-multitenancy/kustomization.yaml
  test/e2e/data/infrastructure-aws/simple-multitenancy/patches/role-identity.yaml
  test/e2e/data/infrastructure-aws/simple-multitenancy/role.yaml
  test/e2e/data/infrastructure-aws/spot-instances/kustomization.yaml
  test/e2e/data/infrastructure-aws/spot-instances/patches/spot-instances.yaml
  test/e2e/data/infrastructure-aws/ssm/kustomization.yaml
  test/e2e/data/infrastructure-aws/ssm/patches/ssm.yaml
  test/e2e/data/infrastructure-aws/upgrade-to-main/kustomization.yaml
  test/e2e/data/infrastructure-aws/upgrade-to-main/machinetemplates.yaml
  test/e2e/suites/unmanaged/unmanaged_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XXL

#2418 Refactor tests to plain go
  bootstrap/eks/api/v1alpha3/webhook_suite_test.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  bootstrap/eks/controllers/suite_test.go
  controllers/awscluster_controller_test.go
  controllers/awsmachine_controller_test.go
  controllers/suite_test.go
  controlplane/eks/api/v1alpha3/webhook_suite_test.go
  controlplane/eks/api/v1alpha4/suite_test.go
  controlplane/eks/controllers/suite_test.go
  exp/controlleridentitycreator/awscontrolleridentity_controller_test.go
  exp/controlleridentitycreator/suite_test.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/suite_test.go
  exp/instancestate/awsinstancestate_controller_test.go
  exp/instancestate/helpers_test.go
  exp/instancestate/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XXL

#2445 fix typo in awsfargateprofile webhook
  config/webhook/manifests.yaml
  exp/api/v1alpha4/awsfargateprofile_webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#2405 feat: add support for taints for managed machine pools
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/awsmanagedmachinepool_types.go
  exp/api/v1alpha4/types.go
  exp/api/v1alpha4/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/cloud/converters/eks.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/eventbridgeiface_mock.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#2458 Copy envtest cleanup from core cluster-api repo
  test/helpers/envtest.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#2460 [docs] Minor introduction section improvements
  README.md
  docs/book/src/development/tilt-setup.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#2450 feat: add support for taints for managed machine pools (backport)
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1alpha3/awsmanagedmachinepool_types.go
  exp/api/v1alpha3/types.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/cloud/converters/eks.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/eventbridgeiface_mock.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#2431 ISSUE-2414: Add additional linters
  .golangci.yml
  cmd/clusterawsadm/cmd/ami/copy/common.go
  pkg/cloud/services/secretsmanager/secret_fetch_script.go
  pkg/cloud/services/ssm/secret_fetch_script.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#2446 backport awsfargateprofile validate webhook typo fix to release-0.6
  config/webhook/manifests.yaml
  exp/api/v1alpha3/awsfargateprofile_webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#2470 Add dependabot configuration
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#2469 Update calico in e2e tests
  test/e2e/data/cni/calico.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XXL

#2485 Bump dependencies for June 2021 except gomock
  Makefile
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
  pkg/cloud/services/elb/mock_elbiface/elbapi_mock.go
  pkg/cloud/services/elb/mock_resourcegroupstaggingapiiface/resourcegroupstaggingapiiface_mock.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/eventbridgeiface_mock.go
  pkg/cloud/services/instancestate/mock_sqsiface/sqsiface_mock.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/mock_services/secretsmanager_machine_interface_mock.go
  pkg/cloud/services/sts/mock_stsiface/stsiface_mock.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XXL

#2486 Update dependencies for June 2021 for v1alpha3
  .golangci.yml
  Makefile
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
  pkg/cloud/services/elb/mock_elbiface/elbapi_mock.go
  pkg/cloud/services/elb/mock_resourcegroupstaggingapiiface/resourcegroupstaggingapiiface_mock.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/eventbridgeiface_mock.go
  pkg/cloud/services/instancestate/mock_sqsiface/sqsiface_mock.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/mock_services/secretsmanager_machine_interface_mock.go
  pkg/cloud/services/sts/mock_stsiface/stsiface_mock.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XXL

#2500 fix: break down DescribeTags requests by 20 LoadBalancers at a time
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/M

#2512 [backport] fix: break down DescribeTags requests by 20 LoadBalancers at a time
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/M

#2510 ✨ Add shortnames to all resources
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/awsidentity_types.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/awsmachinetemplate_types.go
  api/v1alpha4/awscluster_types.go
  api/v1alpha4/awsidentity_types.go
  api/v1alpha4/awsmachine_types.go
  api/v1alpha4/awsmachinetemplate_types.go
  bootstrap/eks/api/v1alpha3/eksconfig_types.go
  bootstrap/eks/api/v1alpha3/eksconfigtemplate_types.go
  bootstrap/eks/api/v1alpha4/eksconfig_types.go
  bootstrap/eks/api/v1alpha4/eksconfigtemplate_types.go
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go
  exp/api/v1alpha3/awsfargateprofile_types.go
  exp/api/v1alpha3/awsmachinepool_types.go
  exp/api/v1alpha3/awsmanagedmachinepool_types.go
  exp/api/v1alpha4/awsfargateprofile_types.go
  exp/api/v1alpha4/awsmachinepool_types.go
  exp/api/v1alpha4/awsmanagedmachinepool_types.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/M

#2516 Dependabot: Add workflow to automatically update generated code
  .github/workflows/dependabot.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#2515 Add file and make commands for nightly build
  Makefile
  cloudbuild-nightly.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#2519 Fix dependabot Github action
  .github/workflows/dependabot.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, size/S

#2511 chore: rely on cluster deletion in eks e2e tests
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
  test/e2e/data/eks/cluster-template-eks-control-plane-only.yaml
  test/e2e/shared/common.go
  test/e2e/shared/identity.go
  test/e2e/shared/suite.go
  test/e2e/suites/managed/eks_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/L

#2495 fix: remove usage of slices of struct pointers
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha3/zz_generated.deepcopy.go
  api/v1alpha4/awsmachine_types.go
  api/v1alpha4/awsmachine_webhook_test.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha3/types.go
  controlplane/eks/api/v1alpha3/zz_generated.conversion.go
  controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_webhook_test.go
  controlplane/eks/api/v1alpha4/types.go
  controlplane/eks/api/v1alpha4/zz_generated.deepcopy.go
  docs/book/src/SUMMARY_SUFFIX.md
  docs/book/src/development/conventions.md
  exp/api/v1alpha3/awsmachinepool_types.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  exp/api/v1alpha4/awsmachinepool_types.go
  exp/api/v1alpha4/zz_generated.deepcopy.go
  pkg/cloud/converters/eks.go
  pkg/cloud/scope/fargate.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/scope/shared_test.go
  pkg/cloud/services/awsnode/subnets.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/eks/addons.go
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/cluster_test.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/network/natgateways_test.go
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/routetables_test.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#2509 CLI command added to list aws resources created by CAPA
  cmd/clusterawsadm/cmd/resource/list/list.go
  cmd/clusterawsadm/cmd/resource/resource.go
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterawsadm/resource/list.go
  cmd/clusterawsadm/resource/type.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#2520 Fix clusterctl metadata
  metadata.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, release-note-none, size/XS

#2521 dependabot: Update author of autocommit to pass CLA checks
  .github/workflows/dependabot.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, size/XS

#2522 README: Remove go-report
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-priority, release-note-none, size/XS

#2529 fix kubebuilder pointing to changed api-endpoint
  api/v1alpha3/awscluster_types.go
  api/v1alpha4/awscluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
Labels: approved, area/api, cncf-cla: yes, kind/bug, lgtm, priority/backlog, release-note, size/S

#2525 :bug: AWSMachinePool: Prune old Launch Template versions
  exp/controllers/awsmachinepool_controller.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-priority, priority/important-soon, release-note, size/M

#2463 Add root storage device tags through additionalTags in ec2 instance
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_tags.go
  controlplane/eks/api/v1alpha3/conversion.go
  controlplane/eks/api/v1alpha3/zz_generated.conversion.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XL

#2531 [backport] :bug: AWSMachinePool: Prune old Launch Template versions
  exp/controllers/awsmachinepool_controller.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, size/M

#2524 Added clusterctl move label to global identity resources
  api/v1alpha4/awsclustercontrolleridentity_webhook.go
  api/v1alpha4/awsclustercontrolleridentity_webhook_test.go
  api/v1alpha4/awsclusterroleidentity_webhook.go
  api/v1alpha4/awsclusterroleidentity_webhook_test.go
  api/v1alpha4/awsclusterstaticidentity_webhook.go
  api/v1alpha4/awsclusterstaticidentity_webhook_test.go
  api/v1alpha4/defaults.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, needs-priority, release-note, size/L

#2536 Bump core cluster-api to v0.3.19
  docs/book/gen-crd-api-reference-docs/config.json
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-priority, release-note-none, size/M

#2537 Update CAPI to v0.4.0-rc.0
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-priority, release-note-none, size/XL

#2532 Add KCP scale-in test
  Makefile
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-aws/kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-aws/kcp-scale-in/patches/kcp-surge.yaml
  test/e2e/shared/defaults.go
  test/e2e/shared/resource.go
  test/e2e/shared/suite.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
  test/e2e/suites/unmanaged/unmanaged_test.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, size/L

#2538 Allow setting ELB scheme when previously not set
  api/v1alpha4/awscluster_webhook.go
  api/v1alpha4/awscluster_webhook_test.go
  api/v1alpha4/types.go
Labels: approved, cncf-cla: yes, lgtm, needs-priority, release-note-none, size/M

#2541 upgrade to kind v0.11.0
  hack/ensure-kind.sh
Labels: approved, cncf-cla: yes, lgtm, needs-priority, ok-to-test, release-note-none, size/XS

#2542 README: Note that v1alpha3 (v0.6) supports Kubernetes v1.21
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, needs-priority, release-note-none, size/XS

#2544 Update Calico version to 3.19
  test/e2e/data/cni/calico.yaml
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, needs-priority, release-note-none, size/XXL

#2545 Upgrade to CAPI v0.4.0
  Makefile
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/resource.go
Labels: approved, cncf-cla: yes, lgtm, needs-priority, release-note-none, size/M

#2550 Kustomize patch added for move-hierarchy label
  config/crd/kustomization.yaml
  config/crd/patches/label_in_awsclustercontrolleridentities.yaml
  config/crd/patches/label_in_awsclusterroleidentities.yaml
  config/crd/patches/label_in_awsclusterstaticidentities.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/critical-urgent, release-note-none, size/M

#2553 Add initial Triage Party setup
  docs/triage-party/.dockerignore
  docs/triage-party/.gitignore
  docs/triage-party/Dockerfile
  docs/triage-party/README.md
  docs/triage-party/cdk.context.json
  docs/triage-party/cdk.json
  docs/triage-party/config/config.yaml
  docs/triage-party/go.mod
  docs/triage-party/go.sum
  docs/triage-party/triage-party-deployment.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, release-note-none, size/XL

#2551 Tagging elastic IPs on creation
  pkg/cloud/services/network/eips.go
  pkg/cloud/services/network/natgateways_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, needs-priority, ok-to-test, release-note, size/M

#2557 Add Linux and Darwin ARM64 builds of clusterawsadm
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, needs-priority, ok-to-test, release-note, size/XS
