Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2021-02, with the labels that each got.

#2037 ✨ Watches instance state changes and reconcile AWSMachine if necessary
  api/v1alpha2/awsmachine_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/zz_generated.deepcopy.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/zz_generated.deepcopy.go
  cmd/clusterawsadm/api/iam/v1alpha1/types.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/helpers.go
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
  exp/controllers/suite_test.go
  exp/instancestate/awsinstancestate_controller.go
  exp/instancestate/awsinstancestate_controller_test.go
  exp/instancestate/helpers_test.go
  exp/instancestate/suite_test.go
  feature/feature.go
  main.go
  pkg/cloud/endpoints/endpoints_test.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/global.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/instancestate/ec2events.go
  pkg/cloud/services/instancestate/helpers_test.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/doc.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/eventbridgeiface_mock.go
  pkg/cloud/services/instancestate/mock_sqsiface/doc.go
  pkg/cloud/services/instancestate/mock_sqsiface/sqsiface_mock.go
  pkg/cloud/services/instancestate/queue.go
  pkg/cloud/services/instancestate/queue_test.go
  pkg/cloud/services/instancestate/rule.go
  pkg/cloud/services/instancestate/rule_test.go
  pkg/cloud/services/instancestate/service.go
  pkg/cloud/services/secretsmanager/service_test.go
  pkg/cloud/services/ssm/service_test.go
  pkg/internal/bytes/bytes_test.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/suites/unmanaged/unmanaged_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2240 :bug: Make EventBridge non-critical to cluster reconciliation
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2234 📖 Added how to develop locally using Tilt for EKS Control Plane
  docs/book/src/SUMMARY.md
  docs/book/src/development/development.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2232 feat: updated PR template to include the release notes sand checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1933 ✨ Support overriding security groups in AWSCluster spec
  api/v1alpha2/awscluster_conversion.go
  api/v1alpha2/zz_generated.conversion.go
  api/v1alpha3/awscluster_types.go
  api/v1alpha3/types.go
  api/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  docs/book/src/topics/consuming-existing-aws-infrastructure.md
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  pkg/cloud/services/securitygroup/service.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2235 🐛 Fix bastion and AWSMachinePool connectivity
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2241 ✨ Add filters support for additional security groups
  api/v1alpha3/awsmachine_types.go
  api/v1alpha3/awsmachine_webhook.go
  api/v1alpha3/awsmachine_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_security_groups.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/L

#2243 🌱 AWSManagedMachinePool: Make public access to SSH explicit
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/api/v1alpha3/types.go
  exp/api/v1alpha3/awsmanagedmachinepool_types.go
  exp/api/v1alpha3/awsmanagedmachinepool_webhook.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/securitygroup.go
Labels: approved, cncf-cla: yes, lgtm, release-note-action-required, size/M

#2246 🐛 AWSManagedControlPlane: Add conditions for Updating/Creating
  controlplane/eks/api/v1alpha3/conditions_consts.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/cluster_test.go
  pkg/cloud/services/eks/mock.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
  pkg/cloud/services/eks/service.go
Labels: approved, area/provider/eks, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#2247 ✨feat: added release-notes automation
  Makefile
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  bootstrap/eks/config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  docs/book/src/development/imagepromo1.png
  docs/book/src/development/releasing.md
  hack/changelog.tpl
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#2249 🌱 Minor comment update
  api/v1alpha3/types.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, size/XS

#2250 📖 Add AWSFargatePool ADR
  docs/adr/0004-fargate-pools.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#2229 ✨ Add a log debug log configuration to the AWS clients
  pkg/cloud/logs/logs.go
  pkg/cloud/scope/clients.go
  pkg/cloud/services/autoscaling/service.go
  pkg/cloud/services/ec2/service.go
  pkg/cloud/services/eks/service.go
  pkg/cloud/services/elb/service.go
  pkg/cloud/services/iamauth/service.go
  pkg/cloud/services/network/service.go
  pkg/cloud/services/secretsmanager/service.go
  pkg/cloud/services/securitygroup/service.go
  pkg/cloud/services/ssm/service.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/L

#2261 🐛 Fix manager arg inconsistencies
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/webhook/manager_webhook_patch.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#2237 📖 Multitenancy: Restrict controller credential usage by creating a permission resource
  docs/proposal/20200506-single-controller-multitenancy-flow.plantuml
  docs/proposal/20200506-single-controller-multitenancy-flow.svg
  docs/proposal/20200506-single-controller-multitenancy.md
Labels: approved, cncf-cla: yes, kind/design, lgtm, size/L

#2252 Updated the PR template to include kind assignment
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#2260 🌱New AMIs for versions 1.20.4, 1.19.8, and 1.18.16
  README.md
  docs/amis.md
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/L

#2259 Replace awslog with logrWrapper
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#2269 Add AWSClusterControllerPrincipal controller to multitenancy proposal
  docs/proposal/20200506-single-controller-multitenancy.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#2262 🐛 hack: fix semver comparison in ensure-kind
  hack/ensure-kind.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
