Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2021-01, with the labels that each got.

#2175 🌱 feat: control plane deletion checks
  controlplane/eks/config/manager/manager_args_patch.yaml
  controlplane/eks/config/rbac/role.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  controlplane/eks/main.go
  pkg/cloud/services/eks/config.go
  pkg/cloud/services/iamauth/reconcile.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2183 🌱 fix: updated service account for leader election
  bootstrap/eks/config/rbac/leader_election_role_binding.yaml
  config/rbac/leader_election_role_binding.yaml
  controlplane/eks/config/rbac/leader_election_role_binding.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2190 New AMIs for Kubernetes versions 1.17.16, 1.18.14, 1.19.6, 1.20.1
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2112 ✨Add copy AMI command to clusterawsadm
  cmd/clusterawsadm/cmd/ami/ami.go
  cmd/clusterawsadm/cmd/ami/copy/copy.go
  cmd/clusterawsadm/cmd/root.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/launchtemplate.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2197 ✨ Add instances to AWSMachinePool status
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1alpha3/awsmachinepool_types.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  exp/controllers/awsmachinepool_controller.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2152 :warning: align flag names to upstream k8s
  bootstrap/eks/config/manager/manager.yaml
  bootstrap/eks/config/manager/manager_args_patch.yaml
  bootstrap/eks/config/webhook/manager_webhook_patch.yaml
  bootstrap/eks/main.go
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/webhook/manager_webhook_patch.yaml
  controlplane/eks/config/manager/manager.yaml
  controlplane/eks/config/manager/manager_args_patch.yaml
  controlplane/eks/config/webhook/manager_webhook_patch.yaml
  controlplane/eks/main.go
  main.go
  test/e2e/data/e2e_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2184 🐛 AWSMachinePool: Remove unused ID field on launch template spec
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1alpha3/types.go
  exp/controllers/awsmachinepool_controller.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2194 🐛Add UpdateAutoScalingGroup to controller IAM
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2101 Consolidating boskos scripts for CAPA
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate_test.py
  hack/boskos.py
  hack/checkin_account.py
  hack/checkout_account.py
  hack/heartbeat_account.py
  scripts/ci-conformance.sh
  scripts/ci-e2e-conformance.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2187 📖 docs: eks docs refactor and added eks console docs
  docs/book/src/SUMMARY.md
  docs/book/src/topics/eks.md
  docs/book/src/topics/eks/cluster-upgrades.md
  docs/book/src/topics/eks/creating-a-cluster.md
  docs/book/src/topics/eks/eks-console.md
  docs/book/src/topics/eks/enabling.md
  docs/book/src/topics/eks/index.md
  docs/book/src/topics/eks/prerequisites.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#2188 🐛 test: investigate and fix eks e2e tests
  Makefile
  controlplane/eks/config/manager/manager_args_patch.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/aws.go
  test/e2e/shared/suite.go
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2199 🐛 fix: updated the eks e2e script with latest boskos changes
  scripts/ci-e2e-eks.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2198 Upgrade to CAPI v0.3.12
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#2204 🌱Upgrade AWS SDK version to 1.36.26
  go.mod
  go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/eks/mock_eksiface/eksapi_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2203 🌱 Add encrypted AMI copy
  cmd/clusterawsadm/cmd/ami/ami.go
  cmd/clusterawsadm/cmd/ami/copy/copy.go
  cmd/clusterawsadm/cmd/ami/copy/encryptedcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2193 🐛Trigger rolling replacement upon launch template change
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1alpha3/awsmachinepool_types.go
  exp/api/v1alpha3/conditions_consts.go
  exp/api/v1alpha3/zz_generated.deepcopy.go
  exp/controllers/awsmachinepool_controller.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2206 🌱 New AMIs for Kubernetes versions 1.20.2, 1.19.6, 1.18.15, 1.17.17
  docs/amis.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2211 🌱 skip EKS upgrade tests when running e2e
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2070 ✨ Add IRSA to EKS workload clusters
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/eks.go
  pkg/cloud/services/eks/iam/iam.go
  pkg/cloud/services/eks/oidc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#2201 ✨ Add fine-grained service rate limiters
  go.sum
  pkg/cloud/interfaces.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/externalinfracluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/scope/session.go
  pkg/cloud/throttle/throttle.go
  pkg/internal/rate/rate.go
  pkg/internal/rate/reset.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2086 ✨ Secondary cidr support for EKS workload clusters
  api/v1alpha3/conditions_consts.go
  api/v1alpha3/tags.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook_test.go
  controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  go.mod
  go.sum
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/awsnode/cni.go
  pkg/cloud/services/awsnode/errors.go
  pkg/cloud/services/awsnode/service.go
  pkg/cloud/services/awsnode/subnets.go
  pkg/cloud/services/network/network.go
  pkg/cloud/services/network/secondarycidr.go
  pkg/cloud/services/network/service.go
  pkg/cloud/services/network/subnets.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#2096 Refactor release process for Github and Staging
  Dockerfile
  Dockerfile.fastbuild
  Makefile
  common.mk
  docs/book/src/development/releasing.md
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/image-patch/kustomization.yaml
  hack/image-patch/pull-policy-patch.yaml
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  versions.mk
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2213 Bump GCB Docker image for cloudbuild
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2214 Ensure mirrored OCI images are pulled before building Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#2215 Bump dockerfile-experimental version
  Dockerfile
  hack/boilerplate/boilerplate.Dockerfile.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2216 Fixups to Docker build
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#2217 Disable cgo for building kustomize without gcc
  hack/tools/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2057 ✨ Support custom AMI lookup with EKS
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/launchtemplate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#2220 :bug: Ensure EKS controllers are preloaded in e2e
  test/e2e/data/e2e_eks_conf.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2202 ✨ feat: add EKS addon support
  Makefile
  bootstrap/eks/config/manager/manager_image_patch.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cmd/eks/addons/addons.go
  cmd/clusterawsadm/cmd/eks/addons/list_available.go
  cmd/clusterawsadm/cmd/eks/addons/list_installed.go
  cmd/clusterawsadm/cmd/eks/addons/types.go
  cmd/clusterawsadm/cmd/eks/eks.go
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterawsadm/printers/printers.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_webhook_test.go
  controlplane/eks/api/v1alpha3/conditions_consts.go
  controlplane/eks/api/v1alpha3/types.go
  controlplane/eks/api/v1alpha3/zz_generated.deepcopy.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/config/manager/manager_image_patch.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  docs/book/src/SUMMARY.md
  docs/book/src/development/releasing.md
  docs/book/src/topics/eks/addons.md
  docs/book/src/topics/eks/index.md
  go.mod
  go.sum
  pkg/cloud/converters/eks.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/eks/addons.go
  pkg/cloud/services/eks/eks.go
  pkg/eks/addons/plan.go
  pkg/eks/addons/plan_test.go
  pkg/eks/addons/procedures.go
  pkg/eks/addons/types.go
  pkg/planner/planner.go
  templates/cluster-template-eks-managedmachinepool-vpccni.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
  test/e2e/suites/managed/addon.go
  test/e2e/suites/managed/addon_helpers.go
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2221 Revert "Add externalInfraCluster"
  controllers/awsmachine_controller.go
  pkg/cloud/scope/externalinfracluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2138 🌱Add CAPI E2E tests
  Makefile
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-aws/cluster-template-mhc.yaml
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
  test/e2e/suites/unmanaged/unmanaged_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#2228 controllers: Add conditionals around fetching secret backend service
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#2230 Update mdbook to 0.4.5 to fix CVE-2020-26297
  versions.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#2223 📖 Minor update on release process doc
  docs/book/src/development/releasing.md
  hack/tools/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/M
