Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2021-08, with the labels that each got.

#2468 :sparkles: Add ebs volume throughput field to v1alpha4 Volume
  api/v1alpha3/conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/awsmachine_webhook.go
  api/v1alpha4/awsmachine_webhook_test.go
  api/v1alpha4/awsmachinetemplate_webhook.go
  api/v1alpha4/types.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  exp/api/v1alpha4/awsmachinepool_webhook.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/launchtemplate.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test

#2422 support for oidc identity provider
  controlplane/eks/api/v1alpha3/conversion.go
  controlplane/eks/api/v1alpha3/zz_generated.conversion.go
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha4/conditions_consts.go
  controlplane/eks/api/v1alpha4/types.go
  controlplane/eks/api/v1alpha4/zz_generated.deepcopy.go
  controlplane/eks/config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  pkg/cloud/converters/eks.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/eks/eks.go
  pkg/cloud/services/eks/identity_provider.go
  pkg/eks/identityprovider/plan.go
  pkg/eks/identityprovider/plan_test.go
  pkg/eks/identityprovider/procedures.go
  pkg/eks/identityprovider/types.go
  pkg/eks/identityprovider/types_test.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test

#2671 August 2021 Dependency Updates
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/shared/v1alpha4_provider/metadata.yaml
  versions.mk
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, priority/important-soon, area/release

#2673 Add log-level customization for artifact logs in E2E runs
  config/manager/manager.yaml
Labels: kind/feature, approved, cncf-cla: yes, priority/backlog, lgtm, size/XS, release-note

#2677 metadata.yaml: Correct version
  metadata.yaml
Labels: release-note-none, approved, cncf-cla: yes, lgtm, priority/important-soon, size/XS, kind/cleanup

#2678 Retry fetching managed vpc attributes when vpc is 'NotFound'
  pkg/cloud/services/network/vpc.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, priority/important-soon, size/XS, release-note, ok-to-test

#2663 fix broken link in docs
  docs/book/src/development/tilt-setup.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-priority

#2692 Remove elasticloadbalancing:AddTags duplicate entries.
  cmd/clusterawsadm/cloudformation/bootstrap/cloud_provider_integration_control_plane.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority

#2682 netlify: Attempt to resolve build speed issues
  docs/book/Makefile
  docs/book/gen-crd-api-reference-docs/config.json
  docs/book/src/SUMMARY_SUFFIX.md
Labels: priority/critical-urgent, release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#2700 Update README
  README.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-priority

#2662 Separate EKS-related IAM resources
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/iam.go
  cmd/clusterawsadm/cloudformation/bootstrap/template.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, adr-required, needs-priority

#2676 Fargate profile tags
  exp/api/v1alpha4/awsfargateprofile_webhook.go
  pkg/cloud/services/eks/fargate.go
  pkg/cloud/services/eks/tags.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, ok-to-test

#2702 Support spot capacity type for ManagedMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/awsmanagedmachinepool_types.go
  exp/api/v1alpha4/awsmanagedmachinepool_webhook.go
  exp/api/v1alpha4/zz_generated.deepcopy.go
  pkg/cloud/converters/eks.go
  pkg/cloud/services/eks/nodegroup.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, ok-to-test, area/api

#2709 fix: missing identity permission for the managed control plane
  controlplane/eks/config/rbac/role.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
Labels: kind/bug, priority/critical-urgent, approved, cncf-cla: yes, lgtm, size/XS, release-note, area/security

#2685 Wait for webhook readiness and healthy
  main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#2720 Finalise removal of kube-rbac-proxy
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  main.go
Labels: size/M, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, ok-to-test, area/security

#2705 [cloud/network] Fix panic on RouteTables reconcile.
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/routetables_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, ok-to-test, area/networking

#2722 fix: node affinity rules in external CCM CRDs
  test/e2e/data/infrastructure-aws/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-aws/external-cloud-provider/aws-ccm-external.yaml
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, priority/important-soon, size/S, area/testing

#2723 fix: node affinity rules indentation in external CCM CRDs
  test/e2e/data/infrastructure-aws/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-aws/external-cloud-provider/aws-ccm-external.yaml
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#2718 Add doc for using external cloud provider with CSI driver
  docs/book/src/topics/external-cloud-provider-with-ebs-csi-driver.md
Labels: size/L, approved, cncf-cla: yes, kind/documentation, lgtm, priority/important-soon, release-note
