Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2021-04, with the labels that each got.

#2328 Add ApplySecurityGroupsToLoadBalancer action to controllers role
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_enable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#2338 Fix netlify builds
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#2341 Allow custom bootstrapper user name
  cmd/clusterawsadm/api/bootstrap/v1alpha1/defaults.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#2342 Publish generated IAM permissions and clusterawsadm documentation
  Makefile
  docs/book/Makefile
  docs/book/cmd/clusterawsadmdocs/main.go
  docs/book/src/.gitignore
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/SUMMARY_SUFFIX.md
  docs/book/src/clusterawsadm/commands/ami.md
  docs/book/src/clusterawsadm/commands/bootstrap.md
  docs/book/src/clusterawsadm/commands/commands.md
  docs/book/src/clusterawsadm/commands/eks.md
  docs/book/src/clusterawsadm/overview.md
  docs/book/src/topics/iam-permissions.md
  go.sum
  hack/eks-clusterawsadm-config.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#2304 Add list AMIs command to clusterawsadm
  cmd/clusterawsadm/cmd/ami/ami.go
  cmd/clusterawsadm/cmd/ami/list/helper.go
  cmd/clusterawsadm/cmd/ami/list/list.go
  cmd/clusterawsadm/printers/printers.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/instances_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#2343 Move myself to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#2348 :bug: Refer to `sshKeyName` field in error
  api/v1alpha3/validate.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/bug, lgtm, release-note, size/S

#2349 Fix machinepool template links
  docs/book/src/topics/machinepools.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS

#2347 Add CRD reference docs
  Makefile
  api/v1alpha3/doc.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/doc.go
  cmd/clusterawsadm/api/iam/v1alpha1/doc.go
  docs/book/Makefile
  docs/book/cmd/clusterawsadmdocs/main.go
  docs/book/gen-crd-api-reference-docs/config.json
  docs/book/gen-crd-api-reference-docs/template/members.tpl
  docs/book/gen-crd-api-reference-docs/template/pkg.tpl
  docs/book/gen-crd-api-reference-docs/template/type.tpl
  docs/book/src/.gitignore
  docs/book/src/SUMMARY_SUFFIX.md
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#2345 Refactor AMI commands and publish AMIs in book
  cmd/clusterawsadm/ami/copy.go
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/ami/list.go
  cmd/clusterawsadm/api/ami/v1alpha1/doc.go
  cmd/clusterawsadm/api/ami/v1alpha1/register.go
  cmd/clusterawsadm/api/ami/v1alpha1/scheme/scheme.go
  cmd/clusterawsadm/api/ami/v1alpha1/types.go
  cmd/clusterawsadm/api/ami/v1alpha1/zz_generated.deepcopy.go
  cmd/clusterawsadm/api/ami/v1alpha1/zz_generated.defaults.go
  cmd/clusterawsadm/cmd/ami/copy/common.go
  cmd/clusterawsadm/cmd/ami/copy/copy.go
  cmd/clusterawsadm/cmd/ami/copy/encryptedcopy.go
  cmd/clusterawsadm/cmd/ami/list/list.go
  cmd/clusterawsadm/cmd/flags/common.go
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterawsadm/printers/printers.go
  docs/book/.gitignore
  docs/book/Makefile
  docs/book/book.toml
  docs/book/cmd/amilist/main.go
  docs/book/src/amis.md
  docs/book/terraform/.gitignore
  docs/book/terraform/.terraform.lock.hcl
  docs/book/terraform/ami_lambda.tf
  docs/book/terraform/terraform.tfstate
  docs/book/terraform/terraform.tfstate.backup
  docs/book/theme/head.hbs
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/XXL

#2350 Test coverage
  Makefile
  scripts/ci-test-coverage.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#2319 [docs] Add multitenancy documentation
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/multitenancy.md
  docs/proposal/20200506-single-controller-multitenancy.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#2353 Add Google site verification
  docs/book/theme/head.hbs
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#2360 Replace AMI list in README with link to amis page in book.
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/M

#2362 fix: Properly handle empty string SSH key name in ASG launch template creation
  go.sum
  hack/tools/go.sum
  pkg/cloud/services/ec2/launchtemplate.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#2337 🏃‍♂️ Update cloudbuild to Go 1.16
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#2357 Rename references to the default branch to main
  docs/book/src/topics/machinepools.md
  docs/book/src/topics/multitenancy.md
  netlify.toml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#2373 bug: add namespace access to eks-contoller rules
  config/rbac/role.yaml
  controllers/awsmachine_controller.go
  controlplane/eks/config/rbac/role.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  docs/book/src/topics/multitenancy.md
  exp/controllers/awsmachinepool_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/S

#2365 book: fix typo identityidentity to staticidentity
  docs/book/src/topics/multitenancy.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note, size/S

#2370 test: Ensure teardown runs
  controllers/suite_test.go
  exp/controlleridentitycreator/suite_test.go
  exp/controllers/suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#2359 Issue 2358: Add required clustercontrolleridentities to eks rbac
  controlplane/eks/config/rbac/role.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#2366 Automated cherry pick of #2362: fix: Properly handle empty string SSH key name in ASG
  pkg/cloud/services/ec2/launchtemplate.go
Labels: approved, cncf-cla: yes, kind/backport, lgtm, size/XS

#2376 fix ineffectual assignment
  test/e2e/suites/unmanaged/unmanaged_test.go
Labels: approved, area/testing, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
