Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-02, with the labels that each got.

#3110 Remove unnecessary calls to AWS API during subnet deletion
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-triage, needs-priority

#3126 Fix cluster-api tilt reference in the book
  docs/book/src/development/tilt-setup.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3125 Fix AMI publishing failure for patch versions in book
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/ami/helper_test.go
  cmd/clusterawsadm/ami/list.go
  docs/book/src/topics/images/built-amis.md
  hack/tools/go.mod
  hack/tools/go.sum
Labels: kind/bug, size/L, approved, cncf-cla: yes, priority/backlog, lgtm, release-note

#3133 Fix e2e ECR creation/lookup
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-triage, needs-priority

#3117 Add unit tests for package pkg/cloud/tags
  pkg/cloud/tags/tags.go
  pkg/cloud/tags/tags_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3135 Bump to CAPI v1.1.0
  go.mod
  go.sum
  pkg/internal/cidr/cidr_test.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-triage, needs-priority

#3140 test/e2e: fix typo and some formatting
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-triage, needs-priority

#3142 Bump CAPI to v0.4.7
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, kind/api-change, needs-triage, needs-priority

#3145 Add lint-fix to Makefile target
  Makefile
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3137 Deleted unused files from sts package
  pkg/cloud/services/sts/identity.go
  pkg/cloud/services/sts/service.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-triage, needs-priority

#3149 release: consistent branch name determination
  Makefile
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-triage, needs-priority

#3147 Add branch variable in release-changelog
  Makefile
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3144 Make logging for creating/deleting AWS resources consistent
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/network/gateways.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/vpc.go
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, needs-triage, needs-priority

#3150 Add branch variable in release-changelog
  Makefile
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3168 Integrated `conversion-verifier` in CI
  Makefile
  api/v1alpha4/awscluster_conversion.go
  api/v1alpha4/awsclustertemplate_conversion.go
  api/v1beta1/conversion.go
  cmd/clusterawsadm/ami/helper_test.go
  hack/tools/Makefile
  hack/tools/tools.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3138 Don't ignore kubeconfig directory in git
  .gitignore
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-triage, needs-priority

#3091 Added unit test for pkg/cloud/services/autoscaling package
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Labels: size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, area/testing, needs-triage, needs-priority

#3178 Added `verify-shellcheck` make target
  Makefile
  hack/utils.sh
  hack/verify-shellcheck.sh
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3123 create right tag for LoadBalancers
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test

#3164 Test cases added for ami.go under ec2 package
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/helper_test.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/ssm/mock_ssmiface/doc.go
  pkg/cloud/services/ssm/mock_ssmiface/ssmapi_mock.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3177 Validate additionalTags
  api/v1beta1/awscluster_webhook.go
  api/v1beta1/awscluster_webhook_test.go
  api/v1beta1/awsmachine_webhook.go
  api/v1beta1/awsmachine_webhook_test.go
  api/v1beta1/tags.go
  api/v1beta1/tags_test.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook_test.go
  exp/api/v1beta1/awsfargateprofile_webhook.go
  exp/api/v1beta1/awsfargateprofile_webhook_test.go
  exp/api/v1beta1/awsmachinepool_webhook.go
  exp/api/v1beta1/awsmachinepool_webhook_test.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook_test.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, ok-to-test

#3184 Remove unused capd helper functions
  hack/utils.sh
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-triage, needs-priority

#3158 Add flatcar-stable to supported OS list for clusterawsadm
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/cmd/ami/common/copy.go
  cmd/clusterawsadm/cmd/ami/common/encryptedcopy.go
  cmd/clusterawsadm/cmd/ami/list/list.go
  docs/book/src/topics/images/built-amis.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-triage, needs-priority

#3073 Increase unit test coverage for AWSCluster controller
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
  controllers/suite_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/mock_services/elb_interface_mock.go
  pkg/cloud/services/mock_services/network_interface_mock.go
  pkg/cloud/services/mock_services/security_group_interface_mock.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, area/testing, triage/accepted

#3200 test/e2e/data/e2e_conf.yaml: bump k8s version to v1.23.3
  test/e2e/data/e2e_conf.yaml
Labels: kind/feature, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3207 Revert "Increase unit test coverage for AWSCluster controller"
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
  controllers/suite_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/mock_services/elb_interface_mock.go
  pkg/cloud/services/mock_services/network_interface_mock.go
  pkg/cloud/services/mock_services/security_group_interface_mock.go
Labels: release-note-none, size/XXL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3192 Group Makefile targets
  Makefile
  common.mk
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3173 docs: added documentation for usage of failure domains
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/failure-domains/control-planes.md
  docs/book/src/topics/failure-domains/index.md
  docs/book/src/topics/failure-domains/worker-nodes.md
Labels: size/L, approved, cncf-cla: yes, kind/documentation, lgtm, release-note, needs-triage, needs-priority

#3206 Added unit tests for pkg/cloud/services/network/routetables
  pkg/cloud/services/network/routetables_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3186 Use Wrapf for errors only when err is not nil
  pkg/cloud/services/eks/fargate.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/network/natgateways.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3159 Add integration tests for AWSCluster controller
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/helpers_test.go
  controllers/suite_test.go
  go.mod
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_machine_interface_mock.go
  pkg/cloud/services/mock_services/elb_interface_mock.go
  pkg/cloud/services/mock_services/network_interface_mock.go
  pkg/cloud/services/mock_services/security_group_interface_mock.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3156 Skip AWSMMP reconciliation if the owning Cluster or AWSMMP itself is paused
  exp/controlleridentitycreator/awscontrolleridentity_controller.go
  exp/controllers/awsmanagedmachinepool_controller.go
  pkg/cloud/services/instancestate/rule_test.go
  test/e2e/shared/resource.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-triage, needs-priority

#3210 Added go report badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-triage, needs-priority

#3205 Add unit tests for AWSCluster controller
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
Labels: size/XL, approved, cncf-cla: yes, lgtm, release-note, kind/flake, area/testing, needs-triage, needs-priority

#3194 Added `verify-book-links` make target
  Makefile
  docs/proposal/20200506-single-controller-multitenancy-flow.svg
  hack/tools/plantuml.Dockerfile
Labels: size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3199 Add list of Prow jobs to the book
  README.md
  docs/book/src/SUMMARY_SUFFIX.md
  docs/book/src/topics/reference/contributing.md
  docs/book/src/topics/reference/glossary.md
  docs/book/src/topics/reference/jobs.md
  docs/book/src/topics/reference/ports.md
  docs/book/src/topics/reference/reference.md
  docs/book/src/topics/reference/versions.md
Labels: size/L, release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, needs-triage, needs-priority

#3190 Test cases added for gateway.go
  pkg/cloud/services/network/gateways_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3196 Added test cases for pkg/cloud/services/securitygroup
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3219 Bump CAPI to v1.1.1
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, area/release, needs-triage, needs-priority

#3212 Added unit test for pkg/cloud/services/secretsmanager
  pkg/cloud/services/secretsmanager/mock_secretsmanageriface/doc.go
  pkg/cloud/services/secretsmanager/mock_secretsmanageriface/secretsmanagerapi_mock.go
  pkg/cloud/services/secretsmanager/secret_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, area/testing, needs-triage, needs-priority

#3195 Added unit test cases for pkg/cloud/services/network/vpc
  pkg/cloud/services/network/vpc_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, area/testing, needs-triage, needs-priority

#3197 Added unit tests for pkg/cloud/services/network/natgateway package
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/natgateways_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, area/testing, needs-triage, needs-priority

#3202 Test cases added for eips.go
  pkg/cloud/services/network/eips.go
  pkg/cloud/services/network/eips_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3220 Refactor cluster upgrade tests
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-triage, needs-priority

#3226 add metric bind addr and auth proxy service
  config/manager/manager.yaml
Labels: kind/feature, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3230 Update version support documentation
  docs/book/src/topics/reference/versions.md
Labels: size/M, release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, needs-triage, needs-priority

#3231 Bump CAPI to v1.1.2
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, area/release, needs-triage, needs-priority

#3217 Update AwsClusterTemplate printcolumn and remove unnecessary RBAC files
  api/v1beta1/awsclustertemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/rbac/awsclustertemplate_editor_role.yaml
  config/rbac/awsclustertemplate_viewer_role.yaml
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-triage, needs-priority

#3237 Added functions for building infra in AWS
  test/e2e/shared/aws.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3241 Bump hack/tools/golangci-lint and fix lint errors
  .golangci.yml
  exp/controllers/awsmachinepool_controller_test.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/hash/base36.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, area/release, needs-triage, needs-priority

#3251 Add SecurityGroup functions, List functions, subnet tags
  test/e2e/shared/aws.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3252 Update multitenancy doc
  docs/book/src/topics/multitenancy.md
  exp/controlleridentitycreator/awscontrolleridentity_controller_test.go
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-triage, needs-priority
