Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-07, with the labels that each got.

#3586 Increase conformance test timeout
  test/e2e/data/kubetest/conformance.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3579 feat: Create bastion security group only when bastion is enabled
  controllers/awscluster_controller.go
  controllers/awscluster_controller_unit_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3587 Increase fast conformance test timeout
  test/e2e/data/kubetest/conformance-fast.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3573 Renaming kubernetes.io/cluster tag to use EKS cluster name
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/cluster_test.go
  pkg/cloud/services/iamauth/mock_iamauth/doc.go
  pkg/cloud/services/iamauth/mock_iamauth/iamauth_mock.go
Labels: kind/bug, size/XXL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3593 Use ginkgo v2 conformance config for Kubernetes >= 1.25
  Makefile
  test/e2e/data/kubetest/conformance-ginkgo-v2.yaml
  test/e2e/suites/conformance/conformance_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3597 Fix the owner checking of a cluster
  pkg/cloud/services/eks/cluster.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3568 Add deduplication handling and only update if there is a need for it
  pkg/cloud/services/awsnode/cni.go
  pkg/cloud/services/awsnode/cni_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3595 [clusterawsadm] Fix attaching CSI policy to control plane IAM role
  cmd/clusterawsadm/cloudformation/bootstrap/csi.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3607 Add AWSMachinePool test to eks e2e test
  docs/book/src/topics/machinepools.md
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/eks/cluster-template-eks-machinepool-only.yaml
  test/e2e/suites/managed/README.md
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/helpers.go
  test/e2e/suites/managed/machine_pool.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3612 Fix aws-node-env checker to use the correct input and context
  test/e2e/suites/managed/aws_node_env.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3615 Correct broken links for EKS addons and multitenancy
  docs/book/src/topics/eks/addons.md
  docs/book/src/topics/multitenancy.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S, ok-to-test, needs-triage, needs-priority

#3613 🐛 Ensure that python and pip is installed for e2e and conformance tests
  scripts/ci-conformance.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3617 Bump github.com/golangci/golangci-lint from 1.45.2 to 1.47.2 in /hack/tools
  .golangci.yml
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XL, approved, cncf-cla: yes, lgtm, area/release, needs-triage, needs-priority

#3483 fix: Do not change default security groups during EKS control plane reconcile
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_unit_test.go
  controlplane/eks/controllers/helpers_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3609 feat: external load balancer garbage collection (part 1) - proposal
  docs/proposal/20220712-garbage-collection-delete.plantuml
  docs/proposal/20220712-garbage-collection-delete.svg
  docs/proposal/20220712-garbage-collection.md
Labels: size/L, approved, cncf-cla: yes, kind/documentation, lgtm, needs-triage, needs-priority

#3583 docs: ADR for graduating EventBridge in CAPA
  docs/adr/0005-graduation of EventBridge.md
Labels: size/M, approved, cncf-cla: yes, kind/documentation, lgtm, needs-triage, needs-priority

#3515 feat: defaulting for update config
  exp/api/v1beta1/awsmanagedmachinepool_webhook.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3610 feat: external load balancer garbage collection (part 2) - new gc service
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_unit_test.go
  controlplane/eks/controllers/helpers_test.go
  exp/api/v1beta1/awsfargateprofile_types.go
  exp/api/v1beta1/awsmachinepool_types.go
  exp/api/v1beta1/awsmanagedmachinepool_types.go
  exp/api/v1beta1/finalizers.go
  exp/api/v1beta1/types.go
  pkg/annotations/annotations.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/session.go
  pkg/cloud/services/awsnode/cni_test.go
  pkg/cloud/services/gc/cleanup.go
  pkg/cloud/services/gc/cleanup_test.go
  pkg/cloud/services/gc/ec2.go
  pkg/cloud/services/gc/loadbalancer.go
  pkg/cloud/services/gc/options.go
  pkg/cloud/services/gc/service.go
  test/mocks/aws_ec2api_mock.go
  test/mocks/aws_elb_mock.go
  test/mocks/aws_elbv2_mock.go
  test/mocks/aws_rgtagging_mock.go
  test/mocks/capa_clusterscoper_mock.go
  test/mocks/generate_aws.go
  test/mocks/generate_capa.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3468 Bump Kubernetes to v1.24.0 and fix AWSMachinePool minsize
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1beta1/awsmachinepool_types.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook_test.go
  exp/controllers/awsmachinepool_controller_test.go
  go.mod
  go.sum
  hack/ensure-kind.sh
  pkg/cloud/scope/machine_test.go
  templates/cluster-template-machinepool.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/infrastructure-aws/capi-upgrades/v1alpha3/cluster-template.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/machine-pool/machine-pool.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
Labels: size/XL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3635 Modify e2e EKS config to use cluster api v1.1.5
  test/e2e/data/e2e_eks_conf.yaml
Labels: size/M, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority
