Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-08, with the labels that each got.

#3640 Changed EventBridge ADR status to "Accepted"
  docs/adr/0005-graduation of EventBridge.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, needs-triage, needs-priority

#3618 Promote Skarlso to reviewer
  OWNERS_ALIASES
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3638 [release-1.5] Bump cluster-api to v1.1.5
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1beta1/awsmachinepool_types.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook_test.go
  exp/controllers/awsmachinepool_controller_test.go
  go.mod
  go.sum
  hack/ensure-kind.sh
  pkg/cloud/scope/machine_test.go
  templates/cluster-template-machinepool.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/infrastructure-aws/capi-upgrades/v1alpha3/cluster-template.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/machine-pool/machine-pool.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
Labels: size/XL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3632 [release-1.5] feat: external load balancer garbage collection (part 2) - new gc service
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_unit_test.go
  controlplane/eks/controllers/helpers_test.go
  exp/api/v1beta1/awsfargateprofile_types.go
  exp/api/v1beta1/awsmachinepool_types.go
  exp/api/v1beta1/awsmanagedmachinepool_types.go
  exp/api/v1beta1/finalizers.go
  exp/api/v1beta1/types.go
  pkg/annotations/annotations.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/session.go
  pkg/cloud/services/gc/cleanup.go
  pkg/cloud/services/gc/cleanup_test.go
  pkg/cloud/services/gc/ec2.go
  pkg/cloud/services/gc/loadbalancer.go
  pkg/cloud/services/gc/options.go
  pkg/cloud/services/gc/service.go
  test/mocks/aws_ec2api_mock.go
  test/mocks/aws_elb_mock.go
  test/mocks/aws_elbv2_mock.go
  test/mocks/aws_rgtagging_mock.go
  test/mocks/capa_clusterscoper_mock.go
  test/mocks/generate_aws.go
  test/mocks/generate_capa.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3633 feat: external load balancer garbage collection (part 3) - add gc to reconciliation
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  cmd/clusterawsadm/cmd/gc/disable.go
  cmd/clusterawsadm/cmd/gc/enable.go
  cmd/clusterawsadm/cmd/gc/gc.go
  cmd/clusterawsadm/cmd/root.go
  cmd/clusterawsadm/gc/gc.go
  cmd/clusterawsadm/gc/gc_test.go
  config/manager/manager.yaml
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
  controllers/awsmachine_controller_test.go
  controllers/helpers_test.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/external-resource-gc.md
  feature/feature.go
  main.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/ec2/mock_ec2iface/doc.go
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/elb/mock_elbiface/doc.go
  pkg/cloud/services/elb/mock_elbiface/elbapi_mock.go
  pkg/cloud/services/elb/mock_resourcegroupstaggingapiiface/doc.go
  pkg/cloud/services/elb/mock_resourcegroupstaggingapiiface/resourcegroupstaggingapiiface_mock.go
  pkg/cloud/services/network/eips_test.go
  pkg/cloud/services/network/gateways_test.go
  pkg/cloud/services/network/natgateways_test.go
  pkg/cloud/services/network/routetables_test.go
  pkg/cloud/services/network/secondarycidr_test.go
  pkg/cloud/services/network/subnets_test.go
  pkg/cloud/services/network/vpc_test.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  pkg/cloud/tags/tags_test.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3658 Add 1.5 version to metadata file
  metadata.yaml
Labels: cncf-cla: yes, size/XS, needs-triage, needs-priority

#3634 Fix apidiff target
  Makefile
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3639 add binary releases for windows
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, ok-to-test, needs-triage, needs-priority

#3656 Bump github.com/golangci/golangci-lint from 1.47.2 to 1.48.0 in /hack/tools
  api/v1alpha3/conditions_consts.go
  api/v1alpha4/conditions_consts.go
  api/v1beta1/conditions_consts.go
  bootstrap/eks/api/v1beta1/doc.go
  cmd/clusterawsadm/cloudformation/service/service.go
  cmd/clusterawsadm/cmd/bootstrap/credentials/credentials.go
  cmd/clusterawsadm/credentials/credentials.go
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_security_groups.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook.go
  exp/controllers/awsmachinepool_controller.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/doc.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/iamauth/mock_iamauth/doc.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/doc.go
  pkg/cloud/services/instancestate/mock_sqsiface/doc.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/secretsmanager/mock_secretsmanageriface/doc.go
  pkg/cloud/services/secretsmanager/secret_fetch_script.go
  pkg/cloud/services/ssm/mock_ssmiface/doc.go
  pkg/cloud/services/ssm/secret_fetch_script.go
  pkg/cloud/services/sts/mock_stsiface/doc.go
Labels: size/L, approved, cncf-cla: yes, lgtm, area/release, needs-triage, needs-priority

#3647 refactor: Group setup by feature flag
  main.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-triage, needs-priority

#3460 bugfix: Fix log level for a couple of message of log messages
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, ok-to-test, needs-triage, needs-priority

#3661 [E2E] Bump NVIDIA GPU operator version in GPU tests
  test/e2e/data/infrastructure-aws/kustomize_sources/gpu/clusterpolicy-crd.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/gpu/gpu-operator-components.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, kind/failing-test, needs-triage, needs-priority

#3659 Update release steps
  docs/book/src/development/releasing.md
Labels: size/M, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3563 Add spot instance support in AWSMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  docs/book/src/topics/spot-instances.md
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/services/ec2/helper_test.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  test/e2e/data/infrastructure-aws/kustomize_sources/machine-pool/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/machine-pool/spot-instance-machine-pool.yaml
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3601 Bump CAPI to v1.2.0
  .github/workflows/dependabot.yml
  .golangci.yml
  Dockerfile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  cmd/clusterawsadm/cmd/gc/disable.go
  cmd/clusterawsadm/cmd/gc/enable.go
  cmd/clusterawsadm/cmd/gc/gc.go
  cmd/clusterawsadm/gc/gc.go
  cmd/clusterawsadm/gc/gc_test.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  docs/book/src/development/development.md
  docs/triage-party/Dockerfile
  docs/triage-party/go.mod
  docs/triage-party/go.sum
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/shared/v1beta1/metadata.yaml
  test/e2e/data/shared/v1beta1_provider/metadata.yaml
  test/e2e/shared/aws_helpers.go
  test/e2e/shared/workload.go
  test/e2e/suites/gc_managed/gc_managed_suite_test.go
  test/e2e/suites/gc_managed/gc_managed_test.go
  test/e2e/suites/gc_unmanaged/gc_unmanaged_suite_test.go
  test/e2e/suites/gc_unmanaged/gc_unmanaged_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3491 Add self-hosted test based on ClusterClass
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/self-hosted-clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/self-hosted-clusterclass/limited-az-variable.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/self-hosted-clusterclass/self-hosted-variable.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/topology/clusterclass-quick-start.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_clusterclass_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3664 Rename quick-start ClusterClass to ci-default
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-topology.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/topology/cluster-template.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/topology/clusterclass-ci-default.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-triage, needs-priority

#3472 Add Cluster Upgrade tests based on ClusterClass
  test/e2e/suites/unmanaged/unmanaged_CAPI_clusterclass_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3667 refactor: Makes specs for cloud/service/network package conformant to a standard naming convention
  pkg/cloud/services/network/eips_test.go
  pkg/cloud/services/network/secondarycidr_test.go
  pkg/cloud/services/network/vpc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, kind/cleanup, needs-triage, needs-priority

#3672 [E2E] fix min desired value of MachinePool nodes for spot instance MachinePool test manifest
  test/e2e/data/infrastructure-aws/kustomize_sources/machine-pool/spot-instance-machine-pool.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, needs-triage, needs-priority

#3671 refactor: Makes specs for cloud package conformant to a standard naming convention
  pkg/cloud/scope/machine_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/eks/cluster_test.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/iamauth/crd_test.go
  pkg/cloud/services/s3/s3_test.go
  pkg/cloud/services/secretsmanager/secret_test.go
  pkg/cloud/services/ssm/secret_test.go
  pkg/cloud/tags/tags_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, kind/cleanup, ok-to-test, needs-triage, needs-priority

#3677 Fix the update logic for aws-node daemonset environment properties
  pkg/cloud/services/awsnode/cni.go
  pkg/cloud/services/awsnode/cni_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage

#3685 chore: adding rbac generation back in
  Makefile
  config/rbac/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, kind/regression, needs-triage, needs-priority

#3680 Add eks machinepool flavor template
  templates/cluster-template-eks-machinepool.yaml
Labels: size/M, approved, cncf-cla: yes, lgtm, needs-triage

#3674 adding a return nil after deleting cni
  pkg/cloud/services/awsnode/cni.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage

#3686 fixing package issues and adding SplitIntoSubnetsIPv4 unit tests
  pkg/internal/cidr/cidr_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, kind/cleanup, ok-to-test, needs-triage, needs-priority

#3094 AWSManagedMachinePool - Launch Template support
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
  docs/book/src/crd/index.md
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/awsmachinepool_types.go
  exp/api/v1beta1/awsmanagedmachinepool_types.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook.go
  exp/api/v1beta1/conditions_consts.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/awsmachinepool_tags.go
  exp/controllers/awsmanagedmachinepool_controller.go
  pkg/cloud/scope/launchtemplate.go
  pkg/cloud/scope/machine.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/tags.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_interface_mock.go
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/eks/cluster-template-eks-managed-machinepool-with-launch-template-only.yaml
  test/e2e/shared/template.go
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/helpers.go
  test/e2e/suites/managed/machine_pool.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority
