Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-06, with the labels that each got.

#3495 Revert "Create bastion security group only when bastion is enabled"
  controllers/awscluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3496 Updated `clusterawsadm ami list` nil AMI output
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/cmd/ami/list/list.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3499 [E2E] Disable external infrastructure test
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3401 first multitenancy example
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/full-multitenancy-implementation.md
Labels: size/L, approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, needs-triage, needs-priority

#3497 Publish e2e templates
  hack/gen-test-flavors.sh
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-csimigration-off.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-efs-support.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-external-cloud-provider.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-external-csi.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-external-infrastructure.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-external-securitygroups.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-gpu.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-ignition.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-internal-elb.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-kcp-remediation.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-kcp-scale-in.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-limit-az.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-machine-pool.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-md-remediation.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-multi-az.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-nested-multitenancy-clusterclass.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-nested-multitenancy.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-peered-remote.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-remote-management-cluster.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-simple-multitenancy.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-spot-instances.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-ssm.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-topology.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-upgrade-to-main.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template-upgrades.yaml
  test/e2e/data/infrastructure-aws/e2e_test_templates/cluster-template.yaml
Labels: size/XXL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3438 adding steps to recover cluster
  docs/book/src/topics/troubleshooting.md
Labels: size/L, cncf-cla: yes, kind/documentation, ok-to-test, needs-triage, needs-priority

#3328 docs: Using IAM roles instead of AWS credentials in management cluster
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/using-iam-roles-in-mgmt-cluster.md
Labels: size/M, approved, cncf-cla: yes, kind/documentation, lgtm, release-note, needs-triage, needs-priority

#3516 Update EKS e2e addon versions
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/managed/eks_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3490 feat: ability to delete kube-proxy daemonset
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/api/v1alpha3/conversion.go
  controlplane/eks/api/v1alpha3/zz_generated.conversion.go
  controlplane/eks/api/v1alpha4/conversion.go
  controlplane/eks/api/v1alpha4/zz_generated.conversion.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook_test.go
  controlplane/eks/api/v1beta1/zz_generated.deepcopy.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  docs/book/src/topics/eks/pod-networking.md
  pkg/cloud/scope/kubeproxy.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/kubeproxy/reconcile.go
  pkg/cloud/services/kubeproxy/service.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3501 Streamline Ginkgo variables
  Makefile
  docs/book/src/development/e2e.md
  docs/book/src/topics/reference/jobs.md
Labels: approved, cncf-cla: yes, priority/backlog, lgtm, size/S, kind/cleanup, ok-to-test, triage/accepted

#3520 Update EKS e2e to use k8s v1.22
  docs/book/src/topics/eks/creating-a-cluster.md
  test/e2e/data/cni/calico_eks.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/cluster.go
  test/e2e/shared/suite.go
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/upgrade_test.go
Labels: size/XL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3523 Add EKS AWSManagedMachinePool example to spot instances doc
  docs/book/src/topics/spot-instances.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S, needs-triage, needs-priority

#3519 Make CAPA tooling work on arm64
  Makefile
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3534 Adding Roadmap Update for Windows Support
  docs/roadmap.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3538 fix: Fail apidiff make target when git fails
  Makefile
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage, needs-priority

#3524 Allow disabling vpc cni when setting secondary cidr block
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/api/v1alpha3/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_webhook_test.go
  docs/book/src/topics/eks/pod-networking.md
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3552 update docs to improve new developer experience
  docs/book/src/topics/full-multitenancy-implementation.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3555 update docs to refect cluster namespace used
  docs/book/src/topics/full-multitenancy-implementation.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3561 Revert "Streamline Ginkgo variables" #3501
  Makefile
  docs/book/src/development/e2e.md
  docs/book/src/topics/reference/jobs.md
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3562 Delete unused conformance script
  scripts/ci-e2e-conformance.sh
Labels: size/L, approved, cncf-cla: yes, lgtm

#3374 feat: add custom environment variables to the 'aws-node' DaemonSet
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/api/v1alpha3/conversion.go
  controlplane/eks/api/v1alpha3/zz_generated.conversion.go
  controlplane/eks/api/v1alpha4/conversion.go
  controlplane/eks/api/v1alpha4/zz_generated.conversion.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta1/zz_generated.deepcopy.go
  docs/book/src/topics/eks/pod-networking.md
  pkg/cloud/scope/awsnode.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/awsnode/cni.go
  test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
  test/e2e/suites/managed/aws_node_env.go
  test/e2e/suites/managed/eks_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3566 Fix the json tag for VpcCni
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
  docs/book/src/topics/eks/pod-networking.md
  test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority
