Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-10, with the labels that each got.

#3741 Suspend and Resume ASG Processes
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  docs/book/src/topics/suspend-asg-processes.md
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/api/v1beta2/types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, needs-priority

#3735 normalize oidc configs to string values for comparison
  pkg/cloud/converters/eks.go
  pkg/cloud/services/eks/identity_provider.go
  pkg/eks/identityprovider/plan.go
  pkg/eks/identityprovider/plan_test.go
  pkg/eks/identityprovider/procedures.go
  pkg/eks/identityprovider/types.go
  pkg/eks/identityprovider/types_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3730 add option for disabling instance refresh
  cmd/clusterawsadm/credentials/credentials.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/controllers/awsmachinepool_controller.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, kind/api-change, ok-to-test, needs-priority

#3775 PROPOSAL: Maintainers and reviewer changes
  CONTRIBUTING.md
  OWNERS
  OWNERS_ALIASES
  README.md
Labels: kind/support, size/L, approved, cncf-cla: yes, lgtm, needs-priority

#2901 Try to find and verify existing OIDC providers before we try to create a new one
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  pkg/cloud/services/eks/iam/iam.go
  pkg/cloud/services/eks/oidc.go
  pkg/cloud/services/eks/oidc_test.go
  pkg/cloud/services/eks/service.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lifecycle/rotten, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3732 deleting additional vpc cni resources when disabled
  go.mod
  go.sum
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/awsnode/cni.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3733 switch to using interface func for consistency
  pkg/cloud/services/eks/identity_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, ok-to-test, needs-priority

#3783 fix: wrong EKS tag when upgrading older clusters
  pkg/cloud/services/eks/cluster.go
Labels: kind/bug, priority/critical-urgent, approved, cncf-cla: yes, lgtm, size/S, triage/accepted

#3787 [release-1.5] fix: wrong EKS tag when upgrading older clusters
  pkg/cloud/services/eks/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3771 Bump golangci-lint in /hack/tools and aws-iam-authenticator
  api/v1beta2/awsmachine_webhook_test.go
  docs/book/cmd/amilist/main.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/instancestate/mock_eventbridgeiface/eventbridgeiface_mock.go
  pkg/cloud/services/network/vpc.go
  pkg/eks/identityprovider/plan.go
  test/e2e/shared/context.go
  test/mocks/aws_ec2api_mock.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, area/release, needs-priority

#3752 Add EventBridge ec2 event reconciliation and rule creation to eks managed control planes
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  test/e2e/data/e2e_eks_conf.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-priority

#3795 Skip deleting 'control-plane.cluster-api-provider-aws.sigs.k8s.io' if it does not exist in the e2e setup
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#3792 PROPOSAL: move Daniel to maintainer
  OWNERS_ALIASES
  README.md
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#3757 Enhance the EKSConfigTemplate and add configuration for files, mounts, users, ntp, etc for CAPI feature parity
  bootstrap/eks/api/v1beta1/conversion.go
  bootstrap/eks/api/v1beta1/zz_generated.conversion.go
  bootstrap/eks/api/v1beta2/eksconfig_types.go
  bootstrap/eks/api/v1beta2/zz_generated.deepcopy.go
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/internal/userdata/commands.go
  bootstrap/eks/internal/userdata/disk_setup.go
  bootstrap/eks/internal/userdata/files.go
  bootstrap/eks/internal/userdata/fs_setup.go
  bootstrap/eks/internal/userdata/kubelet_args.go
  bootstrap/eks/internal/userdata/mounts.go
  bootstrap/eks/internal/userdata/node.go
  bootstrap/eks/internal/userdata/node_test.go
  bootstrap/eks/internal/userdata/ntp.go
  bootstrap/eks/internal/userdata/users.go
  bootstrap/eks/internal/userdata/utils.go
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3800 [E2E] Fix test flavor generation make targets
  Makefile
Labels: priority/critical-urgent, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, kind/regression

#3526 Allow multiple security group filter matches
  controllers/awsmachine_controller_unit_test.go
  controllers/awsmachine_security_groups.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/launchtemplate.go
Labels: size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3798 fix: remove check for root volume device name on create
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/awsmachine_webhook_test.go
  api/v1beta2/awsmachinetemplate_webhook.go
  api/v1beta2/awsmachinetemplate_webhook_test.go
  exp/api/v1beta2/awsmachinepool_webhook.go
  exp/api/v1beta2/awsmachinepool_webhook_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, needs-priority

#3681 rework vpc cni envvar logic to drop the forced keys
  docs/book/src/topics/eks/pod-networking.md
  pkg/cloud/services/awsnode/cni.go
  pkg/cloud/services/awsnode/cni_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage

#3808 chore: Backport maintainer/reviewer updates to release-1.6
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-priority

#3807 chore: Backport maintainer/reviewer updates to release-1.5
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-priority
