Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-04, with the labels that each got.

#3375 fix: removes unused release notes target
  Makefile
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, triage/accepted, needs-priority

#3376 fix: update GH_VERSION to v2.7.0
  versions.mk
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3380 Disable external infra tests
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3379 Revert #3343 e2e test changes
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/services.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/machine_deployment.go
  test/e2e/suites/managed/machine_pool.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/failing-test, needs-triage, needs-priority

#3385 Add v1.4 release to metadata.yaml
  metadata.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3368 Apidiff test runs only if there are changes in api/ or exp/api/
  Makefile
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, needs-triage, needs-priority

#3387 Only setup setup-envtest when the test target is called
  Makefile
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage, needs-priority

#3366 Merge external infrastructure, peered VPCs, internal ELB and private subnets E2E test.
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-infrastructure/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-infrastructure/patches/external-infrastructure.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-securitygroups/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/az-select.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/az-select.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/external-securitygroups.yaml
  test/e2e/shared/aws.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3393 Bump AWS SDK Go and AWS IAM Authenticator
  go.mod
  go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
  pkg/cloud/services/s3/mock_s3iface/s3api_mock.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, area/release, needs-triage, needs-priority

#3378 Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3388 Fix for release log creation script
  Makefile
  hack/releasechangelog.sh
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3400 Only attempt to delete bootstrap data secret if InsecureSkipSecretsManager isn't set
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage, needs-priority

#3412 Bump AWS SDK Go and AWS VPC CNI
  go.mod
  go.sum
  pkg/cloud/services/ec2/mock_ec2iface/ec2api_mock.go
Labels: size/M, approved, cncf-cla: yes, lgtm, area/release, needs-triage, needs-priority

#3417 Remove KIAM page from the book
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/using-cluster-api-with-cross-account-role-assumption.md
Labels: size/L, approved, cncf-cla: yes, kind/documentation, lgtm, needs-triage, needs-priority

#3413 Remove list webhooks
  api/v1alpha3/webhook_suite_test.go
  api/v1beta1/awsclustercontrolleridentitylist_webhook.go
  api/v1beta1/awsclusterlist_webhook.go
  api/v1beta1/awsclusterroleidentitylist_webhook.go
  api/v1beta1/awsmachinelist_webhook.go
  api/v1beta1/awsmachinetemplatelist_webhook.go
  api/v1beta1/suite_test.go
  controllers/suite_test.go
  docs/book/src/crd/index.md
  exp/controllers/suite_test.go
  exp/instancestate/suite_test.go
  main.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-triage, needs-priority

#3416 Add role assumption trust policy example to book
  docs/book/src/topics/multitenancy.md
Labels: size/M, approved, cncf-cla: yes, kind/documentation, lgtm, needs-triage, needs-priority

#3418 Move several functions under E2E CreateInfrastructure to panic
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3426 Backport #3400 to 1.4 branch
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3425 Updates e2e test cluster names to include spec name
  test/e2e/suites/conformance/conformance_test.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/upgrade_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3389 Add multi-tenancy test based on ClusterClass
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy-clusterclass/cluster-template.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy-clusterclass/clusterclass-multi-tenancy.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy-clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy-clusterclass/role.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_quick_clusterclass_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_clusterclass_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3257 Added lookup for fields of type AWSResourcesReference
  api/v1alpha4/conversion.go
  api/v1beta1/awsmachine_webhook.go
  api/v1beta1/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller_unit_test.go
  controllers/awsmachine_security_groups.go
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/conversion_test.go
  exp/api/v1alpha4/conversion_test.go
  exp/api/v1beta1/awsmachinepool_webhook.go
  exp/api/v1beta1/awsmachinepool_webhook_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/helper_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_interface_mock.go
Labels: kind/bug, size/L, cncf-cla: yes, lgtm, priority/important-soon, release-note

#3398 Validate Tags created for the resources
  api/v1beta1/tags.go
  api/v1beta1/tags_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3415 Update roadmap
  docs/roadmap.md
Labels: size/M, approved, cncf-cla: yes, kind/documentation, lgtm, needs-triage, needs-priority

#3429 [E2E] Fix failing tests because of change in cluster names
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, needs-triage, needs-priority

#3382 [E2E] Added tests for using filters in AWSResourceReference type fields
  test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-securitygroups/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/patches/bastion-enabled.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/patches/subnet-with-filters.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/additional-security-group.yaml
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, area/testing, needs-triage, needs-priority

#3436 Use registry.k8s.io registry in CI jobs
  test/e2e/data/cni/calico_eks.yaml
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-cloud-provider/aws-ebs-csi-external.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-csi/aws-ebs-csi-external.yaml
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3430 Scope cleanup
  pkg/cloud/scope/awsnode.go
  pkg/cloud/scope/iamauth.go
  pkg/cloud/scope/network.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/awsnode/service.go
  pkg/cloud/services/iamauth/service.go
  pkg/cloud/services/network/service.go
  pkg/cloud/services/network/subnets_test.go
  pkg/cloud/services/securitygroup/service.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-triage, needs-priority

#3437 Bump cert-manager version in the tests
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  versions.mk
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3344 :bug: ./build/generate-go-apis to run on api change
  Makefile
  docs/book/src/crd/index.md
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage, needs-priority

#3442 Makefile: use 'rm -f' for verify-boilerplate
  Makefile
Labels: approved, cncf-cla: yes, size/XS, kind/cleanup, needs-triage, needs-priority

#3450 Revert ":bug: ./build/generate-go-apis to run on api change"
  Makefile
  docs/book/src/crd/index.md
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority
