Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-03, with the labels that each got.

#3263 Remove manager_name from tilt-provider.json
  tilt-provider.json
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-triage, needs-priority

#3258 Added a join slack badge in CAPA repo for k8s cluster-api-aws channel
  README.md
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-triage, needs-priority

#3260 Added OpenSSF best practices badge to README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, area/security, needs-triage, needs-priority

#3240 Block ELB re-creation after the cluster has been provisioned
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/elb.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, priority/important-soon, size/S, release-note, triage/accepted

#3124 Add support for custom protocol for ELB health checks
  api/v1alpha3/awscluster_conversion.go
  api/v1alpha3/zz_generated.conversion.go
  api/v1alpha4/awscluster_conversion.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1beta1/awscluster_types.go
  api/v1beta1/awscluster_webhook.go
  api/v1beta1/awscluster_webhook_test.go
  api/v1beta1/network_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  test/e2e/data/infrastructure-aws/kustomize_sources/limit-az/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/limit-az/patches/elb-health-check-protocol.yaml
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-triage, needs-priority

#3234 Add ClusterSecurityGroupsReadyCondition to managedcontrolplane's patchObject
  pkg/cloud/scope/managedcontrolplane.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3229 Enable EKS upgrade test
  Makefile
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/identity.go
  test/e2e/shared/suite.go
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/upgrade_test.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3222 Adding apidiff target to the Makefile
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/ci-apidiff.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-triage, needs-priority

#3157 Fix change condition conflict in reconcileDelete
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-triage, needs-priority

#3189 Test cases added for secondary cidr file
  pkg/cloud/services/network/secondarycidr.go
  pkg/cloud/services/network/secondarycidr_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3099 Added unit test cases for launchtemplate.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/helper_test.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3261 Functioning Sec Groups E2E test and refactor AWS infrastructure functions
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-infrastructure/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-infrastructure/patches/external-infrastructure.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-securitygroups/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/external-securitygroups/patches/external-securitygroups.yaml
  test/e2e/shared/aws.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, area/testing, needs-triage, needs-priority

#3270 update manifest to match latest release
  metadata.yaml
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, ok-to-test, needs-triage, needs-priority

#3278 fix: Apidiff prow job is failing
  Makefile
  scripts/ci-apidiff.sh
Labels: release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, ok-to-test, needs-triage, needs-priority

#3281 docs: Added documentation for usage of spot instances
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/spot-instances.md
Labels: size/M, approved, cncf-cla: yes, kind/documentation, lgtm, release-note, needs-triage, needs-priority

#3255 Added subnet IDs lookup by AWSMachinePool Spec Subnets.Filters
  exp/api/v1beta1/awsmachinepool_webhook.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/autoscaling/service.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-triage, needs-priority

#3291 Change assertion for DetachInternetGateway to Eventually
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-triage, needs-priority

#2864 Query AWS to find subnets with explicitely specified subnet IDs
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, priority/important-soon, release-note, ok-to-test, triage/accepted

#3247 Documentation for usage of externally managed clusters
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
Labels: size/M, approved, cncf-cla: yes, kind/documentation, lgtm, release-note, needs-triage, needs-priority

#3285 Adds an E2E test for using peered VPCs and an internal ELB
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/internal-elb.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/management.yaml
  test/e2e/shared/aws.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3298 Removed hardcoding for AMIs in bastion host and added latest AMI lookup
  docs/book/src/topics/accessing-ec2-instances.md
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/bastion_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-triage, needs-priority

#3289 docs: Developer guideline to write unit/integration tests in CAPA repo
  docs/book/src/development/conventions.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S, release-note, needs-triage, needs-priority

#3309 Readme updated with OS name and indentation
  README.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/S, needs-triage, needs-priority

#3312 Added AWSMachinepool webhook create and update test
  exp/api/v1beta1/awsmachinepool_webhook_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, needs-triage, needs-priority

#3293 Upgrade to use latest Kind version v0.12.0
  docs/book/src/development/development.md
  hack/ensure-kind.sh
  hack/tools/go.mod
  hack/tools/go.sum
  scripts/ci-e2e-eks.sh
  scripts/ci-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, area/release, needs-triage, needs-priority

#3311 Add specific AZ to peered VPC and ELB test
  test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/az-select.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/az-select.yaml
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-triage, needs-priority

#3318 [E2E] Test to check if bastion host is running when enabled
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/nested-multitenancy/patches/bastion-enabled.yaml
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, area/testing, needs-triage, needs-priority

#3322 Remove .metadata.clusterName usage
  pkg/cloud/services/eks/addons.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-triage, needs-priority

#3264 fix: asgNeedsUpdates invalid condition (pointers)
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3334 Bump golanci-lint in /hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, area/release, needs-triage, needs-priority

#3223 Add integration tests for AWSMachine controller
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  controllers/helpers_test.go
  docs/book/src/SUMMARY_PREFIX.md
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/elb_interface_mock.go
Labels: size/XXL, approved, cncf-cla: yes, release-note, area/testing, needs-triage, needs-priority

#3340 Fix lint errors due to golangci-lint bump
  go.mod
  pkg/record/recorder.go
  test/helpers/external/cluster.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3339 update kustomize install instructions
  docs/book/src/development/development.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-triage, needs-priority

#3214 Change the release process to use GitHub Release Notes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  Makefile
  hack/changelog.tpl
  hack/releasechangelog.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3337 feat: add nodegroup update config support
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1alpha3/conversion.go
  exp/api/v1alpha3/zz_generated.conversion.go
  exp/api/v1alpha4/conversion.go
  exp/api/v1alpha4/zz_generated.conversion.go
  exp/api/v1beta1/awsmanagedmachinepool_types.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook.go
  exp/api/v1beta1/awsmanagedmachinepool_webhook_test.go
  exp/api/v1beta1/types.go
  exp/api/v1beta1/zz_generated.deepcopy.go
  go.mod
  pkg/cloud/converters/eks.go
  pkg/cloud/services/eks/nodegroup.go
  test/e2e/data/eks/cluster-template-eks-managed-machinepool-only.yaml
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, kind/api-change, needs-triage, needs-priority

#3320 update multi-tenacy docs
  docs/book/src/topics/multitenancy.md
Labels: size/M, approved, cncf-cla: yes, kind/documentation, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3355 netlify: fix missing go.sum entry for blang/semver
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-triage, needs-priority

#3350 Bump to golangci-lint v1.45.2
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, area/release, needs-triage, needs-priority

#3359 Fix flaky integration test
  controllers/awscluster_controller_test.go
  controllers/helpers_test.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/flake, area/testing, needs-triage, needs-priority

#3354 Modify internal ELB test to only use private subnet
  test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/az-select.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/internal-elb/patches/internal-elb.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/peered-remote/patches/az-select.yaml
  test/e2e/shared/common.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-triage, needs-priority

#3351 Makefile: don't log verbose from tests by default
  Makefile
  scripts/ci-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-triage, needs-priority

#3362 Using setup-envtest to install kubebuilder dependency
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  scripts/ci-test.sh
  scripts/fetch_ext_bins.sh
  scripts/go_install.sh
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3347 Disassociate secondary CIDR after subnets are deleted
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  pkg/cloud/services/network/network.go
  test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-triage, needs-priority

#3343 :bug: fixes services for EKS clusters
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/ec2/instances.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/services.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/machine_deployment.go
  test/e2e/suites/managed/machine_pool.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, kind/failing-test, priority/important-soon, release-note, ok-to-test, triage/accepted
