Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-05, with the labels that each got.

#3391 [E2E] EFS CSI driver support
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/aws-efs-csi-external.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/csi-resource-set.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/kustomization.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/efs-support/patches/efs-support.yaml
  test/e2e/shared/aws.go
  test/e2e/shared/defaults.go
  test/e2e/shared/template.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3458 Remove CAPI test package import in `clusterawsadm`
  cmd/clusterawsadm/ami/helper.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3459 [E2E] Fix failing GPU test due to update in the CUDA Linux GPG Repository Key
  test/e2e/data/infrastructure-aws/kustomize_sources/gpu/gpu-operator-components.yaml
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, needs-triage, needs-priority

#3457 Add timeout to AllocateAddress
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3461 Added `owner-id` flag for `clusterawsadm ami list`
  cmd/clusterawsadm/ami/list.go
  cmd/clusterawsadm/cmd/ami/list/list.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-triage, needs-priority

#3448 Add ssm test based on ClusterClass
  test/e2e/data/infrastructure-aws/kustomize_sources/topology/cluster-template.yaml
  test/e2e/data/infrastructure-aws/kustomize_sources/topology/clusterclass-quick-start.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_quick_clusterclass_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_clusterclass_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority

#3471 [E2E] Add retry and timeout to GetSubnetByName in CreateNatGateway
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-triage, needs-priority

#3462 Add ClusterClass templates
  templates/cluster-template-multitenancy-clusterclass.yaml
  templates/cluster-template-simple-clusterclass.yaml
Labels: size/XL, approved, cncf-cla: yes, lgtm, needs-triage, needs-priority
