Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2022-11, with the labels that each got.

#3790 Change naming format of AMIs while searching for AMIs
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/ami/helper_test.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/ami_test.go
Labels: kind/bug, priority/critical-urgent, size/M, approved, cncf-cla: yes, lgtm

#3812 Revert "Change naming format of AMIs while searching for AMIs"
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/ami/helper_test.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/ami_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, needs-priority

#3683 allow annotation on MachinePool to set externally managed
  config/rbac/role.yaml
  docs/book/src/crd/index.md
  docs/book/src/topics/machinepools.md
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/ec2/helper_test.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, needs-priority

#3819 docs: Refactor release process guide
  docs/book/src/development/releasing.md
Labels: size/L, approved, cncf-cla: yes, kind/documentation, lgtm, needs-priority

#3818 [release-1.5] Fix ProviderIDList in managed machinepool
  pkg/cloud/services/eks/nodegroup.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#3815 Added machinehealthcheck to cluster-template-machinepool
  templates/cluster-template-machinepool.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S, ok-to-test, needs-priority

#3467 Fix typo in AWSManagedMachinePool UpdateConfig
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1beta1/types.go
Labels: approved, cncf-cla: yes, lifecycle/rotten, lgtm, size/XS, kind/cleanup, ok-to-test, needs-triage, needs-priority

#3749 Deletion fails for aws cluster with vpc limit exceeded
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/network/vpc.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#3825 Revert "Merge pull request #3467 from phoban01/fix-awsmachinepool-spec typo"
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1beta1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-priority

#3769 More nil checks for Version
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#3831 docs: Update CRD reference with v1beta2 API
  docs/book/src/crd/index.md
Labels: size/XXL, approved, cncf-cla: yes, kind/documentation, lgtm, needs-priority

#3833 Make overwrite the default behaviour for conflict resolution in addons
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/api/v1beta2/types.go
  docs/book/src/topics/eks/addons.md
  pkg/cloud/services/eks/addons.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3836 chore: bump capi to 1.2.5
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#3838 Add CCM tag to routing tables
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/routetables_test.go
  pkg/cloud/services/network/subnets.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3832 Clean up internet-facing loadbalancer scheme logic
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/defaults.go
  api/v1beta2/network_types.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: size/M, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#3840 docs: restore comment describing specific envsubst usage
  config/rbac/serviceaccount.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-priority

#3842 e2e: remove Subnet CCM tags
  test/e2e/shared/aws.go
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3850 Remove Equals() from v1beta2 Tags API
  api/v1beta2/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-priority

#3843 fix: Replace misleading wording used for security group overrides
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-priority

#3835 Remove ARN field from AWSResourceReference
  api/v1beta1/awsmachine_conversion.go
  api/v1beta1/conversion.go
  api/v1beta1/conversion_test.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1beta2/awsmachinepool_webhook.go
  go.mod
  pkg/logger/logger.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/cleanup, kind/api-change, needs-priority

#3841 [E2E] Add check that the pod list is not empty.
  test/e2e/suites/managed/eks_ipv6_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, needs-priority

#3847 Remove failure domain from AWSMachineSpec to respect CAPI's Machine/MD failure domain field
  api/v1beta1/conversion.go
  api/v1beta1/conversion_test.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  test/e2e/data/infrastructure-aws/withclusterclass/clusterclassbase/clusterclass-ci-default.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/topology/clusterclass-ci-default.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-internal-elb.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-peered-remote.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/internal-elb/patches/az-select.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/internal-elb/patches/internal-elb.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/peered-remote/patches/az-select.yaml
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/cleanup, kind/api-change, needs-priority

#3829 Change AMI name generation based on new format in image-builder
  cmd/clusterawsadm/ami/helper.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/bug, priority/critical-urgent, size/M, approved, cncf-cla: yes, lgtm

#3823 [E2E] Use k8s version 1.24.4 in conformance test and increase control plane wait timeout for conformance and EKS tests
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/shared/aws.go
Labels: priority/critical-urgent, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, area/testing, kind/regression

#3867 Fix lastAppliedTags annotations naming
  controllers/awsmachine_security_groups.go
  controllers/awsmachine_tags.go
  pkg/cloud/services/ec2/launchtemplate.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#3877 docs: updated Developer Guide with changes to make it more accurate
  docs/book/src/development/development.md
  docs/book/src/development/tilt-setup.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S, ok-to-test, needs-priority

#3878 test: increased cluster creation timeout for eks e2e
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/suites/managed/cluster.go
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, kind/flake, needs-priority

#3868 chore: bump capi to 1.2.6
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, needs-priority

#3881 [E2E] Update CAPA version in tests
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/shared/v1beta2_provider/metadata.yaml
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/helpers.go
  test/e2e/suites/managed/upgrade_test.go
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, area/testing, needs-priority

#3886 [E2E] Fix AWS services creation flake in external infrastructure test
  test/e2e/shared/aws.go
Labels: size/M, approved, cncf-cla: yes, lgtm, kind/flake, area/testing, needs-priority

#3890 drop /v2/ from api/tests/docs
  api/v1beta2/tags.go
  controllers/awscluster_controller_test.go
  controllers/awsmachine_controller_test.go
  controllers/helpers_test.go
  docs/book/src/topics/accessing-ec2-instances.md
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/network/egress_only_gateways_test.go
  pkg/cloud/services/network/gateways_test.go
  pkg/cloud/services/network/natgateways_test.go
  pkg/cloud/services/network/routetables_test.go
  pkg/cloud/services/network/subnets_test.go
  pkg/cloud/services/network/vpc_test.go
  pkg/cloud/services/secretsmanager/secret_test.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  pkg/cloud/services/ssm/secret_test.go
  pkg/cloud/tags/tags_test.go
  test/e2e/shared/aws.go
Labels: kind/bug, size/L, priority/critical-urgent, approved, cncf-cla: yes, lgtm, kind/regression

#3864 Remove suspend process flow from create ASG
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, needs-priority
