Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-06, with the labels that each got.

#4306 fix: building release-binaries fails
  Makefile
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4314 [release-1.5] [E2E] Fix kubernetes version for EKS upgrade tests
  test/e2e/suites/managed/upgrade_test.go
Labels: priority/critical-urgent, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note

#4304 Allow customization of ingress rules in control plane LB security group
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_types.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4017 Fix EKSControlPlaneReconciliationFailed when OIDC already exists
  pkg/cloud/services/eks/iam/iam.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#4328 E2E tests for AlternativeGCStrategy
  test/e2e/shared/workload.go
  test/e2e/suites/gc_managed/gc_managed_test.go
  test/e2e/suites/gc_unmanaged/gc_unmanaged_test.go
Labels: kind/support, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4321 chore: Bump CAPI to v1.4.3
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  exp/controllers/awsmachinepool_controller_test.go
  go.mod
  go.sum
  pkg/cloud/scope/machine.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  versions.mk
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4100 [E2E] Enable EventBridge in the tests
  test/e2e/data/e2e_conf.yaml
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/flake, area/testing, needs-priority

#4341 check TagUmanagedNetworkResources feature gate before tagging subnets for LBs
  controllers/helpers_test.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4353 [release-2.0] Reconcile EKSConfig correctly for MachinePool and other Owner kinds
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  bootstrap/eks/controllers/eksconfig_controller_test.go
  pkg/logger/logger.go
  test/e2e/shared/template.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, kind/backport, needs-priority

#4334 [release-2.1] chore: Bump CAPI to v1.4.3
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  exp/controllers/awsmachinepool_controller_test.go
  go.mod
  go.sum
  pkg/cloud/scope/machine.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  versions.mk
Labels: kind/support, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4346 feat: add support for EKS addon configuration
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/api/v1beta1/types.go
  controlplane/eks/api/v1beta1/zz_generated.conversion.go
  controlplane/eks/api/v1beta2/types.go
  pkg/cloud/services/eks/addons.go
  pkg/eks/addons/procedures.go
  pkg/eks/addons/types.go
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/eks/cluster-template-eks-control-plane-only-withaddon.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/managed/addon.go
  test/e2e/suites/managed/addon_helpers.go
  test/e2e/suites/managed/eks_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4365 Use public.ecr.aws for golang image
  Dockerfile
Labels: kind/support, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4362 Pass right SGs for IsExternallyManaged on creation
  pkg/cloud/services/ec2/instances.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4347 Use default arch x86_64 for AMI lookup if `ec2:DescribeInstanceTypes` permission is missing
  pkg/cloud/awserrors/errors.go
  pkg/cloud/services/ec2/ami.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority

#4367 chore: remove usage of script to install golangci-lint
  hack/ensure-golangci-lint.sh
  hack/tools/Makefile
  versions.mk
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority
