Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-01, with the labels that each got.

#3958 [E2E] Increase test timeout in Ginkgo args
  Makefile
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, kind/flake, area/testing, needs-priority

#3960 Move sedefsavas to emeritus
  OWNERS
  OWNERS_ALIASES
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3936 Update ASG if subnet changes
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
Labels: size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3959 Update scan action
  .github/workflows/scan.yml
  Makefile
  hack/verify-container-images.sh
Labels: size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3966 refactor: Improved all testcases naming convention conformity to camel case standard
  api/v1beta1/network_types_test.go
  api/v1beta1/tags_test.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/awsclustercontrolleridentity_webhook_test.go
  api/v1beta2/awsclusterroleidentity_webhook_test.go
  api/v1beta2/awsclusterstaticidentity_webhook_test.go
  api/v1beta2/awsmachine_webhook_test.go
  api/v1beta2/network_types_test.go
  api/v1beta2/sshkeyname_test.go
  api/v1beta2/tags_test.go
  bootstrap/eks/controllers/eksconfig_controller_test.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go
  exp/api/v1beta2/awsfargateprofile_webhook_test.go
  exp/api/v1beta2/awsmachinepool_webhook_test.go
  exp/api/v1beta2/awsmanagedmachinepool_webhook_test.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/eks/cluster_test.go
  pkg/cloud/services/s3/s3_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, kind/cleanup, ok-to-test, needs-priority

#3871 Update LoadBalancerReadyCondition on deletion
  controllers/awscluster_controller.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3957 Bump controller-tools and gojq in /hack/tools
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/third_party/conversion-gen/main.go
Labels: kind/support, size/L, approved, cncf-cla: yes, lgtm, area/release, needs-priority

#3941 Expose Metrics port
  config/default/kustomization.yaml
  config/default/metrics_service.yaml
  config/manager/manager.yaml
  pkg/cloud/logs/logs.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3976 Adding tags to OIDC providers
  pkg/cloud/converters/tags.go
  pkg/cloud/services/eks/oidc.go
  pkg/cloud/services/eks/oidc_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3982 Revert "capa fix hardcoded role arn for aws iam authenticator"
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_types.go
  cmd/clusterawsadm/api/bootstrap/v1beta1/defaults.go
  cmd/clusterawsadm/cloudformation/bootstrap/fargate.go
  cmd/clusterawsadm/cloudformation/bootstrap/managed_nodegroup.go
  cmd/clusterawsadm/cloudformation/bootstrap/template.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controlplane/eks/api/v1beta1/conversion.go
  controlplane/eks/api/v1beta1/conversion_test.go
  controlplane/eks/api/v1beta1/zz_generated.conversion.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta2/conversion.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/fargate.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/eks/roles.go
  pkg/cloud/services/iamauth/reconcile.go
  pkg/cloud/services/s3/s3.go
  util/system/util.go
Labels: size/L, approved, cncf-cla: yes, lgtm, needs-priority

#3978 Fail creation of machine pool if no subnets matching filters found
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3992 [Release-1.5] Removed io/ioutil import
  pkg/cloud/services/s3/s3_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#3967 Apply #3871 "Update LoadBalancerReadyCondition on deletion" to release-1.5
  controllers/awscluster_controller.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3440 Introduce args in releasechangelog script
  Makefile
  hack/releasechangelog.sh
Labels: size/M, approved, cncf-cla: yes, lgtm, ok-to-test, needs-triage, kind/refactor, needs-priority

#3996 Ignore EIGW deletion in case of unmanaged VPC
  pkg/cloud/services/network/egress_only_gateways.go
  pkg/cloud/services/network/egress_only_gateways_test.go
  pkg/cloud/services/network/gateways.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#4002 Fix AWS CloudFormation dump after failed suit when there is no bootstrap cluster
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4008 Reorder the bootstrapping logic so AWSSession is available in afterSuite
  test/e2e/shared/aws.go
  test/e2e/shared/suite.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#3999 Fixes for gc related tests
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/suites/gc_managed/gc_managed_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#4006 Fix boilerplate
  api/v1beta2/awsmanagedcluster_types.go
  controllers/awsmanagedcluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, ok-to-test, needs-priority

#4019 Bump ginkgo and klog in /hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, approved, cncf-cla: yes, lgtm, area/release, needs-priority

#4022 Replace E2E_FOCUS with GINKGO_FOCUS in all jobs
  Makefile
  docs/book/src/development/e2e.md
  docs/book/src/topics/reference/jobs.md
Labels: approved, cncf-cla: yes, lgtm, size/S, area/testing, needs-priority

#4000 fix(#3980): save the API ELB AZ to NetworkStatus
  pkg/cloud/services/elb/loadbalancer.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#4024 Run tests on localhost to increase security and avoid macOS firewall popup dialogs
  test/helpers/envtest.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#4025 Move defaulting before creation of patch helper so that no differences will be detected unnecessarily
  controllers/awscluster_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-priority

#4023 Fix `make test` for Apple M1 (darwin-arm64), fail if kubebuilder assets cannot be found
  Makefile
Labels: approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, ok-to-test, needs-priority
