Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-10, with the labels that each got.

#4535 [release-2.2] cherry-pick: Fix cluster-api-provider-last-applied-tags-on-volumes to recalculate the value on each reconcile
  controllers/awsmachine_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4542 fix: make kpromo version consistent
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4545 fix: kpromo failed during release
  Makefile
  docs/book/src/development/releasing.md
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4453 Introduce rosaControlPlane for managed kubernetes
  Makefile
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosaclusters.yaml
  config/rbac/role.yaml
  controllers/rosacluster_controller.go
  controlplane/rosa/api/v1beta2/groupversion_info.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/api/v1beta2/rosacluster_types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  feature/feature.go
  go.mod
  go.sum
  main.go
  pkg/cloud/scope/rosacontrolplane.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, release-note, tide/merge-method-squash, ok-to-test, needs-priority

#4547 fix: remove unused context imports
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/network/natgateways_test.go
  pkg/cloud/services/network/vpc_test.go
  pkg/cloud/services/secretsmanager/secret_test.go
  pkg/cloud/services/ssm/secret_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4474 :bug: Restore subnet management functionality
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/network_types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  pkg/cloud/scope/shared_test.go
  pkg/cloud/services/awsnode/cni.go
  pkg/cloud/services/awsnode/cni_test.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-multi-az.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/multi-az/patches/multi-az.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/bug, priority/critical-urgent, size/XL, approved, cncf-cla: yes, lgtm, release-note-action-required, kind/api-change, kind/regression

#4564 :bug: Fix "error: externally-managed-environment" CI
  scripts/ci-conformance.sh
  scripts/ci-e2e-eks-gc.sh
  scripts/ci-e2e-eks.sh
  scripts/ci-e2e-gc.sh
  scripts/ci-e2e.sh
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#4565 e2e: Remove double install
  scripts/ci-e2e.sh
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4518 🌱 Tag S3 bucket as owned by cluster
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4553 :sparkles: Support ignition v3 and presigned URLs
  api/v1beta1/conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_types.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/s3bucket.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  go.mod
  go.sum
  pkg/cloud/services/s3/s3.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4566 :bug: ELBv2 target groups should inherit tags
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: kind/bug, size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4557 :bug: On deletion, should ignore if the secret cannot be found
  controllers/awsmachine_controller.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4558 [release-2.2] [E2E] Fix E2E pipeline failures
  scripts/ci-conformance.sh
  scripts/ci-e2e-eks-gc.sh
  scripts/ci-e2e-eks.sh
  scripts/ci-e2e-gc.sh
  scripts/ci-e2e.sh
  test/e2e/data/e2e_conf.yaml
Labels: kind/support, release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, needs-priority

#4571 When tagging security groups, ensure cloud provider tag is only on lb
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#4563 :sparkles: Support additional TCP listeners on NLBs
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_types.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controllers/awsmachine_controller.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/elb_interface_mock.go
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4567 Try to delete as many resources as possible, then requeue
  controllers/awscluster_controller.go
  controllers/awscluster_controller_unit_test.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#4579 fix: sorting the tags list to make it determined
  pkg/cloud/services/s3/s3.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4552 :seedling: Allow ESP protocol to be set in IngressRules
  api/v1beta2/network_types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  pkg/cloud/services/securitygroup/securitygroups.go
  test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-internal-elb.yaml
Labels: kind/feature, size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4536 [PROPOSAL] Reviewer and maintainer changes
  OWNERS_ALIASES
  README.md
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4576 ⚠️ Log according to sig-instrumentation guidelines
  controllers/awsmachine_controller.go
  exp/controllers/awsmachinepool_controller.go
  pkg/logger/logger.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, kind/cleanup, needs-priority

#4590 Fix the backport of #4512 into release-2.2 branch
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, kind/regression, needs-priority

#4597 Update CAPA supported AMI OS
  cmd/clusterawsadm/ami/helper.go
  docs/book/src/topics/images/built-amis.md
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4575 fix: eks e2e test failing as subnet name was used
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/network/routetables.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, kind/regression, needs-priority
