Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-08, with the labels that each got.

#4417 Add new on-demand and spot allocation strategies
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1beta2/types.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4445 bug: add missing elasticloadbalancing permissions to cloudformation
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note-action-required, ok-to-test, needs-priority

#4467 chore: approve actions on ok-to-test
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: kind/feature, size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4384 IMDSv2 on AWSManagedMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  docs/book/src/topics/instance-metadata.md
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority
