Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-02, with the labels that each got.

#4005 Move all E2E test templates to use external CCM and CSI
  hack/gen-test-flavors.sh
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/clusterclassbase/clusterclass-ci-default.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/clusterclassbase/clusterclass-multi-tenancy.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/external-vpc-clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/nested-multitenancy-clusterclass/cluster-template.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/nested-multitenancy-clusterclass/clusterclass-multi-tenancy.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/nested-multitenancy-clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/self-hosted-clusterclass/kustomization.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/topology/cluster-template.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/topology/clusterclass-ci-default.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/topology/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/ccm/data/aws-ccm-external.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/ccm/patches/external-cloud-provider.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/ccm/resources/ccm-resource-set.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/cni/patches/cluster-cni.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/cni/resources/cni-resource-set.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/csi/data/aws-ebs-csi-external.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/csi/patches/external-csi-provider.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/addons/csi/resources/csi-resource-set.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/csimigration-off/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/default/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/default/patches/cluster-resource-set-cni.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/efs-support/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/efs-support/machine-deployment.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/efs-support/patches/limit-az.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/external-cloud-provider/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/external-csi/aws-ebs-csi-external.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/external-csi/csi-resource-set.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/external-csi/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/gpu/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/gpu/patches/gpu-instance-type.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/ignition/patches/control-plane-ignition.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/ignition/patches/worker-ignition.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/intree-cloud-provider/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/intree-cloud-provider/machine-deployment.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/machine-pool/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/machine-pool/machine-pool.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/machine-pool/patches/external-csi-provider-controlplane.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/machine-pool/spot-instance-machine-pool.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/upgrade-to-external-cloud-provider/kustomization.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/upgrade-to-external-cloud-provider/patches/upgrade-external-ccm.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/upgrades/machine-pool.yaml
  test/e2e/shared/defaults.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#3973 chore: Bump CAPI to v1.3.3
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  versions.mk
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, priority/important-soon

#4030 Ensure tags on managed VPCs
  pkg/cloud/services/network/vpc.go
  pkg/cloud/services/network/vpc_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, needs-priority

#4033 Ensure empty `loadBalancerType` field value is handled correctly
  api/v1beta2/awscluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4018 Bump controller-tools in /hack/tools
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
  config/crd/bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, priority/important-soon, area/release

#3991 Allow user to specify the Name tag value for AWS tags
  api/v1beta2/tags.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4044 [E2E] Fix CF role deletion flake
  test/e2e/shared/aws.go
Labels: priority/critical-urgent, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, area/testing

#4045 Remove unnecessary `.AnyTimes()` mock calls for unmanaged VPC test
  controllers/awscluster_controller_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, kind/cleanup, ok-to-test, needs-priority

#4011 fix: use instance profiles of machine pools and machine deployments for mapping roles
  config/rbac/role.yaml
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  pkg/cloud/services/iamauth/reconcile.go
  pkg/cloud/services/iamauth/reconcile_test.go
  pkg/cloud/services/iamauth/service.go
  pkg/cloud/services/iamauth/suite_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4048 Fix error condition on eventually
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4059 fix: cleanup AWS CloudFormation stack in Test environment
  cmd/clusterawsadm/cloudformation/service/service.go
  cmd/clusterawsadm/cmd/bootstrap/iam/cloudformation.go
  pkg/cloud/services/securitygroup/securitygroups.go
  test/e2e/shared/aws.go
Labels: kind/bug, priority/critical-urgent, size/M, approved, cncf-cla: yes, lgtm

#4061 [E2E] Fix service quotas for EventBridge rules
  test/e2e/shared/aws.go
  test/e2e/shared/defaults.go
  test/e2e/shared/resource.go
  test/e2e/suites/gc_unmanaged/gc_unmanaged_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_clusterclass_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_quick_clusterclass_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_quick_test.go
  test/e2e/suites/unmanaged/unmanaged_CAPI_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_clusterclass_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/failing-test, needs-priority

#4055 fix error validating message
  api/v1beta2/awscluster_webhook.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#4072 docs: fix git-repository-url
  docs/book/book.toml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-priority

#4069 chore(ref): add more robustness to cloudformation stack create in tests
  cmd/clusterawsadm/cloudformation/service/service.go
  test/e2e/shared/aws.go
  test/e2e/shared/suite.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, needs-priority

#4074 chore: adding release notes section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, needs-priority

#4073 chore: remove usage of images from k8s.gcr.io
  test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-gpu.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/gpu/gpu-operator-components.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, needs-priority

#4076 chore(ref): always clean roles and resources on cf stack failure
  cmd/clusterawsadm/cloudformation/service/service.go
  cmd/clusterawsadm/cmd/bootstrap/iam/cloudformation.go
  test/e2e/shared/aws.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, needs-priority

#4077 chore(ref): add output of error for role deletion
  test/e2e/shared/aws.go
  test/e2e/shared/suite.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#4078 chore(ref): fix error checking in eventually
  test/e2e/shared/aws.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#4079 bug: order of deleting cloud formation resources matters and fix missing GroupName setting from Bootstrap user
  cmd/clusterawsadm/api/bootstrap/v1beta1/defaults.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  test/e2e/shared/aws.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, needs-priority

#4066 Bump envsubst in /hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS, area/release, needs-priority

#4095 cleaning up unnecessary object patches
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  exp/controllers/awsfargatepool_controller.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmanagedmachinepool_controller.go
  pkg/cloud/scope/cluster.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4098 fix: invalid yaml in multi-tenancy example
  docs/book/src/topics/multitenancy.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-priority

#4087 chore: Bump ginkgo version
  Makefile
  go.mod
  go.sum
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/cloud/services/iamauth/reconcile_test.go
Labels: kind/support, size/L, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4092 Modify AWSMachine reconciliation behavior to terminate and create instances without blocking
  controllers/awscluster_controller_test.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#3728 Update AWSMachine webhook validate logic on update to be consistent
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/awsmachinetemplate_webhook.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority
