Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-12, with the labels that each got.

#4670 :bug: Update awsmachine providerID and instanceID immediately after ec2:RunInstances is called
  pkg/cloud/services/ec2/instances.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4662 :bug: There is no need to check instance refresh if ASG is not found
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4676 :sparkles: Enable transit encryption to S3 bucket
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4679 🌱 bump sigs.k8s.io/aws-iam-authenticator from 0.6.12 to 0.6.13
  go.mod
  go.sum
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  test/mocks/aws_ec2api_mock.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4688 🐛 chore: update dependabot to group updates
  .github/dependabot.yml
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, needs-priority

#4692 🌱 chore: change the ignore dependabot updates
  .github/dependabot.yml
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-priority

#4678 🐛: Use external CCM in default template
  templates/cluster-template.yaml
Labels: size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4698 🐛 There is no need to check instance refresh if ASG is not found (cherry-pick to release-2.3)
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4701 🐛 Fix deregistering of deleted CAPI Machines
  controllers/awsmachine_controller.go
  pkg/cloud/scope/machine.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority
