Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-09, with the labels that each got.

#4406 Allow securing api LB, only allowing traffic from required sources
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  pkg/cloud/interfaces.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/network.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, kind/api-change, ok-to-test, needs-priority

#4473 chore: bump kpromo to a newer version
  hack/tools/Makefile
  versions.mk
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/S, kind/cleanup, needs-priority

#4472 feat: use k/k tooling for release notes
  Makefile
  hack/changelog.tpl
  hack/releasechangelog.sh
  hack/tools/Makefile
  versions.mk
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4466 Make garbage collection configurable
  exp/api/v1beta2/types.go
  pkg/cloud/services/gc/cleanup.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4481 Add missing boilerplate
  pkg/cloud/services/gc/compose.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#4484 Add GC configuration tests
  pkg/cloud/services/gc/cleanup_test.go
Labels: kind/support, size/L, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4485 Add validation for GC tasks annotation
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/types.go
  cmd/clusterawsadm/gc/gc.go
  cmd/clusterawsadm/gc/gc_test.go
  exp/api/v1beta2/types.go
  pkg/cloud/services/gc/cleanup.go
  pkg/cloud/services/gc/cleanup_test.go
Labels: kind/support, size/L, release-note-none, approved, cncf-cla: yes, lgtm, tide/merge-method-squash, needs-priority

#4495 Fix error loop for ignition
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
Labels: kind/bug, size/M, release-note-none, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4449 Set availability zones in status.networkStatus.apiServerElb when using BYO NLB
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4444 feat: support IPAM Manager for VPC creation
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go
  pkg/cloud/filter/ec2.go
  pkg/cloud/services/network/vpc.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4507 feat: add table describing supported feature gates and their default values
  docs/book/src/topics/reference/reference.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S, release-note, ok-to-test, needs-priority

#4359 Additional ingress rules for control plane
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controlplane/eks/api/v1beta1/zz_generated.conversion.go
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4512 fix: propagate AdditionalTags from AWSCluster to storage volumes
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4463 fix: don't generate nodegroup role name starting with hyphen
  pkg/cloud/services/eks/roles.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#4508 Save Nat Gateways IPs to status on every reconciliation
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4490 Replace all AWS SDK calls with their WithContext analogs
  controllers/awscluster_controller_test.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/ec2/ami.go
  pkg/cloud/services/ec2/ami_test.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/bastion_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/securitygroup.go
  pkg/cloud/services/eks/tags.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/gc/ec2.go
  pkg/cloud/services/network/account.go
  pkg/cloud/services/network/egress_only_gateways.go
  pkg/cloud/services/network/egress_only_gateways_test.go
  pkg/cloud/services/network/eips.go
  pkg/cloud/services/network/eips_test.go
  pkg/cloud/services/network/gateways.go
  pkg/cloud/services/network/gateways_test.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/natgateways_test.go
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/routetables_test.go
  pkg/cloud/services/network/secondarycidr.go
  pkg/cloud/services/network/secondarycidr_test.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
  pkg/cloud/services/network/vpc.go
  pkg/cloud/services/network/vpc_test.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
  pkg/cloud/tags/tags.go
  pkg/cloud/tags/tags_test.go
  test/e2e/shared/aws.go
Labels: kind/support, release-note-none, size/XXL, approved, cncf-cla: yes, lgtm, tide/merge-method-squash, needs-priority

#4464 feat: allow for specifying subnet type for az
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/api/v1beta2/awsmanagedmachinepool_types.go
  exp/api/v1beta2/awsmanagedmachinepool_webhook.go
  exp/api/v1beta2/awsmanagedmachinepool_webhook_test.go
  exp/api/v1beta2/types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/scope/shared.go
  pkg/cloud/scope/shared_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, tide/merge-method-squash, ok-to-test, needs-priority

#4522 Bump CAPI to v1.5.2
  go.mod
  go.sum
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  versions.mk
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4524 [release-2.2] Add additional ingress rules for CP to API
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controlplane/eks/api/v1beta1/zz_generated.conversion.go
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4525 Bump aws-vpc-cni to v1.15.0
  go.mod
  go.sum
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/iamauth/mock_iamauth/iamauth_mock.go
  pkg/cloud/services/instancestate/mock_sqsiface/sqsiface_mock.go
  test/mocks/aws_ec2api_mock.go
Labels: kind/support, size/XL, approved, cncf-cla: yes, lgtm, release-note, area/release, needs-priority

#4529 flatcar: Run kubeadm after containerd
  templates/cluster-template-flatcar.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/e2e_test_templates/cluster-template-ignition.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/ignition/patches/control-plane-ignition.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/ignition/patches/worker-ignition.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4531 Fix cluster-api-provider-last-applied-tags-on-volumes to recalculate the value on each reconcile
  controllers/awsmachine_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority
