Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-05, with the labels that each got.

#4234 added reset_test.go
  pkg/internal/rate/reset_test.go
Labels: kind/feature, size/M, release-note-none, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4255 feat: Include controller IAM for instance metadata operations
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4256 🐛 Allow the defaulting of InstanceMetadataOptions to go through for AWSMachineTemplates
  api/v1beta2/awsmachinetemplate_webhook.go
  api/v1beta2/awsmachinetemplate_webhook_test.go
Labels: priority/critical-urgent, size/M, approved, cncf-cla: yes, lgtm, release-note

#4130 Remove CAPA tagging from unmanaged network resources
  config/manager/manager.yaml
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmanagedmachinepool_controller.go
  feature/feature.go
  main.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/network.go
  pkg/cloud/services/network/egress_only_gateways.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
  pkg/cloud/services/network/vpc.go
  pkg/cloud/services/network/vpc_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note-action-required, needs-priority

#4250 Set httpPutResponseHopLimit to 2 when creating instances
  api/v1beta2/awsmachinetemplate_webhook_test.go
  api/v1beta2/types.go
  controllers/awsmachine_controller_unit_test.go
  docs/book/src/topics/instance-metadata.md
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4263 Use dl.k8s.io instead of kubernetes-release bucket
  hack/ensure-kubectl.sh
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, kind/cleanup, ok-to-test, needs-priority

#4244 Bump CAPI to v1.4.2
  go.mod
  go.sum
  test/e2e/data/e2e_eks_conf.yaml
  versions.mk
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4264 fix: remove modification of networkinterface for ipv6
  pkg/cloud/services/ec2/launchtemplate.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4249 Feature: add default behaviour for clusterawsadm bootstrap iam print-policy
  cmd/clusterawsadm/cloudformation/bootstrap/iam.go
  cmd/clusterawsadm/cmd/bootstrap/iam/iam_doc.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4272 e2e: add elasticfilesystem:TagResource action
  test/e2e/shared/template.go
Labels: release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, needs-priority

#4274 Set IMDSv2 as optional
  api/v1beta2/awsmachinetemplate_webhook_test.go
  api/v1beta2/types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller_unit_test.go
  docs/book/src/topics/instance-metadata.md
  pkg/cloud/services/ec2/instances.go
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4273 :sparkles: Add support to specify PlacementGroup Name in instances
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/awsmachine_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4285 fix: resolve secrets when generating eks userdata
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4288 fix: resolve secrets when generating eks userdata (backport #4285)
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4132 4046 - Add AssumeRole and update appropriate tests
  cmd/clusterawsadm/api/bootstrap/v1alpha1/zz_generated.conversion.go
  cmd/clusterawsadm/api/bootstrap/v1beta1/types.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  docs/book/src/topics/multitenancy.md
  docs/book/src/topics/using-clusterawsadm-to-fulfill-prerequisites.md
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4228 Additional ingress rules for control plane
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_types.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4292 fix: remove set nodes role
  pkg/cloud/services/iamauth/reconcile.go
  test/e2e/suites/managed/cluster.go
  test/e2e/suites/managed/eks_ipv6_test.go
  test/e2e/suites/managed/upgrade_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4164 add IRSA for self-managed clusters proposal
  docs/proposal/20230317-irsa-support-for-awscluster.md
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, kind/design, needs-priority

#4300 Requque when awsmachine is pending
  controllers/awsmachine_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority
