Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2023-07, with the labels that each got.

#3805 Do not return error if secret does not exist
  controllers/awsmachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, lifecycle/stale, needs-priority

#4360 :bug: compare string value of protocol in health check instead of pointer
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4363 Drop unwanted SGs when calling attachSecurityGroupsToNetworkInterface
  pkg/cloud/services/ec2/instances.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4380 Switch to constants for asg not found events, simplify asg lookup
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, ok-to-test, needs-priority

#4372 Bump CAPI to v1.4.4
  go.mod
  go.sum
  hack/ensure-kind.sh
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  versions.mk
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4383 [release-2.2] Update metadata.yaml
  test/e2e/data/shared/v1beta2_provider/metadata.yaml
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4386 chore: update metedata.yaml with the release series
  metadata.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4387 Wrap error message for failing to retrieve infra provider cluster
  controllers/awsmachine_controller.go
  exp/controllers/awsmachinepool_controller.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#4400 Bump docker/distribution to v2.8.2 and golang.org/x/net to v0.7.0
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4378 Improve AWSMachinePool diff to default to existing values when comparing launch templates
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4399 Customize golang version
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4409 [E2E] Bump k8s version to v1.26.6 to fix conformance tests
  test/e2e/data/e2e_conf.yaml
Labels: kind/support, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, release-note, needs-priority

#4410 Customize golang version
  Dockerfile
  Makefile
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4411 Customize golang version
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4412 Customize golang version
  Dockerfile
  Makefile
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4357 Add elasticloadbalancing:SetSubnets to cloudformation
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note-action-required, needs-priority

#4421 Backport verify container images to release 2.0
  Makefile
  hack/verify-container-images.sh
Labels: kind/support, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4392 Setup Trivy scanning for supported release branches
  .github/workflows/scan.yml
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority
