Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2024-02, with the labels that each got.

#4723 🐛 Make VPC creation idempotent to avoid indefinite creation of new VPCs if storage of the ID fails
  controllers/awscluster_controller_test.go
  pkg/cloud/services/network/vpc.go
  pkg/cloud/services/network/vpc_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4733 ✨ Add support for a secondary control plane load balancer
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_types.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/defaults.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controllers/awsmachine_controller.go
  controllers/helpers_test.go
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/crd/index.md
  docs/book/src/topics/network-load-balancer-with-awscluster.md
  docs/book/src/topics/secondary-load-balancer.md
  docs/proposal/20220712-garbage-collection-delete.svg
  docs/proposal/IPv6 Sequence Diagram.svg
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/elb.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/elb_interface_mock.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4619 ✨ Trigger machine pool instance refresh (node rollout) if bootstrap config reference changes
  api/v1beta2/tags.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/awsmanagedmachinepool_controller.go
  pkg/cloud/scope/launchtemplate.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/doc.go
  pkg/cloud/services/mock_services/ec2_interface_mock.go
  pkg/cloud/services/mock_services/reconcile_interface_mock.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4779 :bug: Use Kube v1.29.1 for EKS e2e tests
  test/e2e/data/e2e_eks_conf.yaml
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#4760 ✨ Add `DefaultInstanceWarmup` field to `AWSMachineDeployment` spec
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/api/v1beta2/awsmachinepool_webhook.go
  exp/api/v1beta2/types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, tide/merge-method-squash, ok-to-test, needs-priority

#4768 :sparkles: Makefile: handle $GOPATH with a trailing slash
  Makefile
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4775 📖 Improve ROSA quickstart with MachinePool and troubleshooting guide
  docs/book/src/topics/rosa/enabling.md
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-priority

#4438 ✨ Supporting externally managed Control Plane
  api/v1beta2/awscluster_types.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/conditions_consts.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/rbac/role.yaml
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  controllers/suite_test.go
  pkg/cloud/scope/machine.go
  pkg/cloud/scope/machine_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/secretsmanager/secret_test.go
  pkg/cloud/services/ssm/secret_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4767 :sparkles: rosa: load identity dynamically
  Makefile
  api/v1beta1/awscluster_types.go
  api/v1beta2/awscluster_types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controllers/rosacluster_controller.go
  controlplane/eks/api/v1beta1/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_types.go
  controlplane/rosa/api/v1beta2/defaults.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/api/v1beta2/zz_generated.defaults.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/controllers/rosamachinepool_controller.go
  main.go
  pkg/cloud/interfaces.go
  pkg/cloud/scope/rosacontrolplane.go
  pkg/cloud/scope/session.go
  pkg/rosa/clusters.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4700 ✨ Ignition: add option to store User Data in plain text
  api/v1beta1/conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  docs/book/src/topics/ignition-support.md
  test/e2e/suites/unmanaged/helpers_test.go
  test/e2e/suites/unmanaged/unmanaged_functional_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4791 :sparkles: *: add OWNERS for ROSA
  config/crd/bases/OWNERS
  controllers/OWNERS
  controlplane/rosa/OWNERS
  docs/book/src/topics/rosa/OWNERS
  exp/api/v1beta2/OWNERS
  exp/controllers/OWNERS
  pkg/cloud/scope/OWNERS
  pkg/rosa/OWNERS
  templates/OWNERS
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#4764 ✨ ROSA: Reconcile ROSAMachinePool version
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_webhook.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  docs/book/src/topics/rosa/creating-a-cluster.md
  exp/api/v1beta2/conditions_consts.go
  exp/api/v1beta2/rosamachinepool_types.go
  exp/api/v1beta2/rosamachinepool_webhook.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/rosamachinepool_controller.go
  main.go
  pkg/rosa/nodepools.go
  pkg/rosa/versions.go
  templates/cluster-template-rosa-machinepool.yaml
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4637 ✨ Add test for provider-managed infrastructure, fix writing latest status back into `ClusterScope`
  api/v1beta2/network_types.go
  cmd/clusterawsadm/converters/cloudformation.go
  controllers/awscluster_controller_test.go
  pkg/cloud/converters/tags.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/eks/iam/iam.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/routetables.go
  pkg/cloud/services/network/subnets.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4798 🌱 Bump kubernetes/release notes tool to v0.16.5
  versions.mk
Labels: kind/support, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4799 :bug: Delete VPC endpoints only if s3 bucket is enabled
  controllers/awscluster_controller_test.go
  pkg/cloud/services/network/vpc.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#4803 [release-2.3] 🌱 Bump go version to 1.21
  Makefile
  docs/book/src/development/development.md
  docs/triage-party/Dockerfile
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
Labels: kind/support, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4794 :bug: Don't reconcile security groups on NLBs from older versions of CAPA
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: kind/bug, size/L, priority/critical-urgent, release-note-none, approved, cncf-cla: yes, lgtm

#4809 🐛 fix: staging image build failed due to toolchain directive
  cloudbuild.yaml
  go.mod
  hack/tools/go.mod
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4810 🐛 chore: rollback changes to cloudbuild file
  cloudbuild.yaml
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4814 🐛 [RELEASE-2.3] Changes to release process
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  docs/triage-party/Dockerfile
  go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  netlify.toml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4813 🐛 fix: changes to release process
  Makefile
  cloudbuild-nightly.yaml
  cloudbuild.yaml
  go.mod
  hack/tools/go.mod
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4819 🌱 chore: disable dependency report
  Makefile
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4825 🌱 chore: disable the dependency report short term
  Makefile
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4765 :sparkles: rosa: use the openshift/rosa libraries where we can
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  config/webhook/manifests.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_webhook.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/api/v1beta2/rosamachinepool_types.go
  exp/api/v1beta2/rosamachinepool_webhook.go
  exp/controllers/rosamachinepool_controller.go
  go.mod
  go.sum
  main.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/rosa/client.go
  pkg/rosa/clusters.go
  pkg/rosa/idps.go
  pkg/rosa/nodepools.go
  pkg/rosa/users.go
  pkg/rosa/util.go
  pkg/rosa/versions.go
  test/mocks/aws_ec2api_mock.go
Labels: release-note-none, size/XXL, approved, cncf-cla: yes, lgtm, needs-priority

#4828 🌱 Making ControlPlane LoadBalancer immutable for disabled type
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, ok-to-test, needs-priority

#4822 🌱 Expose Cluster Control Plane ref through cluster scope
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  pkg/cloud/interfaces.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/machine.go
  pkg/cloud/scope/machine_test.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/shared.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/secretsmanager/secret_test.go
  pkg/cloud/services/ssm/secret_test.go
  test/mocks/capa_clusterscoper_mock.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#4780 🌱 Add missing Fields to RosaControlPlane
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  templates/cluster-template-rosa-machinepool.yaml
  templates/cluster-template-rosa.yaml
Labels: kind/feature, size/L, release-note-none, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4833 🌱 chore: add release 2.4.x to metadata
  metadata.yaml
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4836 🐛 fix: bump rosa deps to fix int overflow on non-64bit arch
  go.mod
  go.sum
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority
