Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2024-08, with the labels that each got.

#5079 🌱 feat: add issue templates for reviewers/maintainer changes
  .github/ISSUE_TEMPLATE/maintainer_change.yml
  .github/ISSUE_TEMPLATE/reviewer_change.yml
Labels: kind/support, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5078 :seedling: Update Go version to 1.22.6
  .github/workflows/dependabot.yml
  .github/workflows/release.yaml
  .golangci.yml
  Makefile
  docs/book/src/development/development.md
  docs/triage-party/Dockerfile
  docs/triage-party/go.mod
  hack/ensure-go.sh
  hack/tools/go.mod
  netlify.toml
Labels: kind/support, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#5083 🐛 ROSA: Fix ROSAMchinePool spec.Taints diff detection
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
Labels: kind/bug, size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority, area/provider/rosa

#5095 :seedling: Dependabot cleanup
  .github/dependabot.yml
  go.mod
  go.sum
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#5106 Add permissions to the GitHub Actions token
  .github/workflows/dependabot.yml
  .github/workflows/pr-verify.yml
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority
