Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2024-07, with the labels that each got.

#5044 🌱 Remove vincepri from cluster-api-aws-maintainers
  OWNERS_ALIASES
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#5024 🐛: securitygroup: fix comparison of ingress rules sets.
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5048 🐛 Fix subtests running in same environment and reconciliation bug which was not covered because of that
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/services/ec2/launchtemplate.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5051 🐛 subnets: use "owned" k8s tag value for managed subnets.
  controllers/awscluster_controller_test.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5057 ✨ Ensure Volumes and Network Interfaces are also tagged when created as part of instance creation
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5055 :bug: Update filenames for released binaries
  .goreleaser.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, kind/regression, needs-priority

#4648 ✨ Add separate eks kubeconfig secret keys for the cluster-autoscaler
  docs/book/src/topics/eks/creating-a-cluster.md
  pkg/cloud/services/eks/config.go
  pkg/cloud/services/eks/config_test.go
  test/e2e/shared/suite.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5060 🌱 [PROPOSAL]: Move Andidog to maintainer
  OWNERS
  OWNERS_ALIASES
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, kind/cleanup, needs-priority

#4971 ✨ SubnetSchema support
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5040 🐛 awsmachine: only register machine to LB when it's running
  controllers/awsmachine_controller.go
  pkg/cloud/services/elb/errors.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5047 ✨ Added the CapacityReservation support
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/awsmachine_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5009 :bug: Remove Helm condition for AWS VPC CNI deletion
  docs/book/src/topics/eks/pod-networking.md
  go.mod
  pkg/cloud/services/awsnode/cni.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5071 🌱chore: update metadata for v2.6.0
  metadata.yaml
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#5072 🌱 chore: change name of prevent deletion label
  api/v1beta2/types.go
  docs/book/src/topics/eks/pod-networking.md
  pkg/cloud/services/awsnode/cni.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4898 ✨ Support adding custom secondary VPC CIDR blocks in `AWSCluster`
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/network.go
  pkg/cloud/scope/shared.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/network.go
  pkg/cloud/services/network/secondarycidr.go
  pkg/cloud/services/network/secondarycidr_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority
