Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2024-06, with the labels that each got.

#4990 🐛Use generate name for CP loadbalancer listeners
  go.mod
  go.sum
  pkg/cloud/services/elb/loadbalancer.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4991 🐛Apply the same set of rules for processing all custom ingress rules
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4998 ✨ ROSA: Add upgrade config to ROSAMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  exp/api/v1beta2/rosamachinepool_types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
  go.mod
  go.sum
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, area/api, needs-priority

#5004 🐛 Reconcile target groups and listeners as their own entities
  controllers/awscluster_controller_test.go
  controllers/helpers_test.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  test/helpers/matchers.go
Labels: kind/bug, size/XXL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4996 🌱 Bump setup-envtest to use new controller-tools binaries
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#4905 ✨ Support BYO Public IPv4 Pool when provision infrastructure
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/awsmachine_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/awsmachine_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/eip.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
  pkg/cloud/services/ec2/service.go
  pkg/cloud/services/elb/eip.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/service.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_interface_mock.go
  pkg/cloud/services/network/eips.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/natgateways_test.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, kind/documentation, lgtm, release-note, kind/api-change, ok-to-test, needs-priority

#5016 🐛 ROSA: fix ROSAMachinePool.Spec.UpdateConfig causing unnecessary update calls
  exp/api/v1beta2/rosamachinepool_webhook.go
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
Labels: kind/bug, size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority, area/provider/rosa

#5017 🐛 Fix creation of target groups and listeners in the reconcile loop
  pkg/cloud/services/elb/loadbalancer.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5005 ✨ Add natgatewayips as source for ingress rules
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/network_types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5035 📖 fix docs typos
  docs/book/src/topics/eks/prerequisites.md
  docs/book/src/topics/iam-permissions.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-priority
