Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2024-01, with the labels that each got.

#4710 ✨ Use go 1.21.5, fix kubectl version detection after `--short` parameter was removed
  .github/workflows/dependabot.yml
  .golangci.yml
  Makefile
  docs/book/src/development/development.md
  docs/triage-party/Dockerfile
  docs/triage-party/go.mod
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/ensure-kubectl.sh
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4665 🌱ROSA Cleanup & Documentation
  Makefile
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  docs/book/src/SUMMARY_PREFIX.md
  docs/book/src/crd/index.md
  docs/book/src/topics/reference/reference.md
  docs/book/src/topics/rosa/creating-a-cluster.md
  docs/book/src/topics/rosa/enabling.md
  docs/book/src/topics/rosa/index.md
  templates/cluster-template-rosa.yaml
Labels: release-note-none, size/XXL, approved, cncf-cla: yes, kind/documentation, lgtm, kind/cleanup, ok-to-test, needs-priority

#4709 ✨ Log full ARN in GC error messages
  pkg/cloud/services/gc/ec2.go
  pkg/cloud/services/gc/loadbalancer.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#4685 :bug: Wrap error when AWSMachinePool reconciler fails to get infra provider cluster
  exp/controllers/awsmachinepool_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#4667 :bug: cleanup: eliminate log spam when using S3 secrets
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, ok-to-test, needs-priority

#4724 🌱 Fix some logging and error cases
  controllers/awscluster_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  pkg/cloud/services/eks/config.go
  pkg/cloud/services/eks/roles.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, needs-priority

#4707 :sparkles: Remove ingress and egress rules from vpc default security group
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/network_types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  pkg/cloud/awserrors/errors.go
  pkg/cloud/filter/ec2.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/securitygroup/securitygroups_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4730 ✨ Skip AWSCluster deletion reconciliation once CAPA finalizer is gone
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#4732 :bug: S3 Bucket should be created in the same region, always add transport encryption policy
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4751 🌱 Move AverageMarcus to emeritus status
  OWNERS
  OWNERS_ALIASES
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#4756 :book: Add /agenda redirect to book
  docs/book/book.toml
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, needs-priority

#4742 ✨ ROSA: Generate CAPI kubeconfig secret
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  pkg/cloud/scope/rosacontrolplane.go
  pkg/rosa/client.go
  pkg/rosa/clusters.go
  pkg/rosa/idps.go
  pkg/rosa/nodepools.go
  pkg/rosa/oauth.go
  pkg/rosa/users.go
  pkg/rosa/util.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4759 ✨ ROSA: Reconcile ROSAControlePlane status
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controllers/rosacluster_controller.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/controllers/rosamachinepool_controller.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4720 🐛 Updating verify kubectl version script
  hack/ensure-kubectl.sh
  hack/utils.sh
Labels: kind/bug, size/M, release-note-none, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4664 :sparkles: feat: support setting HostnameType options for subnets and machines
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/awsmachine_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/awsmachine_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/network/subnets.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4761 ✨ ROSA: Reconcile ROSAControlPlane version
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/conditions_consts.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  pkg/rosa/versions.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4541 ✨ Add AWSMachine fields to control vpc placement for the instance
  api/v1beta1/awsmachine_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller_test.go
  docs/book/src/topics/bring-your-own-aws-infrastructure.md
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/feature, size/L, do-not-merge/hold, approved, cncf-cla: yes, lgtm, release-note, needs-priority
