Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2024-12, with the labels that each got.

#5240 :bug: Downgrade kustomize and prevent dependabot bumps
  .github/dependabot.yml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/regression, needs-priority

#5250 🌱 test: log aws account being used
  test/e2e/shared/aws.go
  test/e2e/shared/suite.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#5238 :bug: Fixed a few typos.
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  docs/book/src/topics/rosa/upgrades.md
  pkg/rosa/versions.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#5244 :bug: Fixed RosaMachinePool typo.
  exp/api/v1beta2/conditions_consts.go
  exp/controllers/rosamachinepool_controller.go
  pkg/cloud/scope/rosamachinepool.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority
