Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2024-03, with the labels that each got.

#4839 🐛 fix: s3 bucket in us-east-1 should not set location constraint
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4804 ✨ ROSA: Reconcile ROSAMachinePool fields
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controlplane/rosa/api/v1beta2/conditions_consts.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_webhook.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/api/v1beta2/rosamachinepool_types.go
  exp/api/v1beta2/rosamachinepool_webhook.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
  main.go
  pkg/cloud/scope/rosacontrolplane.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4831 ✨ ROSA: Reconcile ROSAMachinePool.spec.ProviderIDList
  exp/controllers/rosamachinepool_controller.go
  pkg/cloud/scope/machine.go
  pkg/cloud/scope/providerid.go
  pkg/cloud/scope/providerid_test.go
  pkg/cloud/scope/rosamachinepool.go
  pkg/rosa/helpers.go
  pkg/rosa/versions.go
Labels: kind/feature, size/L, needs-rebase, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4848 ✨ ROSA: Add additionalSecurityGroups field to ROSAMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  exp/api/v1beta2/rosamachinepool_types.go
  exp/api/v1beta2/rosamachinepool_webhook.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/rosamachinepool_controller.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4789 :seedling: Update awsmachinetemplate_webhook.go, fix typo
  api/v1beta2/awsmachinetemplate_webhook.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#4844 ✨Add new fields to ROSAControlPlane - additionalTags, etcdEncryption, endpointAccess
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/doc.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_webhook.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/api/v1beta2/zz_generated.defaults.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  docs/book/src/crd/index.md
  templates/cluster-template-rosa-machinepool.yaml
  templates/cluster-template-rosa.yaml
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4750 🌱 Add support for Ignition v3 Proxy and TLS
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awsmachine_types.go
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/awsmachine_webhook_test.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  controllers/awsmachine_controller.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4852 :seedling: Align dependabot config with upstream cluster-api
  .github/dependabot.yml
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#4840 🐛 fix: additional control plane LBs must use correct schema/subnets
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/elb.go
  pkg/cloud/services/elb/loadbalancer.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority

#4793 :book: docs: adds some notes for the release process
  docs/book/src/development/releasing.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, needs-priority

#4830 :bug: fix upgrade of managed node groups using custom AMIs
  pkg/cloud/services/eks/nodegroup.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority

#4851 ✨ ROSA: support long cluster name
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  go.mod
  go.sum
Labels: kind/feature, size/M, release-note-none, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4850 ✨ ROSA: Cleanup
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/conditions_consts.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/zz_generated.deepcopy.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  docs/book/src/crd/index.md
  exp/api/v1beta2/conditions_consts.go
  exp/controllers/rosamachinepool_controller.go
Labels: release-note-none, size/XL, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#4857 ✨ ROSA: Support audit log forwarding
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/api/v1beta2/rosacontrolplane_webhook.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  docs/book/src/crd/index.md
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#4863 ✨ Add nodeDrainGracePeriod for RosaMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  exp/api/v1beta2/rosamachinepool_types.go
  exp/controllers/rosamachinepool_controller.go
  go.mod
  go.sum
Labels: kind/feature, size/M, release-note-none, approved, cncf-cla: yes, lgtm, needs-ok-to-test, needs-priority

#4869 ✨ ROSA: Add additionalTags API field to ROSAMachinePool
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  docs/book/src/crd/index.md
  exp/api/v1beta2/rosamachinepool_types.go
  exp/api/v1beta2/rosamachinepool_webhook.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, kind/api-change, needs-priority

#4872 ✨ ROSA: Add ProvisionShardID API field to ROSAControlPlane
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#4877 🐛 ROSA: Fix domainPrefix not being set
  controlplane/rosa/controllers/rosacontrolplane_controller.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#4846 🐛 Allow overriding health check endpoint protocol
  api/v1beta2/network_types.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4860 :bug: Create a `aws.Config` with region to be able to work different AWS partition (like gov cloud or china AWS partition)
  pkg/cloud/identity/identity.go
  pkg/cloud/identity/identity_test.go
  pkg/cloud/scope/session.go
  pkg/cloud/scope/session_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority

#4873 🐛 ROSA: fix auto scale and multi zone compute nodes
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-priority

#4845 :sparkles: Add flags for leaderElection timeouts
  main.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#4841 :bug: fix: Fix instance PrivateDNSName when domain-name is set in dhcpOpts
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  controllers/awsmachine_controller_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: kind/bug, size/L, release-note-none, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#4879 :bug: fix: s3: fix bucket object not found
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, tide/merge-method-squash, ok-to-test, needs-priority
