Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2025-09, with the labels that each got.

#5645 :bug: Return early if Cluster is paused
  exp/controllers/awsmachinepool_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#5647 🐛 Fix ignition version defaulting to consider if the storageType gets defaulted itself
  api/v1beta2/awsmachine_webhook.go
  exp/api/v1beta2/awsmachinepool_webhook.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#5654 :bug: Make print-policy consistent with print-cloudformation-template
  cmd/clusterawsadm/cloudformation/bootstrap/iam.go
  cmd/clusterawsadm/cmd/bootstrap/iam/iam_doc.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5662 🐛 Fix AWSManagedClusterTemplate short name
  api/v1beta2/awsmanagedclustertemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclustertemplates.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note-action-required, needs-priority

#5629 🐛 ROSA: Fix RosaControlPlane sync default RosaMachinePool
  config/rbac/role.yaml
  controllers/rosacluster_controller.go
  controllers/rosacluster_controller_test.go
  controllers/suite_test.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/controllers/rosamachinepool_controller.go
  exp/utils/rosa_helper.go
  exp/utils/rosa_helper_test.go
  pkg/rosa/ocmclient.go
  test/mocks/ocm_client_mock.go
Labels: kind/bug, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority
