Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2025-05, with the labels that each got.

#4875 ✨feat(awsmachinepool): custom lifecyclehooks for machinepools
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/api/v1beta2/awsmachinepool_webhook.go
  exp/api/v1beta2/awsmachinepool_webhook_test.go
  exp/api/v1beta2/awsmanagedmachinepool_types.go
  exp/api/v1beta2/awsmanagedmachinepool_webhook.go
  exp/api/v1beta2/conditions_consts.go
  exp/api/v1beta2/types.go
  exp/api/v1beta2/validation.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/lifecyclehook.go
  pkg/cloud/services/autoscaling/lifecyclehook_test.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/service.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/autoscaling_interface_mock.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5474 :bug: Don't overwrite subnet spec tags with AWS tags
  pkg/cloud/services/network/subnets.go
  pkg/cloud/services/network/subnets_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#5348 🌱 chore: graduate garbage collection
  Makefile
  config/manager/manager.yaml
  devbox.lock
  docs/book/src/topics/external-resource-gc.md
  feature/feature.go
  scripts/ci-e2e-eks-gc.sh
  scripts/ci-e2e-gc.sh
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/gcworkload.yaml
  test/e2e/suites/gc_managed/gc_managed_suite_test.go
  test/e2e/suites/gc_unmanaged/gc_unmanaged_suite_test.go
  test/e2e/suites/managed/gc_test.go
  test/e2e/suites/unmanaged/gc_test.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note-action-required, needs-priority

#5389 ✨ Migrate S3, Sessions and Endpoints packages to AWS SDK v2
  controllers/awscluster_controller.go
  controllers/awscluster_controller_test.go
  controllers/awscluster_controller_unit_test.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_test.go
  controllers/awsmachine_controller_unit_test.go
  go.mod
  go.sum
  pkg/cloud/awserrors/errors.go
  pkg/cloud/endpoints/endpoints.go
  pkg/cloud/endpointsv2/endpoints.go
  pkg/cloud/identityv2/identity.go
  pkg/cloud/interfaces.go
  pkg/cloud/logs/logs.go
  pkg/cloud/metricsv2/metrics.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/fargate.go
  pkg/cloud/scope/global.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/scope/rosacontrolplane.go
  pkg/cloud/scope/rosamachinepool.go
  pkg/cloud/scope/session.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/objectstore_machine_interface_mock.go
  pkg/cloud/services/s3/mock_s3iface/doc.go
  pkg/cloud/services/s3/mock_s3iface/s3api_mock.go
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
  pkg/logger/logger.go
  test/mocks/capa_clusterscoper_mock.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, ok-to-test, needs-priority

#5496 :bug: Launchtemplate needs to be updated if spot options are changed
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5456 🐛 Fix error message in rosa control plane controller
  controlplane/rosa/controllers/rosacontrolplane_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, ok-to-test, needs-priority

#5458 🐛 fix(addons): avoid infinite reconciliation loop
  pkg/cloud/services/eks/addons.go
  pkg/eks/addons/types.go
  pkg/eks/addons/types_test.go
Labels: size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, kind/regression, needs-priority
