Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2025-06, with the labels that each got.

#5461 🐛 Skip adding reserved aws internal tags to resources as they are invalid
  pkg/cloud/converters/tags.go
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority

#5497 ✨Migrate autoscaling to AWS SDK V2
  go.mod
  go.sum
  pkg/cloud/converters/tags.go
  pkg/cloud/scope/clients.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/autoscaling/autoscalinggroup_test.go
  pkg/cloud/services/autoscaling/lifecyclehook.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscaling_mock.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/autoscalingapi_mock.go
  pkg/cloud/services/autoscaling/mock_autoscalingiface/doc.go
  pkg/cloud/services/autoscaling/service.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/eks/service.go
  pkg/cloud/services/eks/tags.go
  pkg/cloud/services/s3/s3.go
  pkg/utils/utils.go
  test/e2e/shared/aws.go
  test/e2e/shared/context.go
  test/e2e/shared/suite.go
  test/e2e/suites/managed/eks_ipv6_test.go
  test/e2e/suites/managed/eks_legacy_test.go
  test/e2e/suites/managed/eks_test.go
  test/e2e/suites/managed/helpers.go
  test/e2e/suites/managed/machine_pool.go
Labels: size/XXL, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, kind/deprecation, needs-priority

#5508 :bug: Update launch template if PrivateDnsName changes
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5523 🐛 Fix determined value for `MinSize` field of ASG
  pkg/cloud/services/autoscaling/autoscalinggroup.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#5502 :sparkles: Update go-apidiff
  hack/tools/go.mod
  hack/tools/go.sum
Labels: kind/support, size/L, release-note-none, approved, cncf-cla: yes, lgtm, needs-priority

#5527 🐛 Fix session creation in e2e test suite
  test/e2e/shared/aws.go
  test/e2e/shared/context.go
  test/e2e/shared/suite.go
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5363 :bug: fix(EmptyRoutesDefaultVPCSecurityGroup): empty rule should not produce a warning event
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#5531 🐛 fix: default bastion ami lookup
  pkg/cloud/services/ec2/ami.go
Labels: kind/bug, priority/critical-urgent, approved, cncf-cla: yes, lgtm, size/XS, release-note

#5522 🌱 Add machine pool template for Flatcar Linux
  docs/book/src/development/releasing.md
  templates/cluster-template-flatcar-machinepool.yaml
Labels: kind/support, size/XXL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5392 🌱 feat: add kal linter
  .github/workflows/pr-golangci-lint.yaml
  .golangci-kal.yml
  .golangci.yml
  Makefile
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/awsclustertemplate_conversion.go
  api/v1beta1/awsidentity_conversion.go
  api/v1beta1/awsmachine_conversion.go
  api/v1beta1/conversion.go
  api/v1beta1/conversion_test.go
  bootstrap/eks/api/v1beta1/conversion.go
  bootstrap/eks/api/v1beta1/conversion_test.go
  cmd/clusterawsadm/api/bootstrap/v1alpha1/conversion.go
  controlplane/eks/api/v1beta1/conversion.go
  controlplane/eks/api/v1beta1/conversion_test.go
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/conversion_test.go
  hack/tools/.custom-gcl.yaml
  test/e2e/shared/aws_helpers.go
  versions.mk
Labels: size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5318 ✨ Support storing Ignition user data in S3 bucket for `AWSMachinePool`
  api/v1beta2/awsmachine_types.go
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/tags.go
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  controllers/awsmachine_controller.go
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/api/v1beta2/awsmachinepool_webhook.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/awsmanagedmachinepool_controller.go
  pkg/cloud/scope/ignition.go
  pkg/cloud/scope/launchtemplate.go
  pkg/cloud/scope/machinepool.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/ec2/launchtemplate_test.go
  pkg/cloud/services/interfaces.go
  pkg/cloud/services/mock_services/ec2_interface_mock.go
  pkg/cloud/services/mock_services/objectstore_machine_interface_mock.go
  pkg/cloud/services/mock_services/reconcile_interface_mock.go
  pkg/cloud/services/s3/mock_s3iface/s3api_mock.go
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, release-note-action-required, needs-priority

#5558 🐛 Fix missing CRD validation for Amazon Linux 2023 eksLookupType
  api/v1beta2/types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority
