Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2025-03, with the labels that each got.

#5357 [release-2.7] ✨ release-2.7 cherry pick rosa changes
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  docs/book/src/topics/rosa/creating-a-cluster.md
  docs/book/src/topics/rosa/upgrades.md
  exp/api/v1beta2/conditions_consts.go
  exp/api/v1beta2/rosamachinepool_types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
  exp/controllers/suite_test.go
  pkg/cloud/scope/rosacontrolplane.go
  pkg/cloud/scope/rosamachinepool.go
  pkg/rosa/client.go
  pkg/rosa/client_test.go
  pkg/rosa/idps.go
  pkg/rosa/ocmclient.go
  pkg/rosa/versions.go
  test/mocks/generate_capa.go
  test/mocks/ocm_client_mock.go
Labels: release-note-none, size/XXL, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#5337 🌱 ROSA Modified rosacontrolplane_controller version error messages.
  controlplane/rosa/controllers/rosacontrolplane_controller.go
Labels: release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority, area/provider/rosa

#5358 :bug: ROSA: Add instructions to activate a newly created service account
  docs/book/src/topics/rosa/creating-a-cluster.md
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-priority, area/provider/rosa

#5377 🌱 [release-2.6] Bump golangci-lint to v1.62.2 and fix all lint errors
  .github/workflows/pr-golangci-lint.yaml
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/api/v1beta2/awsmanagedmachinepool_webhook.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/rosamachinepool_controller.go
  pkg/cloud/scope/fargate.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/scope/rosamachinepool.go
  pkg/cloud/scope/session.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/eks/eks.go
  pkg/cloud/services/eks/fargate.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/network/network.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/internal/cidr/cidr.go
  pkg/rosa/helpers.go
  test/e2e/shared/aws.go
  test/e2e/shared/exec.go
  test/e2e/suites/unmanaged/helpers_test.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, ok-to-test, needs-priority

#5382 🌱 Fix test version string in order to use manifests from source files
  test/e2e/data/e2e_eks_conf.yaml
Labels: release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, size/XS, needs-priority

#5268 :book: Clarify that the ROSA provider is currently for ROSA HCP clusters
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  docs/book/src/topics/rosa/creating-a-cluster.md
  docs/book/src/topics/rosa/enabling.md
  docs/book/src/topics/rosa/external-auth.md
  docs/book/src/topics/rosa/support.md
Labels: size/M, release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, needs-priority

#5319 ✨ Add AWSMachines to back the EC2 instances in AWSMachinePools and AWSManagedMachinePools
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
  config/rbac/role.yaml
  controllers/awsmachine_controller.go
  exp/api/v1beta1/conversion.go
  exp/api/v1beta1/zz_generated.conversion.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/api/v1beta2/conditions_consts.go
  exp/api/v1beta2/types.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/awsmachinepool_machines.go
  feature/feature.go
  feature/gates.go
  pkg/cloud/awserrors/errors.go
  pkg/cloud/scope/machine.go
  pkg/cloud/services/ec2/instances.go
Labels: kind/feature, size/XL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5376 :book: Fix link to AWS ROSA documentation
  docs/book/src/topics/rosa/creating-a-cluster.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, ok-to-test, needs-priority

#5379 ✨Add support for public-only networking
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/network/subnets.go
Labels: kind/feature, release-note-none, approved, cncf-cla: yes, lgtm, size/S, ok-to-test, needs-priority

#5397 🌱 chore: update metadata for v2.8.x release series
  metadata.yaml
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#5383 ✨ Set Paused condition on reconciled resources status upon reconciliation being paused
  bootstrap/eks/controllers/eksconfig_controller.go
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controllers/awsmachine_controller_unit_test.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/controllers/awsmanagedmachinepool_controller.go
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
  util/paused/paused.go
  util/paused/paused_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5222 ✨ Support for BoostrapSelfManagedAddons flag for EKS cluster creation
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  controlplane/eks/api/v1beta1/conversion.go
  controlplane/eks/api/v1beta1/zz_generated.conversion.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/services/eks/cluster.go
  pkg/cloud/services/eks/cluster_test.go
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/eks/cluster-template-eks-control-plane-bare-eks.yaml
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5394 ✨ Updates AWSManagedCluster, ROSACluster with Paused Condition
  api/v1beta2/awsmanagedcluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_rosaclusters.yaml
  controllers/awsmanagedcluster_controller.go
  controllers/rosacluster_controller.go
  exp/api/v1beta2/rosacluster_types.go
  exp/api/v1beta2/zz_generated.deepcopy.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, kind/api-change, ok-to-test, needs-priority

#5417 🐛 Allow controllers to patch clusters/status
  config/rbac/role.yaml
  controllers/awscluster_controller.go
  controllers/awsmanagedcluster_controller.go
  controllers/rosacluster_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  exp/controllers/awsfargatepool_controller.go
Labels: kind/bug, priority/critical-urgent, release-note-none, approved, cncf-cla: yes, lgtm, size/S, kind/release-blocking

#5421 🌱 Devbox update
  .devcontainer/devcontainer.json
  devbox.json
  devbox.lock
  scripts/devbox-init-hook.sh
Labels: kind/support, release-note-none, size/XL, approved, cncf-cla: yes, lgtm, needs-priority

#5395 :sparkles: Allow disabling controllers
  controllers/disabled_controllers.go
  controllers/disabled_controllers_unit_test.go
  docs/proposal/20250314-optional-controllers.md
  main.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5425 🐛 fix: ensure patching correct object for paused
  config/rbac/role.yaml
  controllers/awscluster_controller.go
  controllers/awsmanagedcluster_controller.go
  controllers/rosacluster_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  exp/controllers/awsfargatepool_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#5418 🐛 fix: efs & elb upgrade e2e tests
  controllers/awscluster_controller.go
  controllers/awscluster_controller_unit_test.go
  main.go
  test/e2e/data/e2e_conf.yaml
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/efs-support/patches/efs-support.yaml
  test/e2e/shared/aws_helpers.go
  test/e2e/suites/unmanaged/helpers_test.go
Labels: size/L, approved, cncf-cla: yes, lgtm, kind/failing-test, release-note, needs-priority

#5422 :seedling: Retry boskos account checkouts
  hack/boskos.py
Labels: kind/support, release-note-none, approved, cncf-cla: yes, lgtm, size/S, needs-priority

#5428 🌱 cloudbuild: bump gcb image to get go 1.23
  cloudbuild-nightly.yaml
  cloudbuild.yaml
Labels: kind/support, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#5431 [release-2.7] :seedling: Bump golangci-lint to v1.62.2 and fix all lint errors
  .github/workflows/pr-golangci-lint.yaml
  .golangci.yml
  bootstrap/eks/controllers/eksconfig_controller.go
  bootstrap/eks/controllers/eksconfig_controller_reconciler_test.go
  cmd/clusterawsadm/ami/helper.go
  cmd/clusterawsadm/cloudformation/bootstrap/template_test.go
  controllers/awscluster_controller.go
  controllers/awsmachine_controller.go
  controlplane/eks/controllers/awsmanagedcontrolplane_controller.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  exp/api/v1beta2/awsmachinepool_types.go
  exp/api/v1beta2/awsmanagedmachinepool_webhook.go
  exp/controllers/awsmachinepool_controller.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/rosamachinepool_controller.go
  pkg/cloud/scope/fargate.go
  pkg/cloud/scope/managednodegroup.go
  pkg/cloud/scope/rosamachinepool.go
  pkg/cloud/scope/session.go
  pkg/cloud/scope/session_test.go
  pkg/cloud/services/autoscaling/autoscalinggroup.go
  pkg/cloud/services/ec2/bastion.go
  pkg/cloud/services/ec2/launchtemplate.go
  pkg/cloud/services/eks/eks.go
  pkg/cloud/services/eks/fargate.go
  pkg/cloud/services/eks/nodegroup.go
  pkg/cloud/services/elb/loadbalancer.go
  pkg/cloud/services/elb/loadbalancer_test.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/network.go
  pkg/cloud/services/network/secondarycidr.go
  pkg/cloud/services/secretsmanager/secret.go
  pkg/cloud/services/securitygroup/securitygroups.go
  pkg/cloud/services/ssm/secret.go
  pkg/internal/cidr/cidr.go
  pkg/rosa/helpers.go
  test/e2e/shared/aws.go
  test/e2e/shared/exec.go
  test/e2e/suites/unmanaged/helpers_test.go
  util/system/util_test.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, needs-priority

#5430 [release-2.7] :bug: fix: efs e2e test breaking
  test/e2e/data/infrastructure-aws/withoutclusterclass/kustomize_sources/efs-support/patches/efs-support.yaml
  test/e2e/suites/unmanaged/helpers_test.go
Labels: release-note-none, approved, cncf-cla: yes, lgtm, kind/failing-test, size/S, needs-priority

#5429 :book: Document latest release obstacles
  docs/book/src/development/releasing.md
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/S, needs-priority

#5435 [release-2.7] 🌱 Bump github.com/golang-jwt/jwt to 4.5.2 and 5.5.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#5436 [release-2.8] 🌱 Bump github.com/golang-jwt/jwt to v4.5.2 and v5.2.2
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#5437 🌱 Bump to go 1.23
  .github/workflows/dependabot.yml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/release.yaml
  Makefile
  netlify.toml
Labels: kind/support, approved, cncf-cla: yes, lgtm, size/S, release-note, needs-priority

#5440 :seedling: Document how previous versions are found
  .github/workflows/release.yaml
Labels: release-note-none, approved, cncf-cla: yes, kind/documentation, lgtm, size/XS, needs-priority
