Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2025-08, with the labels that each got.

#5375 ✨ Add ClusterClass support for EKS clusters
  api/v1beta2/awsmanagedclustertemplate_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmanagedclustertemplates.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_awsmanagedclustertemplates.yaml
  config/crd/patches/cainjection_in_awsmanagedcontrolplanetemplates.yaml
  config/crd/patches/webhook_in_awsmanagedcontrolplanetemplates.yaml
  config/webhook/manifests.yaml
  controlplane/eks/api/v1beta1/conversion.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_types.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplane_webhook_test.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplanetemplate_types.go
  controlplane/eks/api/v1beta2/awsmanagedcontrolplanetemplate_webhook.go
  controlplane/eks/api/v1beta2/zz_generated.deepcopy.go
  main.go
  templates/cluster-template-eks-clusterclass.yaml
  test/e2e/data/e2e_eks_conf.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/eks-clusterclass/cluster-template.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/eks-clusterclass/clusterclass-eks-e2e.yaml
  test/e2e/data/infrastructure-aws/withclusterclass/kustomize_sources/eks-clusterclass/kustomization.yaml
  test/e2e/suites/managed/control_plane_helpers.go
  test/e2e/suites/managed/eks_clusterclass_test.go
  test/e2e/suites/managed/helpers.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5601 🌱 Migrate sts to sdk v2
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  controlplane/rosa/controllers/rosacontrolplane_controller_test.go
  exp/controllers/awsmachinepool_controller_test.go
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
  pkg/cloud/endpointsv2/endpoints.go
  pkg/cloud/scope/clients.go
  pkg/cloud/scope/rosacontrolplane.go
  pkg/cloud/services/eks/config.go
  pkg/cloud/services/eks/config_test.go
  pkg/cloud/services/eks/service.go
  pkg/cloud/services/s3/mock_stsiface/doc.go
  pkg/cloud/services/s3/s3.go
  pkg/cloud/services/s3/s3_test.go
  pkg/cloud/services/sts/mock_stsiface/doc.go
  pkg/cloud/services/sts/mock_stsiface/stsiface_mock.go
  pkg/cloud/services/sts/mock_stsiface/stsiface_mock_v1.go
  pkg/cloud/services/sts/mock_stsiface/stsiface_mock_v2.go
  pkg/cloud/services/sts/sts.go
  test/e2e/shared/aws.go
  test/e2e/shared/suite.go
Labels: size/XL, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, kind/deprecation, needs-priority

#5330 :sparkles: Addons: Add functionality for resolveConflicts: PRESERVE
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanetemplates.yaml
  controlplane/eks/api/v1beta2/types.go
  docs/book/src/topics/eks/addons.md
  pkg/cloud/services/eks/addons.go
Labels: kind/feature, size/M, release-note-none, approved, cncf-cla: yes, lgtm, tide/merge-method-squash, ok-to-test, needs-priority

#5615 ✨ Migrate Secrets Manager packages to AWS SDK v2
  pkg/cloud/endpointsv2/endpoints.go
  pkg/cloud/scope/clients.go
  pkg/cloud/services/secretsmanager/secret.go
  pkg/cloud/services/secretsmanager/secret_test.go
  test/mocks/aws_secretsmanager_mock.go
  test/mocks/generate_aws.go
Labels: kind/feature, size/M, approved, cncf-cla: yes, lgtm, release-note, kind/cleanup, ok-to-test, needs-priority

#5616 🐛 ROSA: Fix update channel group
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  controlplane/rosa/controllers/rosacontrolplane_controller_test.go
  go.mod
  go.sum
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5621 :bug: Remove deleted `--short` option for kubectl
  test/helpers/kubernetesversions/data/debian_injection_script.envsubst.sh.tpl
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, needs-priority

#5622 🌱 e2e: create tarball as artifact with pod logs for debugging
  test/e2e/shared/common.go
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#5628 :seedling: remove kpromo from hack/tools/go.mod and directly install it instead
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  versions.mk
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, kind/cleanup, needs-priority

#5633 🐛 Add validation to prevent Spot instances with CapacityReservationsOnly preference
  api/v1beta2/awsmachine_types.go
  api/v1beta2/awsmachine_webhook.go
  api/v1beta2/awsmachine_webhook_test.go
  api/v1beta2/types.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
Labels: kind/bug, size/M, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5342 🐛 Add missing IAM permission `ec2:RevokeSecurityGroupEgress` for `emptyRoutesDefaultVPCSecurityGroup` option
  cmd/clusterawsadm/cloudformation/bootstrap/cluster_api_controller.go
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/customsuffix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/default.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_all_secret_backends.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_allow_assume_role.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_custom_bootstrap_user.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_different_instance_profiles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_console.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_default_roles.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_disable.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_eks_kms_prefix.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_extra_statements.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_s3_bucket.yaml
  cmd/clusterawsadm/cloudformation/bootstrap/fixtures/with_ssm_secret_backend.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S, release-note, ok-to-test, needs-priority

#5602 :sparkles: Create only one nat gateway per AZ
  controlplane/eks/controllers/awsmanagedcontrolplane_controller_test.go
  pkg/cloud/services/network/natgateways.go
  pkg/cloud/services/network/natgateways_test.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority
