Repository kubernetes-sigs/cluster-api-provider-aws, pull requests merged in 2025-04, with the labels that each got.

#5386 :bug: ROSA: Apply CAPI machinepool changes to ROSAMachinePool
  exp/controllers/rosamachinepool_controller.go
  exp/controllers/rosamachinepool_controller_test.go
  templates/cluster-template-rosa-machinepool.yaml
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority, area/provider/rosa

#5452 🌱 Fix envsubstr installation in Devbox
  devbox.json
  scripts/devbox-init-hook.sh
Labels: size/M, release-note-none, approved, cncf-cla: yes, lgtm, ok-to-test, needs-priority

#5374 🐛 add marketType field validation
  api/v1beta2/awsmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
  exp/api/v1beta2/awsmachinepool_webhook.go
  exp/api/v1beta2/awsmachinepool_webhook_test.go
  pkg/cloud/services/ec2/instances.go
  pkg/cloud/services/ec2/instances_test.go
Labels: size/L, release-note-none, approved, cncf-cla: yes, lgtm, tide/merge-method-squash, ok-to-test, needs-priority

#5462 :bug: Wire logger into machine scope
  controllers/awsmachine_controller.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/XS, release-note, needs-priority

#5459 🌱 chore: bump calico for e2e tests
  test/e2e/data/cni/calico.yaml
Labels: kind/support, size/XXL, approved, cncf-cla: yes, lgtm, release-note, needs-priority

#5465 :bug: Typo fixes
  main.go
Labels: kind/bug, release-note-none, approved, cncf-cla: yes, lgtm, size/XS, ok-to-test, needs-priority

#5443 :bug: Add Version to ROSA Control Plane Status
  config/crd/bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
  controlplane/rosa/api/v1beta2/rosacontrolplane_types.go
  controlplane/rosa/controllers/rosacontrolplane_controller.go
  controlplane/rosa/controllers/rosacontrolplane_controller_test.go
  controlplane/rosa/controllers/suite_test.go
  exp/controllers/rosamachinepool_controller_test.go
Labels: kind/bug, size/L, approved, cncf-cla: yes, lgtm, release-note, ok-to-test, needs-priority

#5224 ✨ Support additional security group ingress rules for all nodes
  api/v1beta1/awscluster_conversion.go
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/awscluster_webhook.go
  api/v1beta2/awscluster_webhook_test.go
  api/v1beta2/network_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
  pkg/cloud/scope/cluster.go
  pkg/cloud/scope/managedcontrolplane.go
  pkg/cloud/scope/sg.go
  pkg/cloud/services/securitygroup/securitygroups.go
Labels: kind/feature, size/L, approved, cncf-cla: yes, lgtm, release-note, needs-priority
